### ISSUE TITLE
🐛 Bug Report: UI fixes

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#1014]
### 📜 Description

* Conversation Bubble Padding does't match the [Figma Design](https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=NIzl3TBjsWZvZKc8-0)
* The  gap between Conversations bubbles wrapper and Prompts input wrapper is tight and Vary across screen resolutions.
* ~~There isn't an icon for exiting Settings screen and returning to Ongoing Conversation screen. Currently, it's a manual switch.~~

### 👟 Reproduction steps

1. Try adding a line in input field prompt
2. Simulate the interface on varying screen resolutions

### 👍 Expected behavior

Responsive User Interface for all screen resolutions, aligned with the UI design.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/96079232/d5ebe76f-4c92-4f15-8777-8c10d79d925b)
Figma design
![image](https://github.com/arc53/DocsGPT/assets/96079232/3c767e25-0185-4cf0-90c0-96a14011f8ee)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utin-francis-peter** [comment]
Hi, @dartpain 

I'd love to jump on these fixes. Kindly assign to me.
