### ISSUE TITLE
Feature: Set default i18n language depending on browsers language

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1016]
Set i18n initial language using browsers default one, make sure they are able to change it later

**Comment by utin-francis-peter** [comment]
Hi, @dartpain 

I am on this issue now. 

Please confirm: if a user's default browser language is set to a language that isn't English nor our currently supported language options, default in that case should be set to English?

**Comment by dartpain** [comment]
Yeep, thats correct!
