### ISSUE TITLE
🚀 Feature: Create reusable input field component and cleanup code

### ISSUE THREAD

**Issue by siiddhantt** [arc53/DocsGPT#1017]
### 🔖 Feature description

Create a reusable input field component to replace redundant Tailwind CSS classes, ensuring consistent styling and cleaner code.

### 🎤 Why is this feature needed ?

Reduce redundancy, ensure consistency, improve maintainability, enhance code quality, and clean up the codebase.

### ✌️ How do you aim to achieve this?

Identify common patterns, create a reusable component, replace existing fields and test thoroughly.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by utin-francis-peter** [comment]
Hi, @dartpain  @siiddhantt 

I've studied the repetitive usage of text input across multiple files - like `APIKeyModal`, `PromptsModal`, `APIKeys`, and `Upload`- and currently designing the component.

I also noted an editable `div` element is used for entering prompts which could also use the `Input` component in view.   

Kindly assign me the issue.
