### ISSUE TITLE
🐛 Bug Report: UX enhancement

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#1019]
### 📜 Description

1. Training modal should close automatically on completion.

### 👟 Reproduction steps

1) In the sidebar upload documents, on complete training the FINISH button is to be clicked as per the current strategy.

### 👍 Expected behavior

1) On complete training of  the document the modal should automatically close

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/96079232/2fcc587e-1270-4d67-8fc2-2dc91b60afac)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

yes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayelimdejesus** [comment]
Hi, I would like to work on this issue. Thank you.
