### ISSUE TITLE
🐛 Bug Report: Query Bar Overflow with Long Text Input

### ISSUE THREAD

**Issue by shelar1423** [arc53/DocsGPT#1021]
### 📜 Description

 When long text is pasted into the query bar, it expands horizontally beyond its intended size.

### 👟 Reproduction steps

1. Copy a long text string.
2. Paste the text into the query bar.

### 👍 Expected behavior

The query bar should maintain its fixed width and handle long text by either wrapping it within the bar or providing a scrollable view.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/82649533/70db2cac-3d62-4cba-8c93-7a7ff6a7a2ff)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayelimdejesus** [comment]
Hi, I would like to work on this issue please. Thank you.

**Comment by shelar1423** [comment]
> Hi, I would like to work on this issue please. Thank you.

Assigned it to you!

**Comment by sarthaklaptop** [comment]
Hello @shelar1423 I created a PR on this issue please review it

**Comment by siiddhantt** [comment]
hi @shelar1423 does this bug still needs to be resolved in the current version of the query box?

**Comment by shelar1423** [comment]
hey @siiddhantt i feel this still needs to be fixed as when we paste the long text the last sentences is not visible.

**Comment by chickenleaf** [comment]
hello @shelar1423 can i have this assigned to me?

**Comment by siiddhantt** [comment]
hi @chickenleaf , I think @sarthaklaptop has already linked a PR for it that resolves it. I'll look into closing this issue, so maybe you could check out other ones. Thanks!
