### ISSUE TITLE
🐛 Bug Report: Code Display Overflow and Formatting Issue

### ISSUE THREAD

**Issue by shelar1423** [arc53/DocsGPT#1022]
### 📜 Description

The code display section does not handle code formatting properly, causing the code to overflow horizontally and extending beyond its intended bounds.

### 👟 Reproduction steps

1. Insert or paste code into the code display section/query bar(mostly the code with many indentations and spaces).
2. Observe the rendering of the code.

### 👍 Expected behavior

The code should be properly formatted within the container, with line breaks and proper indentation to ensure readability. The code display section should handle overflow correctly, either by wrapping the code within the container or providing a scrollable view.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/82649533/f4a85a49-d379-4f71-b292-4340db5b4159)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shelar1423** [comment]
> Working on this. please assign me the issue in the meantime

Assigned it, thank you!

**Comment by moink7** [comment]
Hi, im working on this issue, please assign me!
