### ISSUE TITLE
🐛 Bug Report: Misaligned Submit Button in Query Bar

### ISSUE THREAD

**Issue by shelar1423** [arc53/DocsGPT#1023]
### 📜 Description

the submit button in the query bar appears misaligned within its container. This misalignment affects the visual aesthetics and usability of the query bar.

### 👟 Reproduction steps

1. Navigate to the interface with the query bar and hover upon it.
2. Observe the submit button within the query bar.

### 👍 Expected behavior

The submit button should be perfectly centered and aligned within its circular container, ensuring a clean and user-friendly appearance.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/82649533/3adf6d1d-e26d-481d-a378-0b9a1b754f47)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarthaklaptop** [comment]
Is this issue still open ?

**Comment by blackviking27** [comment]
This icon is perfectly aligned but visually it seems a little off. adding a little padding / margin on left and adjusting the icon width will center  the icon visually which can be seen in the below diagram. 

![search-center](https://github.com/arc53/DocsGPT/assets/46470516/547d8bb1-c4cf-4079-8f59-9d87d16deaf7)

**Comment by shelar1423** [comment]
> Is this issue still open ?
> ![Screenshot from 2024-07-02 22-28-45](https://github.com/arc53/DocsGPT/assets/101018384/ab50b00f-c254-401b-a9c6-94dca0e66644)
> for me the submit button is perfectly centered in laptop and mobile screen
> 
> 

Yes it is open,you can try to make it a bit more aligned visually as it requires some padding

**Comment by nayelimdejesus** [comment]
Hi, I would like to work on this issue.

**Comment by blackviking27** [comment]
@utin-francis-peter I looked at your css changes and would like to point out that the Icon still seems a little off.  I added some of my css changes to visually align the icon to center. You can see the difference below

`your css`
![search-center](https://github.com/arc53/DocsGPT/assets/46470516/5f38aa2c-0702-4a9e-80ae-1fe307d35658)

adding only `ml-[4px] h-6` classes to the img tag
![correct-search](https://github.com/arc53/DocsGPT/assets/46470516/b2ea38c9-30c2-4a84-a251-41e840e7608e)

I hope you can see the differences, You can implement these changes or try something new. Hope this helps

**Comment by utin-francis-peter** [comment]
The all mighty CSS at it again, lol. 

@blackviking27 I've modified the styles using the highlighted classes. Pls have a look.

Thanks.

**Comment by blackviking27** [comment]
@utin-francis-peter Looks pretty good now. Don't see the need to add `flex-shrink-0` and also `p-4` would align better with border of the input text.

**Comment by chickenleaf** [comment]
@blackviking27  hello!! is this still up for grabs?
