### ISSUE TITLE
🚀 Feature: Integrated a new Vector DB Milvus

### ISSUE THREAD

**Issue by Jacksonxhx** [arc53/DocsGPT#1046]
### 🔖 Feature description

Add a new Vector DB into the original project, Milvus

### 🎤 Why is this feature needed ?

This provides more options for customers to choose from

### ✌️ How do you aim to achieve this?

Milvus integration which already done

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
Was added
https://github.com/arc53/DocsGPT/blob/main/application/vectorstore/milvus.py
