### ISSUE TITLE
🐛 Bug Report: Streaming Issue

### ISSUE THREAD

**Issue by shriyaMadan** [arc53/DocsGPT#1074]
### 📜 Description

When a user creates a new chat, and receives response on the prompt entered, meanwhile tries switching the chat. It appends the prompt response within the old chat  selected by the user. And in sometime the app crashes.

### 👟 Reproduction steps

1. Let's say user has multiple chat windows open, to explain let us suppose 2 different chat boxes are being used.
2. On the first chat box user clicks and types a message.
3. By the time the prompt answer is being fetched by DocsGPT, the user clicks on 2nd chat box.
4. As the 2nd or any other chat is clicked/selected by user from the left side, the prompt response appends in this chat.
5. The app then crashes completely.

### 👍 Expected behavior

It should smoothly allow user to switch between chats without crashing/appending previous response to this selected chat.

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/b8922e3c-eafe-4799-81c8-b100a7d600e9

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Thank you, thats a good issue, assigned to you!
