### ISSUE TITLE
🐛 Bug Report: CSV upload doesn't work

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1106]
### 📜 Description

CSV format upload doesn't work.

### 👟 Reproduction steps

1. Click on upload
2. Select .csv file

### 👍 Expected behavior

Name field should display the selected .csv file. After that user should be able to press train. 

### 👎 Actual Behavior with Screenshots

Name field stays empty. Train button is locked. 

### 💻 Operating system

MacOS

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ruhi47** [comment]
Hi, I can help, have experience with GenAI Chatbots.
Please assign me, Thank you!

**Comment by dartpain** [comment]
Appreciate your interest @ruhi47
Unfortunately this issue is fixed.
Please check out our other issues or suggest yours. 
Thank you!
