### ISSUE TITLE
Multiple language support i18n

### ISSUE THREAD

**Issue by detasar** [arc53/DocsGPT#113]
I want to help with Turkish Lang support 
how can i help? ocr & LM's?

**Comment by dartpain** [comment]
Turkinsh language in the UI? would love help woth that, will probably need i18n plugin for it

**Comment by oznav2** [comment]
will be very helpful to add i18n also for Hebrew. please note the filename issue. currently when the filename is not set in english characters the ingest function and parsing process will fail.

**Comment by AshkanArabim** [comment]
I'd be happy to assist with Persian if it's on the agenda! Not sure if there's an update on the i18n plugin?

**Comment by krabbi** [comment]
Would like to add i18n plugin for static UI texts. Who can I ask to assist with design of language selector?

**Comment by dartpain** [comment]
Thats a good issue to work on @krabbi 
@tenokami please think of the design, I think we can have it in a settings menu?

**Comment by tenokami** [comment]
@dartpain I can't think of a better place than there. Need to wait when the settings page is implemented after the wireframes are ready.
