### ISSUE TITLE
Create a dropdown instead of about menu.

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1165]
Create a dropdown that will be in place instead of the about menu.
Dropdown will say Help with a respective icon
Dropdown will have a few options:
Email us with a mailto link for contact@arc53.com
Documentation, that will open https://docs.docsgpt.cloud/ in an external page

**Comment by rudradeep22** [comment]
Can this issue be assigned to me? I'd like to work on this

**Comment by pragyananda** [comment]
hello , anyone working on this issue if not can I do ?

**Comment by AnujSaha0111** [comment]
Can you assign it to me?

**Comment by anurag-4508** [comment]
Can you please assign this issue to me. I want to work on it.
Thank you
