### ISSUE TITLE
[BUG] Make sure users can only send feedback once on convo and make it persistent

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1166]
Basically both on a normal conversation page and on a shared conversation page its sometimes possible to submit feedback twice after refreshing / reloading the page. It good to make feedback persistend

**Comment by sidhanshamil** [comment]
I would like to work on this

**Comment by anurag-4508** [comment]
Is this issue still open? I want to work on it. Please assign me this task.
Thank you

**Comment by Niharika0104** [comment]
@dartpain Can you assign this issue to me?
