### ISSUE TITLE
Drag and drop training, from input box

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1167]
Basically should trigger from file training process once a user drags and drops a file into the input box

**Comment by sahil9001** [comment]
Hey, can you please assign this to me?

**Comment by sahil9001** [comment]
Just wanted to ask, wouldn't this be cost inefficient? Like a user might just drop the file accidentally and the system would train on it. I feel that it should be trained when user submits the file to the system instead of dropping it directly. 

Please let me know if you have any reasoning to this

**Comment by dartpain** [comment]
Im not sure may people put things into the input box, even on github it assumes the your are uploading an attachment. Would agree if it was a larger area.

**Comment by sahil9001** [comment]
> Im not sure may people put things into the input box, even on github it assumes the your are uploading an attachment. Would agree if it was a larger area.

But that's upload, right? Wouldn't training consume COGS/cost to DocsGPT with no reason? Assuming if a user uploads a big text file (1M Tokens), and then removes, let's say this happens 10 times, wouldn't the cost for 10M tokens incur on DocsGPT?

**Comment by dartpain** [comment]
Once user drags a file we should pop open the training modal to show progress.
In this case we can just preload that document into modal and wait till user clicks train

**Comment by ssilare-adobe** [comment]
Got it, I will raise a PR. Thanks!

**Comment by sahil9001** [comment]
Got it, I will raise a PR for this. Thanks!

**Comment by anurag-4508** [comment]
Is this issue still open? I want to work on it. Please assign me this task.
Thank you

**Comment by dartpain** [comment]
@sahil9001

**Comment by sahil9001** [comment]
hey @dartpain sorry i missed this, i am working on it.

**Comment by sahil9001** [comment]
@dartpain Can you please clear this one last time? I mean the flow, it is —

1. User picks a file.
2. It auto uploads.
3. Training modal opens up and file auto trains
5. Finish


Is this correct?

**Comment by dartpain** [comment]
Think we decided to change it a bit based on you comments.
1. Users drops file into the input box
2. Upload box open, not training yet, just preloaded the document
![CleanShot 2024-10-07 at 11 21 57@2x](https://github.com/user-attachments/assets/ff27d641-9483-4b02-a458-810404ea57f1)

**Comment by ManishMadan2882** [comment]
@sahil9001 is there any update?

**Comment by sahil9001** [comment]
No, you can take it up if you want to, occupied with other work

**Comment by ManishMadan2882** [comment]
@anurag-4508

**Comment by Srayash** [comment]
@ManishMadan2882 what is meant by input box here the textarea or the upload file from device?

**Comment by ManishMadan2882** [comment]
Hi @tenokami,
We are planning to have a feature such that we hover a file over the input box in the Conversations, and the file drop modal pops up, can make it more clear in terms of UX.

**Comment by tenokami** [comment]
> Hi @tenokami, We are planning to have a feature such that we hover a file over the input box in the Conversations, and the file drop modal pops up, can you please make it more clear in terms of UX.

I'm working on design for this and will send you

**Comment by tenokami** [comment]
@ManishMadan2882 

https://www.figma.com/proto/OXLtrl1EAy885to6S69554/DocsGPT?node-id=4924-7643&t=jN2h9b2qkZbZUC3B-1
https://www.figma.com/proto/OXLtrl1EAy885to6S69554/DocsGPT?node-id=4924-7780&t=jN2h9b2qkZbZUC3B-1

![Drag and drop 2](https://github.com/user-attachments/assets/5a90ee6d-ce23-446d-b07d-451d1899ab3d)
![Drag and drop 2 Dark](https://github.com/user-attachments/assets/27fee4e5-642a-49c1-9b7c-a608f0efeccb)


https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=jN2h9b2qkZbZUC3B-1

**Comment by AkashJana18** [comment]
Hey @ManishMadan2882 @tenokami 
I would like to work on this issue can you please assign it to me please.
Thank you.

**Comment by Srayash** [comment]
hey @AkashJana18 I'm working on this issue, expect a PR soon.

**Comment by dartpain** [comment]
Hey @Srayash Is is still active?

**Comment by Srayash** [comment]
Yes, had my end semester exams going on.
Will be working on it soon.

**Comment by Srayash** [comment]
I have set up the dropzone on the conversation bubble currently, onDrop logs the dropped files to the console.(#1459 )
I'll need help with the onDrop function to upload and turn the modal state to active.
