### ISSUE TITLE
Add a default message in the UI when no data is fetched, Example: Settings > Chatbots - No existing Chatbots.

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1169]
Need to handle such empty state and prompt users for action in:

- Settings -> documents menu
- Settings -> chatbots menu

**Comment by anasKhafaga** [comment]
Could you please assign this issue to me @dartpain ?

**Comment by githubashutoshsoni** [comment]
Hi, can you please assign this issue to me?
