### ISSUE TITLE
Re-structure mongodb connection

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1170]
Re structure mongodb connection in the backend.
Make sure its done well in flask and we dont initiate multiple connections in multiple different files.
Please also suggest ideas with some justification.

Thank you!

**Comment by rajveer43** [comment]
I would like to work upon this.

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by dartpain** [comment]
@rajveer43  just politely pinging you if you are still active with the issue. Sorry to disturb if anything.

**Comment by kom-senapati** [comment]
Is this solved

**Comment by dartpain** [comment]
Thats great to hear, please submit PR once you are ready!
Thank you!

**Comment by rajveer43** [comment]
> @rajveer43  just politely pinging you if you are still active with the issue. Sorry to disturb if anything.

Yes am am still active with the issue

**Comment by kom-senapati** [comment]
Are you creating custom class or using Flask Pymongo

**Comment by rajveer43** [comment]
@kom-senapati @dartpain you can assign this to someone else

**Comment by kom-senapati** [comment]
I would like to give it a try @dartpain
