### ISSUE TITLE
🚀 Feature: Add support for mathematical equations in Markdown

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#1175]
### 🔖 Feature description

In Conversations, mathematical notations in the response are hard to comprehend in LaTeX format.
![Screenshot from 2024-09-26 00-45-59](https://github.com/user-attachments/assets/4654f367-17d1-4b14-87ea-afc125358dbb)

### 🎤 Why is this feature needed ?

Responses can cater to the needs of users who rely on accurate and high-quality mathematical typesetting, enhancing the versatility.

### ✌️ How do you aim to achieve this?

By leveraging the react-markdown library with remark-math and rehype-katex plugins.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kom-senapati** [comment]
I would like to solve this issue

**Comment by AniruddhaKundu** [comment]
I would like to solve this issue

**Comment by kom-senapati** [comment]
You can see any other open issue, I am working on it.
