### ISSUE TITLE
🚀 Feature: Creating a reusable loader for all the tabs while fetching responses.

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#1181]
### 🔖 Feature description

1. Create a reusable skeleton component to handle asynchronous data(fetch)
2. Component can be integrated in Settings > Documents, Chatbots, Analytics, logs

### 🎤 Why is this feature needed ?

Improves UX:  Providing a skeleton loader helps maintain user engagement by showing a visual placeholder instead of a blank screen. This reduces perceived loading times and enhances the overall user experience.

### ✌️ How do you aim to achieve this?

The loader component will be designed to be highly flexible and customizable, enabling it to adapt to different shapes and structures (example: tables).

### 🔄️ Additional Information

Skeleton should match the design of the component in the [ConversationBubble](https://github.com/arc53/DocsGPT/blob/350c91889e13e058cd60b879703d478c9a2ea6cc/frontend/src/conversation/ConversationBubble.tsx#L108) component, which appears until the sources are streamed.
<img src="https://cdn.discordapp.com/attachments/1187720917418258485/1290968406228467816/CleanShot_2024-10-02_at_10.27.272x.png?ex=66fe6385&is=66fd1205&hm=59af2b60c5931445c68dd60bbd7f88579a29d61293e6ea9b0ae9a25ea2dcfaf1&"/>
### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by HarshitVashisht11** [comment]
Hi can i fix this issue

**Comment by amansharma612** [comment]
Hi, I would like to work on this issue. Since I am new to this repository, could you please let me know a good starting point for solving this issue? Thanks!

**Comment by Vidhanvyrs** [comment]
hi @ManishMadan2882 can i work on this please assign it to me

**Comment by prathamesh424** [comment]
hi @ManishMadan2882  I want to work on this issue can you assign it to me

**Comment by prathamesh424** [comment]
solved issue #1188

**Comment by prathamesh424** [comment]
I solved the issue in #1188  ,so assign to me and merge  the pull request @larinam

**Comment by prathamesh424** [comment]
@dartpain  updated the settings component

**Comment by KaranSingh36752** [comment]
@prathamesh424 did you make the dark theme also if not I want to make whole website option in dark theme?

**Comment by prathamesh424** [comment]
@dartpain   @larinam @jbampton
### Updated the loading state and loader in the settings component : 

![Screenshot 2024-10-06 110355](https://github.com/user-attachments/assets/ccd1a43c-e3bf-4f0d-94d6-8c321503f56e)
![Screenshot 2024-10-06 110859](https://github.com/user-attachments/assets/d9c6bfdc-f4be-44bd-9c15-3acbe073a0cc)
![Screenshot 2024-10-06 110914](https://github.com/user-attachments/assets/d2aada49-af8b-4d4c-9f87-c3e9a13d61b7)
![Screenshot 2024-10-06 111143](https://github.com/user-attachments/assets/c3229a69-1659-4cc4-934f-d063bc4f6ed8)
![Screenshot 2024-10-06 105221](https://github.com/user-attachments/assets/923291ae-2e9f-44cc-a01c-4e9268e00adf)

**Comment by prathamesh424** [comment]
> @prathamesh424 did you make the dark theme also if not I want to make whole website option in dark theme?

support dark and light theme both

**Comment by KaranSingh36752** [comment]
Yeah i checked it was in settings..

**Comment by prathamesh424** [comment]
@dartpain check out ..
