### ISSUE TITLE
🚀 Feature: Enhance UI Color Scheme to Match Logo Gradient

### ISSUE THREAD

**Issue by rahul0x00** [arc53/DocsGPT#1193]
### 🔖 Feature description

The current UI design does not fully align with the gradient of the logo. I suggest improving the color scheme to better match the logo’s tones.

### 🎤 Why is this feature needed ?

This will create a more cohesive and visually appealing interface.

### ✌️ How do you aim to achieve this?

* Implement a gradient with these colors: #00C9A7, #B66DFF, #FF61A6.
* Consider using gradients for accents and solid colors for buttons/text to keep the design clean.

Proposed Changes Screenshot:
![image](https://github.com/user-attachments/assets/99bc99ce-c576-433c-858d-ae4ebad819e2)

![image](https://github.com/user-attachments/assets/36013027-7281-41a5-b9df-aec0b86cb6c8)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
Interesting idea, but there is one issue, login and sign up are not in the open source version.
