### ISSUE TITLE
🚀 Feature: Add Dark Theme toggle button.

### ISSUE THREAD

**Issue by sanketshinde3001** [arc53/DocsGPT#1195]
### 🔖 Feature description

Add a Dark Theme option, allowing users to switch between light and dark modes for a more comfortable viewing experience.

### 🎤 Why is this feature needed ?

Many users prefer a darker interface. But currently Dark theme is very deep inside settings.

### ✌️ How do you aim to achieve this?

Implement a theme toggle that allows users to switch between light and dark modes. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ManishMadan2882** [comment]
@sanketshinde3001 the feature to toggle themes actually exists in the Settings >  General, 
Thank you!

**Comment by sanketshinde3001** [comment]
@ManishMadan2882 I know they are in settings. But not easily accessible to users.
