### ISSUE TITLE
🚀 Feature: Improvement in Upload Info UI

### ISSUE THREAD

**Issue by sanketshinde3001** [arc53/DocsGPT#1199]
### 🔖 Feature description

Make it UI better.
![image](https://github.com/user-attachments/assets/d14b8ccf-4b7f-4e2f-b6f0-64bb4bfe04d2)

### 🎤 Why is this feature needed ?

Text looks so uneven.

### ✌️ How do you aim to achieve this?

It should show clean and clear.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
Hi can you expand on the uneven text please, if you can attach your proposal it would be great.

Thank you!

**Comment by RonakSurana-2001** [comment]
I am interested to work on this issue. Can you please provide me the UI so that I can develop it.
Hoping for quick response.
