### ISSUE TITLE
🚀 Feature: Text-to-Speech for Model Output

### ISSUE THREAD

**Issue by Vaishnavi-Raykar** [arc53/DocsGPT#1202]
### 🔖 Feature description

Add a feature that converts model-generated text into speech, allowing users to listen to the output.

### 🎤 Why is this feature needed ?

It enhances accessibility for visually impaired users and those who prefer listening. It also supports multitasking and broadens the app’s user base.

### ✌️ How do you aim to achieve this?

Use a TTS engine like Google Text-to-Speech or the Web Speech API. After the model generates text, users can click a button to hear it.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by eleensmathew** [comment]
Hi can i work on this?

**Comment by Vaishnavi-Raykar** [comment]
@dartpain 
This issue was actually created by me and I already mentioned that I want to make a pull request for it. 

So please assign it to me.

**Comment by dartpain** [comment]
Very sorry for this @Vaishnavi-Raykar 
Thank you for pointing it out.

**Comment by Vaishnavi-Raykar** [comment]
@dartpain 

Welcome...No problem👍

**Comment by Srayash** [comment]
Hi @tenokami @ManishMadan2882 
I want to confirm the icon and hover effect for the Speak button. Let me know what works best to match the style!

Thanks!

**Comment by tenokami** [comment]
Hi @Srayash 

I believe @Vaishnavi-Raykar is working on this, right? In any case here is the design

Prototype: https://www.figma.com/proto/OXLtrl1EAy885to6S69554/DocsGPT?node-id=4949-8126&t=Hue5mwMSnqxaYgvt-1

Wireframes https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=Hue5mwMSnqxaYgvt-1

For dark theme just use the right color for icon

**Comment by Vaishnavi-Raykar** [comment]
Yes ,@tenokami I'm working on this issue.

**Comment by Srayash** [comment]
Hi @Vaishnavi-Raykar! I’ve already completed the work on this issue. If it’s alright with you, would you mind if I go ahead and submit a PR for it?

**Comment by Vaishnavi-Raykar** [comment]
Hi @Srayash ! Thanks for working on this issue. Please go ahead and submit the PR. I’ll review it, and if I see any areas for improvement, I’ll let you know.👍

**Comment by Srayash** [comment]
https://github.com/user-attachments/assets/ef477ce8-2370-4c3a-94f5-754897457fd8

Browser: Brave.

**Comment by tenokami** [comment]
@Srayash Thanks! Btw why did you change the position of the button?

**Comment by tenokami** [comment]
@Srayash Maybe the play sound icon looks a bit too big?

**Comment by Srayash** [comment]
> @Srayash Maybe make play sound icon a bit smaller to be the same size as the other icons?

is this okay? @tenokami 

<img width="186" alt="Screenshot 2024-10-27 at 9 20 44 PM" src="https://github.com/user-attachments/assets/67b18394-846f-487f-8241-ee7af9fb7cbb">

**Comment by Srayash** [comment]
> @Srayash Maybe make play sound icon a bit smaller to be the same size as the other icons?

is this okay @tenokami ?

<img width="341" alt="Screenshot 2024-10-27 at 9 41 35 PM" src="https://github.com/user-attachments/assets/5e6b1a51-34bd-4f7d-a2f6-4950ae190bb9">

**Comment by tenokami** [comment]
@Srayash Looks great!
