### ISSUE TITLE
🚀 Feature: Updated UI/UX for "Upload new document" modal

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#1210]
### 🔖 Feature description

https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=N50TV6CgjXioM0rQ-1

![image](https://github.com/user-attachments/assets/5b02c3dd-e20b-4cea-a387-073662f7db7c)
![image](https://github.com/user-attachments/assets/45bac34f-bd0b-45ee-8549-d44fed668395)

### 🎤 Why is this feature needed ?

Better UI/UX

### ✌️ How do you aim to achieve this?

Better UI/UX

### 🔄️ Additional Information

It might be optimal to work on this issue after https://github.com/arc53/DocsGPT/issues/1201 is completed because they share some similarities that can be reused.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by RohittCodes** [comment]
Hey @tenokami, I would like to work on it.

**Comment by ovindu-a** [comment]
@tenokami hi, I would like to work on this UI/UX feature

**Comment by shelar1423** [comment]
@RohittCodes assigned it to you !

**Comment by tenokami** [comment]
@ovindu-a Thank you! Please make sure that training loader is consistent with #1201

**Comment by tenokami** [comment]
@RohittCodes I've added a dark theme if you could please add it too.


![image](https://github.com/user-attachments/assets/cc5a92bb-9b5b-4320-88e4-8dbd79d51e65)

**Comment by RohittCodes** [comment]
yeah sure!

**Comment by ovindu-a** [comment]
> @ovindu-a Thank you! Please make sure that training loader is consistent with #1201

@tenokami looks like @RohittCodes is working on it already right. Is there something else I could do?

**Comment by tenokami** [comment]
> > @ovindu-a Thank you! Please make sure that training loader is consistent with #1201
> 
> 
> 
> @tenokami looks like @RohittCodes is working on it already right. Is there something else I could do?
> 
> 

New issues will be added soon

**Comment by RohittCodes** [comment]
hey @tenokami! I'm almost done with the UI can you've a look into it. and there is some issue with the worker from my side while **training**, so the training percentage is stuck at 0% only. But I've updated the styles for it on 100% too. And, I've added a prop named isOnboarding to the `<Upload />` component, which will work with the issue #1201, and it will take some condition based styling there.

Can I submit the PR or is it necessary to try the training too. I've not played with any functions related to fetching (training/upload). So i guess it won't have issues?

https://github.com/user-attachments/assets/4d273309-98fe-4160-b279-3100df898921

**Comment by dartpain** [comment]
Yeah please submit the PR, we will test out some of the potential issues if they exist with upload itself.
Thank you!
