### ISSUE TITLE
🐛 Bug Report: Strange horizontal scroll bar behavior on mobile

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1218]
### 📜 Description

A useless horizontal scroll appears on mobile.
![image](https://github.com/user-attachments/assets/78384d11-cb7d-495b-a0e8-b6e60fdc7c22)

### 👟 Reproduction steps

Can be reproduced in developer tools:
![image](https://github.com/user-attachments/assets/77d8ede4-6f2a-4964-8413-0679506d1d19)

### 👍 Expected behavior

I don't think there should be a horizontal scroll for such a small distance. Or at least it shouldn't be of this size. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/78384d11-cb7d-495b-a0e8-b6e60fdc7c22)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pranavmugatkar** [comment]
Hello @pabik , I am interested in contributing to this issue.  Any guidance or specific requirements would be greatly appreciated. Thank you!
