### ISSUE TITLE
🐛 Bug Report: Make border style similar for elements

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1220]
### 📜 Description

Currently there is a mixture of border sizes and styles in the app. This is especially noticeable in the main window before chat and in the settings (documents and chatbots tables). We need to get borders of similar elements under one style.   

### 👟 Reproduction steps

Go to the main screen or settings/documents, settings/chatbots.

### 👍 Expected behavior

On the main screen borders of model selection and follow up questions should be same as for the text input field.
![image](https://github.com/user-attachments/assets/b6b368e3-9c6a-4176-9ad0-8168953d30f6)
Documents and chatbots tables should have same border as drop-downs or analytics components.
![image](https://github.com/user-attachments/assets/edd9a46f-e6cf-4cbe-9034-4c1e9deb5a21)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/24d8d18e-4466-48ba-bfd0-f11d8051f0f0)
![image](https://github.com/user-attachments/assets/dfba9d0a-5cd9-4686-98fa-e7d528017e01)

### 💻 Operating system

MacOS

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anasKhafaga** [comment]
I'm interested in working on this bug @pabik
