### ISSUE TITLE
🚀 Feature: Make logo clickable

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1221]
### 🔖 Feature description

I propose to make the DocsGPT logo clickable and to assign it same behaviour as the new chat button.
![image](https://github.com/user-attachments/assets/40e3ebf9-2bf9-4291-84fa-9c4ceac5097f)

### 🎤 Why is this feature needed ?

It is a common practice to make the logo click redirect to an index page. 

### ✌️ How do you aim to achieve this?

Add a link attribute to the logo component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by anasKhafaga** [comment]
I'm interested in working on this feature @pabik

**Comment by Abinanthan47** [comment]
I'd like to work on this , can you assign me

**Comment by QaisarMoin** [comment]
Please assign me this issue.
