### ISSUE TITLE
🐛 Bug Report: Very long continues string (long word) unexpected behaviour

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1222]
### 📜 Description

A message containing very long words breaks the max width. 

### 👟 Reproduction steps

Type a 60+ character string as a question.

### 👍 Expected behavior

There should be a mechanism for word hyphenation at extreme cases. We don't want to break down words too often as this reduces readability. Max width for question/answer bubbles for each device should not be broken.  

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/cedac4cd-aef5-45b5-84fe-2bf2acdbbf1d)
![image](https://github.com/user-attachments/assets/5cd57746-abd7-495f-9a43-0306baa31f96)

https://app.docsgpt.cloud/share/65a817e7-f6b7-4e36-821f-f1598805aafd

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utin-francis-peter** [comment]
Hi, @pabik.

Love to jump on this please.

**Comment by anasKhafaga** [comment]
I'm interested in working on this bug
