### ISSUE TITLE
🐛 Bug Report: Safari wrong fonts

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1223]
### 📜 Description

In desktop Safari wrong fonts are displayed.

### 👟 Reproduction steps

Open DocsGPT on desktop Safari. 

### 👍 Expected behavior

![image](https://github.com/user-attachments/assets/e8374083-76de-4e0e-b33f-9b27a53fde22)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/96a9ae7e-81e7-49b6-becc-105a1417b66c)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshitVashisht11** [comment]
Hi, can i solve this issue

**Comment by pabik** [comment]
Hi @HarshitVashisht11 , how are things going with the issue?

**Comment by staticGuru** [comment]
@pabik Could you please assign these tickets? I will start working on these issues.

**Comment by shatanikmahanty** [comment]
@staticGuru are you still working on this, I came across this issue today and know the solution to this. I can submit a PR for this in case you are stuck. Thanks!

**Comment by shatanikmahanty** [comment]
@dartpain thanks for assigning! Have created the PR.
