### ISSUE TITLE
🐛 Bug Report: sources component flash on Safari

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1224]
### 📜 Description

Sources component appears on Safari for a moment even when no source document is selected.

### 👟 Reproduction steps

Set source document as none or Chunks processed per query to 0. Then start the conversation, you will see blank sources appear for a sec. 

 

### 👍 Expected behavior

The sources component should not appear at all if None is selected in sources or Chunks processed per query set to 0.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/ad9178c1-7ab7-43ce-ab61-4afbaaf865ca)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AwadhootK** [comment]
@pabik please assign me this issue!

**Comment by pabik** [comment]
Hey @AwadhootK just wanted to check in on this issue to see how things are going

**Comment by staticGuru** [comment]
@pabik Could you please assign these tickets to me? I will begin working on them right away.
