### ISSUE TITLE
🚀 Feature: On mobile sidebar minimisation 

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1226]
### 🔖 Feature description

On mobile, side bar should minimise upon click (item selection, such as settings) or off click. 

### 🎤 Why is this feature needed ?

Better usability. 

### ✌️ How do you aim to achieve this?

Check if mobile dimensions and alter behaviour. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by shatanikmahanty** [comment]
@pabik May I work on this?

**Comment by shatanikmahanty** [comment]
<img width="186" alt="Screenshot 2024-10-04 at 9 34 47 PM" src="https://github.com/user-attachments/assets/f3867ebf-54e5-4813-99da-300e61dc2064">

@pabik should it close on clicking on the logo as well?

I have added it for the rest on mobile.

**Comment by dartpain** [comment]
On mobile - yes. Think its a good idea

**Comment by shatanikmahanty** [comment]
@dartpain have created a PR for this. Once you review, please let me know if it needs any improvements. Thanks!
