### ISSUE TITLE
🐛 Bug Report: No share button on mobile

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1227]
### 📜 Description

When on mobile resolution and sidebar icon turns into menu burger there is no share button.

### 👟 Reproduction steps

Set width to less then 678px. 

### 👍 Expected behavior

I propose to remove the mobile top menu with burger, as it covers the share button. Additionally this will keep UI more discreet. 
![image](https://github.com/user-attachments/assets/cfdc7b30-3abf-4eef-9fd0-cad4a6df055a)
However on mobile when sidebar is triggered, message boxes are not truncated - this should be left. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/4cae1154-fd6f-49cf-b86d-994aa05cbc44)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JeevaRamanathan** [comment]
I would like to work on this!

**Comment by JeevaRamanathan** [comment]
Hi @pabik, In the local development environment, I couldn’t find the Avatar/Manage Account screen or the related code. Any help with this would be appreciated, or if I'm missing anything.
![image](https://github.com/user-attachments/assets/c9560f1b-0222-4f65-885a-f3c1201bec1c)
![image](https://github.com/user-attachments/assets/016729ac-865d-4182-a8b0-9f01450e3ebc)

**Comment by dartpain** [comment]
Should be moved a little more to the left (on mobile), to allow for the profile icon.
Profile icon is not on the open source version

**Comment by JeevaRamanathan** [comment]
Got it, I will move it slightly to the left! 

_(However, on mobile, when the sidebar is triggered, the message boxes are not truncated – they should remain on the left.) Could you highlight their purpose?_

I would like to understand this point better. Could you clarify or point what is being referred to regarding the message boxes?

**Comment by SamsShow** [comment]
would like to work on it if the current assignees is in active
