### ISSUE TITLE
🚀 Feature:  Mobile settings menu

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1228]
### 🔖 Feature description

Currently the settings tabs on mobile look bad. 
![image](https://github.com/user-attachments/assets/5a10ec15-fa9c-4d5a-839c-1241d889448a)
Additionally on desktop there is an awkward left margin even on desktop. 
![image](https://github.com/user-attachments/assets/8412ccad-f194-4da6-a796-5cc974b4eeae)
I propose we take an inspiration from this and change the behaviour of the component.
![image](https://github.com/user-attachments/assets/68b4aca5-ae41-40d1-9197-84e86ff72d5a)

### 🎤 Why is this feature needed ?

Better UI + style points

### ✌️ How do you aim to achieve this?

Rework this component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by anasKhafaga** [comment]
I'm interested in handling this feature?

**Comment by naaa760** [comment]
Hello @pabik 
I want to work on this issue, please assign me.
