### ISSUE TITLE
🐛 Bug Report: Mobile retry button too large

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1230]
### 📜 Description

On mobile resolution retry button is too large + pushes the answer bubble to the left. 

### 👟 Reproduction steps

1. Don't connect backend to front end. 
2. Ask any question. 

### 👍 Expected behavior

Move retry to the bottom of the message + make it similar style to copy and feedback icons. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/f06b355a-ab9d-49cc-b988-0a8f6a009831)

### 💻 Operating system

Something else

### What browsers are you seeing the problem on?

Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayaan-qadri** [comment]
I would like to work on it !

**Comment by PROSENJIT-RONI** [comment]
May I work on this issue. I want to work on this

**Comment by ovindu-a** [comment]
@dartpain @pabik my apologies, I saw this was assigned to someone only after making the pull request. Please let me know if there's anything else I could do.

**Comment by ayaan-qadri** [comment]
@ovindu-a That's not fair. You should review the issue before starting to work on it. I was just troubleshooting the setup due to rendering issues. This behavior could waste someone's time and effort, so I hope you avoid making this mistake in the future.

**Comment by ovindu-a** [comment]
You're right @ayaan-qadri, I apologize for my mistake.

**Comment by dartpain** [comment]
@ayaan-qadri Current PR, does not fix the problem completely and does not aling. So please you can still try at it.

**Comment by ayaan-qadri** [comment]
@dartpain It would be better if you assign to @ovindu-a as he already did some work, it will ruin his PR & duplicate the PR if I raise PR.

**Comment by PROSENJIT-RONI** [comment]
@dartpain Can I work on this issue?

**Comment by ovindu-a** [comment]
@ayaan-qadri you can build on what I have done as you are assigned it already. Once again so sorry for the mix-up

**Comment by ayaan-qadri** [comment]
All good @ovindu-a, you can handle it, Our end goal is to improve the project :)

**Comment by pabik** [comment]
Hey @ovindu-a 
How is the issue going? Do you want any help?

**Comment by ovindu-a** [comment]
@pabik I made the changed and my pull request was merged. Is there anything else for me to do?
