### ISSUE TITLE
🚀 Feature: Modals under one style

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1231]
### 🔖 Feature description

Currently in an app all modals look different. I think it will benefit the UI to have them under one style.
Create new modal in settings/chatbots looks clean and I think should be the base case.
![image](https://github.com/user-attachments/assets/945c85e2-9c2d-4c31-af12-824e1f320dae)
However I think an off modal click/tap should close modal. 

Here for example what would need to be changed in upload modal.
![image](https://github.com/user-attachments/assets/08fff4c7-ef73-47af-880c-55a53cebf6de)
1. Add x at the top right corner to close. 
2. Remove 'Cancel'
3. Make 'Train' button inactive by default, similarly to the one in new chatbot modal.
![image](https://github.com/user-attachments/assets/984442fd-e975-46a3-8ed5-cb6b1c29d09f)
![image](https://github.com/user-attachments/assets/4bcc4916-8773-4fc0-9385-5694f5dde9ef)
4. Allow for a click outside modal to close it. 

### 🎤 Why is this feature needed ?

Benefit UI. 

### ✌️ How do you aim to achieve this?

1. Add click outside modal to close it functionality.
2. Check other modals to have same structure.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by JeevaRamanathan** [comment]
I noticed that another issue,  [Updated UI/UX for "Upload new document" modal](https://github.com/arc53/DocsGPT/issues/1210)  is already in place. Could having multiple issues focused on updating the upload modal lead to some overlap?

**Comment by dartpain** [comment]
Think this one is more about the color of the buttons for consistency.
Other issue is a larger change and we dont expect it to be delivered quickly as this one can.
I do appreciate your careful sift through other issues

**Comment by Kritika30032002** [comment]
assign this issue to me, interested to contribute @pabik @dartpain

**Comment by uttam282005** [comment]
@dartpain  can you assign me this issue. I have explored the codebase and files related to this issue and I think I can work on this.

**Comment by Kritika30032002** [comment]
working on it

**Comment by prathamesh424** [comment]
@ManishMadan2882  can you assign this issue to  me

**Comment by AkashJana18** [comment]
Hey  @dartpain @ManishMadan2882 If this issue still persist I would like to work on it. Please assign it to me. Thank you.

**Comment by RohittCodes** [comment]
i guess the new upload modal has a few things in place already.

- Allow for a click outside modal to close it.
- Make 'Train' button inactive by default, similarly to the one in new chatbot modal.
are the only 2 things to be done. do you want anything else to be included? @ManishMadan2882

**Comment by RohittCodes** [comment]
oh sorry, if i understand it correct. the idea is to create a base modal for all the modals??
