### ISSUE TITLE
🐛 !Bug Report: Issue#1222 Seems to be Working Fine

### ISSUE THREAD

**Issue by utin-francis-peter** [arc53/DocsGPT#1244]
### 📜 Description

In an attempt to recreate the highlighted bug in issue#1222 (https://github.com/arc53/DocsGPT/issues/1222), I soon realized the bug had already been fixed earlier by @ManishMadan2882. 

### 👟 Reproduction steps

Please follow the provided reproduction steps in issue#1222 (https://github.com/arc53/DocsGPT/issues/1222)

### 👍 Expected behavior

The highlighted behavior in issue#1222

### 👎 Actual Behavior with Screenshots

Please have a look at the video review: https://drive.google.com/file/d/1kWsnrlGWnIHathFUjMEJaxEPOuDEuoQI/view?usp=sharing 

### 💻 Operating system

Linux

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pabik** [comment]
Hi @utin-francis-peter,
Just tested on the docker deployment main (Chrome, MacOS). 
![image](https://github.com/user-attachments/assets/71555c0f-ee65-413f-8f71-1343e6c98b94)
Try typing this as the input:
`AaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaaAaaaaaaaaaaaaaaaaaa
`

**Comment by ManishMadan2882** [comment]
Hi @utin-francis-peter 
I submitted the fix for long sentences basically tested it for code snippets in the input, but I think it fails for long words as mentions in #1222
Thanks!
