### ISSUE TITLE
🚀 Feature: Redesign the screen for unauthorized users

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#1255]
### 🔖 Feature description

Unauthorized screen section design is here https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=LIx2jRUn39Pt06cs-1

![image](https://github.com/user-attachments/assets/679d0668-65cd-463c-bc65-4260dfe16270)

This is what every unauthorzed user sees, whether they opened DocsGPT for the first time or they signed out of their account. The form is a modified version of what is currently on prod.

### 🎤 Why is this feature needed ?

Better UI/UX

### ✌️ How do you aim to achieve this?

Better UI/UX

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by amitroy-thedev** [comment]
Hey @tenokami 
I would like to work on this issue but how to implement dark mode? Do I need to add a button to toggle between dark and light mode

**Comment by amitroy-thedev** [comment]
Hey @tenokami i can build in light mode for now

**Comment by amitroy-thedev** [comment]
Hey @tenokami i can build in light mode for now

**Comment by tenokami** [comment]
@amitroy-thedev sorry this issue was opened by mistake and is now closed

**Comment by amitroy-thedev** [comment]
@tenokami any other issue that i can work upon which is related to frontend?

**Comment by tenokami** [comment]
> @tenokami any other issue that i can work upon which is related to frontend?

New issues will be added soon

**Comment by amitroy-thedev** [comment]
@tenokami Okay
