### ISSUE TITLE
🐛 Bug Report: pop up box is not well positioned

### ISSUE THREAD

**Issue by ayaan-qadri** [arc53/DocsGPT#1256]
### 📜 Description

The pop-up box is poorly positioned, resulting in misalignment and potential clipping of options. This affects visibility and user experience when interacting with the interface.

### 👟 Reproduction steps

Go to > https://app.docsgpt.cloud/ > Chats > scroll to the bottom > click on three dots of tile

### 👍 Expected behavior

The pop-up box should be correctly positioned, ensuring all options are fully visible and easily accessible without clipping especially it should be positioned beside three dots.

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/0b810394-1c62-45b0-9dfd-828a6aa1464f

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayaan-qadri** [comment]
I'm already working on it.

**Comment by PROSENJIT-RONI** [comment]
@ayaan-qadri May I work on this?

**Comment by ayaan-qadri** [comment]
> @ayaan-qadri May I work on this?

Sure, lemme know if you are done with this, I'm also exploring this issue. Make sure you ask @dartpain first.

**Comment by PROSENJIT-RONI** [comment]
@dartpain May I work with this issue?

**Comment by PROSENJIT-RONI** [comment]
@ManishMadan2882 Please let me know if any changes are required in the PR. Thanks
