### ISSUE TITLE
🚀 Feature: Edit Previous Request and Resend in DocsGPT

### ISSUE THREAD

**Issue by Mefisto04** [arc53/DocsGPT#1260]
### 🔖 Feature description

I propose adding a functionality in DocsGPT where users can edit their previously sent requests and resend them to the AI to receive a new response. This feature will enhance the user experience by allowing them to refine their queries and get better, more targeted answers without having to start from scratch.

You should add an "Edit Request" button next to each previous request, allowing users to modify the text and resubmit the query to DocsGPT.

### 🎤 Why is this feature needed ?

In many cases, users may not get the exact response they are looking for on the first attempt. Rather than retyping or copying the whole request and submitting it again, allowing users to edit their last submission would save time and effort, improving both efficiency and interaction.

In my use case, this feature would allow me to correct mistakes, refine queries, or simply modify a question to get a more precise answer without retyping everything.

### ✌️ How do you aim to achieve this?

I want this feature to be implemented by adding an "Edit" option near the previous request in the chat interface. When clicked, it should populate the input field with the previous query, allowing users to modify it and resubmit. Upon sending, the updated query would replace the original request and trigger a new response from the AI based on the new input.

### 🔄️ Additional Information

A clear solution that I considered is adding an "Edit" button alongside the "Resend" option that allows users to directly modify their previous query. The alternative is to copy and paste manually, but that adds friction to the user flow and isn't as intuitive.

I tried manually copying and resubmitting, but it is tedious and error-prone, especially when the original request is lengthy.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tenokami** [comment]
![image](https://github.com/user-attachments/assets/abe27a45-559e-4517-bfda-4bc7f4bc7884)

![image](https://github.com/user-attachments/assets/495f115e-904e-465c-bc0c-b11f5987a568)

https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=IV7S4Y3cuEgsVe2j-1

**Comment by tenokami** [comment]
![image](https://github.com/user-attachments/assets/c75dfd9d-70d8-4734-84fa-2f77e28f37ce)

@Mefisto04

**Comment by tenokami** [comment]
![image](https://github.com/user-attachments/assets/ee84b07c-1863-4f07-9903-b25ce7e9fe72)

@Mefisto04

**Comment by Niharika0104** [comment]
Can you assign this issue to me?

**Comment by AkashJana18** [comment]
@Niharika0104  @Mefisto04 are you guys working it ?
May I assist .. I would love to work on this issue

**Comment by Niharika0104** [comment]
@AkashJana18 you can do the backend  part of this and I will do the frontend part of this.
What say ?

**Comment by AkashJana18** [comment]
@Niharika0104 it is supposed to be a frontend issue as doesn't has any backend tag

**Comment by Niharika0104** [comment]
@AkashJana18 I think we need to have one backend method which will update that particular query
We need to check if we have any such endpoint

**Comment by RohittCodes** [comment]
@ManishMadan2882 can u assign this to me?
