### ISSUE TITLE
🚀 Feature: Update for the sidebar

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#1261]
### 🔖 Feature description

Remove icons next to chat and shorten Source docs to Source

![image](https://github.com/user-attachments/assets/9b38693d-c5fb-4087-91dc-5bb817966184)

### 🎤 Why is this feature needed ?

Better UI/UX

### ✌️ How do you aim to achieve this?

Better UI/UX

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by utin-francis-peter** [comment]
Pls assign.
