### ISSUE TITLE
🚀 Feature: Prevent flash on dark theme

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#1262]
### 🔖 Feature description

Implement a theme switcher that automatically detects the user's system color scheme preference and applies the appropriate theme (light or dark).  Script should run on page load. If no preference is found, default to light theme. The user's manual selection should be stored in localStorage for future visits.

### 🎤 Why is this feature needed ?

This feature enhances the user experience.

### ✌️ How do you aim to achieve this?

Modify the existing script to handle theme switching based on the prefers-color-scheme media query.
Use localStorage to store the user's selected theme (light or dark) if they manually choose a different theme.
Ensure that the script runs on page load to apply the appropriate theme.

### 🔄️ Additional Information

We need to implement something similar, to eliminate light flash on page reload.
```javascript
(function () {
    try {
        var d = document.documentElement,
            c = d.classList;
        c.remove('light', 'dark');
        var e = localStorage.getItem('theme');
        if ('system' === e || (!e && true)) {
            var t = '(prefers-color-scheme: dark)',
                m = window.matchMedia(t);
            if (m.media !== t || m.matches) {
                d.style.colorScheme = 'dark';
                c.add('dark');
            } else {
                d.style.colorScheme = 'light';
                c.add('light');
            }
        } else if (e) {
            c.add(e || '');
        }
        if (e === 'light' || e === 'dark') d.style.colorScheme = e;
    } catch (e) {}
})();
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by mousumi2002** [comment]
@pabik  I want to work on this

**Comment by wizaye** [comment]
@pabik I want to work on this issue, could you assign this to me?

**Comment by mousumi2002** [comment]
@ManishMadan2882 have submitted a PR for this that checks if the component is mounted and then loads the page to prevent flicker. Apart from that the suggested improvements like storing theme in local storage was already there. Please let me know once you review if any changes are necessary. Thanks!
