### ISSUE TITLE
Mobile responsiveness issue

### ISSUE THREAD

**Issue by shelar1423** [arc53/DocsGPT#1276]
When tested with ios device browsers due to the placement of bottom bar and top bar of the browsers there is an issue occurring in the responsiveness as show in the video below

![image](https://github.com/user-attachments/assets/420f512a-7354-4ad5-a634-0380c2d17e3d)

https://github.com/user-attachments/assets/ef8f27fb-d5ca-4be0-aa0b-d749ac9ff130

**Comment by RS-labhub** [comment]
Will look into it! Assign me this

**Comment by RohittCodes** [comment]
@shelar1423 I would like to work on it. can u assign it to me?

**Comment by shelar1423** [comment]
@RohittCodes assigned it to you!

**Comment by RohittCodes** [comment]
@shelar1423, the issue appears to be browser-specific (affecting only Safari). It can be optimized according to the documentation, but I currently don't have access to an iOS device to test further.

However, we could add some extra padding or height as a temporary workaround.
