### ISSUE TITLE
🐛 Bug Report: Font color too dark on About page

### ISSUE THREAD

**Issue by adarsh-jha-dev** [arc53/DocsGPT#1284]
### 📜 Description

In the About page- 
Observe the "Currently it uses..."  part, the font is not visible because of the color combination

### 👟 Reproduction steps

Update the font color similar to the other blue-fonts in the page.

### 👍 Expected behavior

The font should be visible aligning with the background.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/51bab98b-d886-4cad-83fe-6dbb5d104af7)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Appreciate it, but we are depriciating about page very soon.
Thank you!
