### ISSUE TITLE
🚀 Feature: Table redesign

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#1286]
### 🔖 Feature description

https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=Sav41zuHC2ts3pxh-1

![image](https://github.com/user-attachments/assets/37ef5fbd-c0bf-4bbf-89ce-628c5af36325)
![image](https://github.com/user-attachments/assets/2e3327ab-87ce-48f2-9441-007fa1aa1d4a)
![image](https://github.com/user-attachments/assets/23ac922d-4811-4c70-bc68-b851fb214f32)
![image](https://github.com/user-attachments/assets/f3d514a4-7a02-4240-aed1-31f1c01777f5)

![image](https://github.com/user-attachments/assets/30afa81f-6166-4d8f-86da-8542054684e1)

### 🎤 Why is this feature needed ?

Better UI/UX and functionality

### ✌️ How do you aim to achieve this?

Better UI/UX and functionality

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by AkashJana18** [comment]
i would love to work on this issue please assign me

**Comment by utin-francis-peter** [comment]
Hello, @AkashJana18.

Please how's it going with the issue?

**Comment by AkashJana18** [comment]
> Hello, @AkashJana18.
> 
> Please how's it going with the issue? 

Working on it
