### ISSUE TITLE
🚀 Feature: Slack extension

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1290]
### 🔖 Feature description

Slack extension for docsgpt, should connect with docsgpt chatbot api

### 🎤 Why is this feature needed ?

To integrate docsgpt with slack

### ✌️ How do you aim to achieve this?

Here is an example of a good extension:
https://github.com/arc53/DocsGPT/tree/main/extensions/react-widget
Also this:
https://github.com/arc53/tg-bot-docsgpt-extenstion

Should include history management ideally and display sources too (in very minimised way)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by sayanm16** [comment]
I want to work on this

**Comment by sayanm16** [comment]
@dartpain you may assign @mousumi2002 as I am facing some issues and won’t be able to continue.

**Comment by sayanm16** [comment]
@dartpain you may assign @mousumi2002 as I am facing some issues and won’t be able to continue.

**Comment by mousumi2002** [comment]
@ManishMadan2882 As per the DocsGPT API, we need a 12-byte input or a 24-character hex string for conversation_id. As Slack uses 11-digit channel_id for a conversation if I use hashing to convert it to 12 bytes will that work?
