### ISSUE TITLE
🚀 Feature: New button and logo in header when the sidebar is closed

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#1292]
### 🔖 Feature description

The "+" icon will open a new chat on click. (Only if the current chat has any messages)

https://www.figma.com/design/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0-1&t=UbTE0eKgODqCaJ8p-1

![image](https://github.com/user-attachments/assets/33465bf4-0358-48c6-a8fb-f9709c92d552)

![image](https://github.com/user-attachments/assets/77c8e58f-8685-496c-89b8-e9a656a96809)

![image](https://github.com/user-attachments/assets/47ef1f53-32b9-4c10-a4b7-3096fdd5b5ad)

![image](https://github.com/user-attachments/assets/af0b140e-6f13-4e27-a6f6-927fcc489656)

### 🎤 Why is this feature needed ?

Better UI/UX

### ✌️ How do you aim to achieve this?

Better UI/UX

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by RohittCodes** [comment]
Hey @tenokami, i would like to work on it?

**Comment by tenokami** [comment]
@RohittCodes Thanks, assigned to you.

**Comment by Niharika0104** [comment]
Can you assign that issue to me?

**Comment by RohittCodes** [comment]
@Niharika0104 you can work on it. I would stick with other issues.

@tenokami sorry, but can you assign it to her?

**Comment by tenokami** [comment]
@Niharika0104 Thanks, assigned to you.
