### ISSUE TITLE
🐛 Bug Report: Disable scrolling and Close popup box clicking on three dots

### ISSUE THREAD

**Issue by ayaan-qadri** [arc53/DocsGPT#1294]
### 📜 Description

Scrolling should be disabled when Popup is opened and when Popup is opened it should be closed by click on three dots.

### 👟 Reproduction steps

1. Open chats > click on three dost > scroll (see issue in attached screen recording)
2. Click on three dots again (on opened popup) > click on three dots (it will not close popup)

### 👍 Expected behavior

Scrolling should be disabled and popup should close when again click on three dots.

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/a92041e4-2ff6-4645-9a1c-11e54ef8df61

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayaan-qadri** [comment]
Let me know whether I should create a PR.

**Comment by ManishMadan2882** [comment]
Thanks @ayaan-qadri, assigning to you.
