### ISSUE TITLE
🚀 Feature: Enhance About Page UI

### ISSUE THREAD

**Issue by Ayushjhawar8** [arc53/DocsGPT#1301]
### 🔖 Feature description

The current About page is not properly designed, and the visibility of the word "DocsGPT" is insufficient, making it difficult for users to grasp the key features and usage of the application. This feature aims to redesign the About page for improved visibility and a more modern, user-friendly look.

### 🎤 Why is this feature needed ?

The About page is often the first point of contact for users to learn about DocsGPT. An improved UI will help convey important information more effectively and encourage users to explore the application further. In my use case, a more visually appealing design will enhance the user experience and retention.

### I plan to achieve this by:

- Implementing a cleaner layout with appropriate spacing.
- Using modern typography for better readability.
- Incorporating consistent color schemes that align with the overall theme of the application.
- Ensuring the design is responsive and user-friendly across devices.

### 🔄️ Additional Information

Old About Page Screenshot:
<img width="959" alt="before" src="https://github.com/user-attachments/assets/71473ef7-f936-49e4-977a-5dca1cb2d1b5">

New About Page Screenshot:
<img width="948" alt="after" src="https://github.com/user-attachments/assets/cd8c2410-89c8-4686-a571-70168dc3aab2">

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ManishMadan2882** [comment]
Hi @Ayushjhawar8 
There is already an [update](https://github.com/arc53/DocsGPT/pull/1213) in the queue, which will replace the about section.
Thanks.
