### ISSUE TITLE
Frontend feedback

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#131]
- [x] 1. If you close the side bar, there is no button to reopen it. Standard sidebar component in MUI provides this functionality.
- [x] 2. The cursor in the chat input field is not vertically centered. And make the left padding be visually equal to the top padding
![padd](https://user-images.githubusercontent.com/17906039/221411224-21b3c645-b059-4b9d-921c-d21967810879.png)

- [x] 3. The description text on main screen should have line-height: 25px;
- [x] 4. On large screens the word "answers" should be in the second line and not wrap (check design)
- [x] 5. at 514px width breakpoint, the text under the input field gets too close to the input. A fixed distance should be maintained also the width of the input is smaller than the text and is slightly pushed to the left but should be centered
- [x] 6. Would look better if the T-rex after GPT letters was the size of the letters and not pushed below them like currently
- [x] 7. ideally, the red distance should never be larger than the blue distance. (screenshot attached) It's good on larger screen but breaks on smaller screens
![image](https://user-images.githubusercontent.com/15183589/221359268-401971b7-1898-4ccc-9fe8-a47978ed171b.png)

- [x] 8. On touchscreen devices, clicking outside of sidebar should close it
- [x] 9. I've redesigned chat messages. Please pay close attention to paddings. Top, down, left, right paddings around text in message boxes. Also the fact that the long DocsGPT message never fully goes to the right edge but stops right before it. All updates are in figma 

![617ea8c8-821c-4d75-b456-9021e59135](https://user-images.githubusercontent.com/17906039/221361034-f9003486-c01b-4949-8be1-3e72cf4dbf0b.jpeg)

- [x] 10. Add hover effect to the send message button
![3f903195-16da-4614-ae70-016278592b6e](https://user-images.githubusercontent.com/17906039/221361105-d08a1e69-5880-4990-b0be-7a611b172e47.png)

**Comment by dartpain** [comment]
Done in #144
