### ISSUE TITLE
🐛 Bug Report: Website reloads on clicking the logo

### ISSUE THREAD

**Issue by Mayurakshi-mondal** [arc53/DocsGPT#1311]
### 📜 Description

Clicking on logo restarts the website as we are using an <a> tag to go to route `/`

Instead of this we can call the reset conversation method we have to start a new chat, which would make it more effecient

### 👟 Reproduction steps

Click on DocsGPT logo in drawer

### 👍 Expected behavior

It should start a new chat without the website refreshing

### 👎 Actual Behavior with Screenshots

Reload is encountered

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

Yes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManishMadan2882** [comment]
Hi
It's not a bug, was reasonably added, Thanks!
