### ISSUE TITLE
🐛 Bug Report: Retriever name always passed as classic

### ISSUE THREAD

**Issue by Mayurakshi-mondal** [arc53/DocsGPT#1313]
### 📜 Description

Retriever is always passed as classic from the frontend.

### 👟 Reproduction steps

Select DuckDuckGo from the frontend as source. Retriever won't be passed to backend and it will pick up the configured default which is 'classic'

### 👍 Expected behavior

It should pickup the correct retriever

### 👎 Actual Behavior with Screenshots

Always classic is picked

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

Yes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mayurakshi-mondal** [comment]
@ManishMadan2882 I would like to work on a fix for this in case it is the intended behavior!

**Comment by Mayurakshi-mondal** [comment]
@dartpain have added the fix for this issue. I found that with the dependency that we use for duck duck go which is `duckduckgo-search==6.2.6` the website fails to do a search when chunk size is set to more than 0. On upgrading it to latest dependency it is able to do a search with higher chunks. 

If it's intended to allow higher chunks for Duck Duck Go, I can create a PR upgrading the related dependencies!

**Comment by dartpain** [comment]
Alright, yeah please open a separate PR for it too!
Thank you!
