### ISSUE TITLE
🐛 Bug Report: Errors occur when creating an account with GitHub or Google 

### ISSUE THREAD

**Issue by CBID2** [arc53/DocsGPT#1315]
### 📜 Description

I tried creating a DocsGPT account and receive this error 

![IMG_0438](https://github.com/user-attachments/assets/924682d5-c0dd-4b0c-93f6-b3feddacee48)

### 👟 Reproduction steps

1. Go to the website 
2. Click on the icons 
3. Receive error message 

### 👍 Expected behavior

The account is created 

### 👎 Actual Behavior with Screenshots

![IMG_0438](https://github.com/user-attachments/assets/fb34dd56-368f-4240-bff1-d217e24d60cb)

### 💻 Operating system

Something else

### What browsers are you seeing the problem on?

Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CBID2** [comment]
If approved, I would like to count this towards Hacktoberfest

**Comment by ManishMadan2882** [comment]
Hi @CBID2 
This error generally occurs when you try to Create a new account, when already registered.
Try Signing in instead, please share if you still face this issue.
Thanks!

**Comment by CBID2** [comment]
> Hi @CBID2 This error generally occurs when you try to Create a new account, when already registered. Try Signing in instead, please share if you still face this issue. Thanks!

It worked! :)
