### ISSUE TITLE
🚀 Feature:  Conditionally Display "Help" Text on Hover

### ISSUE THREAD

**Issue by Ayushjhawar8** [arc53/DocsGPT#1318]
### 🔖 Feature description

A clear and concise description of what the feature is.

- You should add hover functionality to the Help button so that the "Help" text only appears when a user hovers over the icon, keeping the interface cleaner and less cluttered by default.

### 🎤 Why is this feature needed ?

In my use-case, having the "Help" text always visible next to the icon creates unnecessary clutter. By only showing the text on hover, the interface becomes more minimal and user-friendly. This makes the UI more intuitive while saving space for other elements.

### ✌️ How do you aim to achieve this?

I want this feature to conditionally render the "Help" text only on hover, keeping the icon always visible but hiding the text until hovered. This will be implemented using a simple hover state in React.

### 🔄️ Additional Information

I tried always showing the text but found it too cluttered. Another option could be to use a tooltip, but in this case, showing the text next to the icon on hover is more consistent with the UI style.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Ayushjhawar8** [comment]
Before:
![image](https://github.com/user-attachments/assets/85507d8f-6b21-4e27-a35e-8be5f2ef344d)

After:
![image](https://github.com/user-attachments/assets/cb5240a1-fe8c-46cd-b060-45666a6546fb)
After someone hover then only the help text is visible

**Comment by i-sanjay-cs** [comment]
Assign me @Ayushjhawar8 !!

**Comment by Ayushjhawar8** [comment]
> Assign me @Ayushjhawar8 !!

I'm not a maintainer, so I can't assign anyone. Moreover, I raised this issue because I would like to fix it myself. Could you please  find another issue to work on?

**Comment by dartpain** [comment]
Thank you, so much for this issue, im just not sure this fits our design spec, I would suggest you talk to Nick in our discord if there are any ideas. Im just not sure what the empty space should be used for instead
