### ISSUE TITLE
[a11y]: Button's color contrast is low 

### ISSUE THREAD

**Issue by CBID2** [arc53/DocsGPT#1327]
## Description
I did an accessibility test on the website, and the results reveal that the sign-in button has a low color contrast of 4.43. This can cause users with low-vision to see it(see screenshot below for more context).

## Screenshot
![screenshot of the sign-in section of the website](https://github.com/user-attachments/assets/e889c5b8-32b7-4bc5-9a23-b5e04ac3b212)

## Solution
Changing the button's foreground color to make it meet the WCAG's standards and make it more accessible. 

## Additional Information
I would like to count this towards Hacktoberfest

**Comment by i-sanjay-cs** [comment]
Assign me !!

**Comment by CBID2** [comment]
> Assign me !!

Hi @i-sanjay-cs! 😊 I requested to work on this for Hacktoberfest

**Comment by ManishMadan2882** [comment]
@CBID2 Sorry, but this page of our application is not available on this repo.

**Comment by CBID2** [comment]
> @CBID2 Sorry, but this page of our application is not available on this repo.

Oh where is it then @ManishMadan2882? 😊

**Comment by dartpain** [comment]
Hey @CBID2 Nice to see you here again!
Unfortunately this issue is related to our cloud version, ill write it down, its very important.
If you find anything else - please dont hesitate to create another issue.

Thank you,
Alex

**Comment by CBID2** [comment]
> Hey @CBID2 Nice to see you here again!
> 
> Unfortunately this issue is related to our cloud version, ill write it down, its very important.
> 
> If you find anything else - please dont hesitate to create another issue.
> 
> 
> 
> Thank you,
> 
> Alex

Great @dartpain! 😊 Where's the repo for the cloud? I can post it there! 😊

**Comment by dartpain** [comment]
Cloud repo is not open source, as it has a very specific setup + some billing settings.
