### ISSUE TITLE
[FEATURE]: add “Edit on GitHub” buttons 

### ISSUE THREAD

**Issue by CBID2** [arc53/DocsGPT#1331]
### 🔖 Feature description

This feature is an Edit on GitHub button that appears at the bottom of a page on DocsGPT’s Doc site.

### 🎤 Why is this feature needed ?

In my experience with docs pages, having an edit button will make it easier for contributors to find the page that they need to refer to when making an update to a guide or what part of the documentation site.

### ✌️ How do you aim to achieve this?

I plan on asking @dartpain what has been used to build DocsGPT’s documentation site. From there, I will go to the tool’s website and find its tutorial on how to add edit buttons.

### 🔄️ Additional Information

I would for this to count towards Hacktoberfest 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
we used [nextra](https://nextra.site/) to build our documentation.
It should be located in the /docs directory of this project.

Thank you!
