### ISSUE TITLE
I want to make changes in API key and made the .env file.

### ISSUE THREAD

**Issue by jatin9823** [arc53/DocsGPT#1336]
### 🔖 Feature description

Make the .env file

### 🎤 Why is this feature needed ?

To secure the API key

### ✌️ How do you aim to achieve this?

I made a env file to make the API secured 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ManishMadan2882** [comment]
Hi @jatin9823 
Could you please elaborate on this issue ?

**Comment by jatin9823** [comment]
Hi @ManishMadan2882,

Sure, I can elaborate on this.

The purpose of the .env file is to store environment variables, such as API keys, in a secure way rather than hardcoding them in the codebase. This file ensures sensitive information remains confidential, especially when sharing or deploying the project.

Why it's needed:

Security: API keys and other sensitive credentials should not be exposed in the code. By using a .env file, these credentials are stored securely and are not shared publicly.
Ease of management: If the API key changes, you can simply update the .env file without modifying the source code.
How to achieve this:

I've created a .env file that stores the API key and other sensitive data. The application will read from this file at runtime using libraries like dotenv (for Node.js projects).
In .gitignore, I added .env to ensure this file is not tracked in version control.
Let me know if you need further clarification!
