### ISSUE TITLE
🐛 Bug Report: Internal server Error while calling answer API

### ISSUE THREAD

**Issue by mousumi2002** [arc53/DocsGPT#1340]
### 📜 Description

On calling the /answer API I get Internal server error. I am using the prod url: https://gptcloud.arc53.com/api/answer

Here is the JSON body I am passing:

```json
{
  "question": "Help me to setup VSCode",
  "history": [],
  "conversation_id": null,
  "prompt_id": "default",
  "chunks": 2,
  "token_limit": 0,
  "api_key": "hidden",
  "isNoneDoc": true
}
```

Here is the response:

```json
{
    "error": "Internal Server Error",
    "message": "PlanExecutor error during aggregation :: caused by :: \"filter.source_id.$eq\" must be a boolean, objectId, number, string, date, uuid, or null, full error: {'ok': 0.0, 'errmsg': 'PlanExecutor error during aggregation :: caused by :: \"filter.source_id.$eq\" must be a boolean, objectId, number, string, date, uuid, or null', 'code': 8, 'codeName': 'UnknownError', '$clusterTime': {'clusterTime': Timestamp(1729252751, 1), 'signature': {'hash': b\"i\\xa2w\\x95\\x11=\\x82\\x12.C'\\xa3q{\\xa49je\\xeb8\", 'keyId': 7384906587107753985}}, 'operationTime': Timestamp(1729252751, 1)}"
}
```

### 👟 Reproduction steps

Hit the answer API using Postman or any other client

### 👍 Expected behavior

It should generate answer

### 👎 Actual Behavior with Screenshots

Internal Server Error

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Something else

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mousumi2002** [comment]
@dartpain Could you help me if I am missing out on anything here that will help me call the API properly?

**Comment by ManishMadan2882** [comment]
Works on my postman, by the way I generated on api_key to substitute in the request body from https://app.docsgpt.cloud/settings > Chatbots

**Comment by mousumi2002** [comment]
@ManishMadan2882 had done the same myself, hid the api key here so that it doesn't get exposed. Will try generating another one and check.

**Comment by mousumi2002** [comment]
@ManishMadan2882 still not working for me. Can I share a test api key from my side with you somewhere so you may take a look

**Comment by ManishMadan2882** [comment]
Hi, you can share on [discord](https://discordapp.com/users/784396060063170580).

**Comment by CLY009** [comment]
Excuse me, how was this problem solved? I want to know what the cause of the problem is.

**Comment by ManishMadan2882** [comment]
@CLY009 `history` should be passed as string(`"[]"`) in the case we discussed in this issue
The error response should be like `
the JSON object must be str, bytes or bytearray, not list
`

The backend accepts the request body attribute as:
```
"history": fields.List(
                fields.String,
                required=False,
                description="Conversation history (only for new conversations)",
            )
```
