### ISSUE TITLE
Feature: Backstage widget plugin

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1341]
Create a backstage plugin that will utilise our existing react widget.
Check out examples here:
https://backstage.io/plugins/

Import our react extension that is here:
[react web extension](https://github.com/arc53/DocsGPT/tree/main/extensions/react-widget)

https://www.npmjs.com/package/docsgpt

This issue will need its own PR, but is a subtask of #1293

**Comment by ayaan-qadri** [comment]
I would like work on it !

**Comment by ayaan-qadri** [comment]
I would like to work on it !

**Comment by ayaan-qadri** [comment]
(WORKING)

**Comment by naaa760** [comment]
Hello @dartpain  :)
I want to contribute to this issue. Please assign this issue to me.
Thank you!

**Comment by ayaan-qadri** [comment]
Update ::: making changes in react-widget for this issue.

**Comment by ayaan-qadri** [comment]
Update ::: Custom sizing for <DocsGPTWidget /> in progress

**Comment by ayaan-qadri** [comment]
This issue is resolved.
