### ISSUE TITLE
Update DOCS: Add Screenshots to existing Chrome Extension Documentation

### ISSUE THREAD

**Issue by abhirajadhikary06** [arc53/DocsGPT#1344]
**Description:**
I would like to update the documentation by adding screenshots to the Chrome extension section of DocsGPT. This will help improve clarity and provide visual guidance to users on how to use the extension more effectively.

**Task Details:**
Add screenshots demonstrating key steps and features of the Chrome extension.
Ensure the images are appropriately sized and aligned with the existing documentation style.
Update any necessary descriptions to complement the screenshots.
Please assign this task to me, @dartpain.

**Comment by dartpain** [comment]
We are planning a heavy redesign on that chrome extension.
Thank you for raising this issue.
I think there are other places that may benefit from screenshots.
