### ISSUE TITLE
🐛 Bug Report: Last saved Prompt remains on "Add Prompt"

### ISSUE THREAD

**Issue by lakshmi930** [arc53/DocsGPT#1351]
### 📜 Description

1. Clicking on "Add Prompt" button on Settings page, retains the last created Prompt on the session and have to be manually cleared. Either we can fix that the modal is fresh everytime or we can have the input fields to have some clear button.

2. We can create prompts with same names, even as those of default ones and we can't edit the default ones (even though edit button is accessible but save is not). Not sure if this is intended.

3. Another bug that could be fixed with the same modal is that we can save a prompt without any details (title, prompt etc.). This might be misused I'm not sure, but definitely looks bad as the name on dropdown is undefined.

### 👟 Reproduction steps

1. Go to Settings page
2. Click on the "Add New" button below the Active Prompt section
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/ddc9ad72-f762-4d39-9d08-c5ed0e1fc74c">

3. Fill the Prompt section
4. Click "Save"
5. Click the "Add New" button again
6. The Prompt modal opens again

### 👍 Expected behavior

Expected an empty modal to open

### 👎 Actual Behavior with Screenshots

It actually opened with the last custom prompt that the user created or edited in the session. 

https://github.com/user-attachments/assets/0d0ad9f9-3531-4d22-8557-77e9af332463

Screenshot for Prompt saved without title/details in the dropdown:
<img width="392" alt="image" src="https://github.com/user-attachments/assets/54b7e39d-df60-47f5-8a35-e235c278405b">

### 💻 Operating system

MacOS

### 🤖 What development environment are you experiencing this bug on?

Docker

### 📃 Provide any additional context for the Bug.

I am checking this on production.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mas-who** [comment]
Hi! I have created PR #1435  addressing the bugs mentioned in the issue description :slightly_smiling_face: let me know what you think?
