### ISSUE TITLE
🚀 Feature: Automatic Contributor Section Updates via GitHub Action

### ISSUE THREAD

**Issue by SagarSharma101** [arc53/DocsGPT#1352]
### 🔖 Feature description

Automate the update of the "Contributors" section in the repository (README or CONTRIBUTORS file) using a GitHub Action that runs periodically or on specific triggers. This would retrieve contributors from GitHub’s API and ensure that the list is always current without manual updates.

### 🎤 Why is this feature needed ?

In my use-case, manually maintaining the list of contributors becomes cumbersome, especially in larger projects or open-source repos where multiple contributions happen regularly. It is easy to overlook some contributors, leading to inaccuracies in recognition. Automating this process would ensure that contributors are always properly credited without manual intervention, increasing both project transparency and contributor satisfaction.

### ✌️ How do you aim to achieve this?

I will write a script using GitHub Action that automates the process of fetching contributors from the GitHub API and updating the README or CONTRIBUTORS file. The action will run on a schedule or specific triggers like pull request merges, ensuring the contributors' list is always current.

### 🔄️ Additional Information

I tried manually updating the contributors list, but it’s not sustainable for large projects or those with many collaborators. I also looked into third-party tools, but they lack the seamless integration of GitHub Actions and sometimes don't offer enough flexibility in formatting the contributor section.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SagarSharma101** [comment]
assign me if you find this usefull =)

**Comment by dartpain** [comment]
Im not sure if github API should be used for this.
Can you help me understand why it needs to run inside github action instead of a widget that uses API.
Thank you!

**Comment by SagarSharma101** [comment]
Thank you for your feedback! I understand your point about using a widget and the GitHub API.

The main reason for using a GitHub Action is that I want the contributors' list to be updated directly in the repository’s README or CONTRIBUTORS file. This makes the list static and version-controlled, ensuring that it's always part of the repo itself. By doing this through a GitHub Action, we can automate the update process based on events like pull request merges or on a scheduled basis, without needing manual intervention.

A widget using the GitHub API could certainly display contributors dynamically, but it wouldn't update the actual files in the repo. Additionally, having the contributors visible in the repo itself (even in local clones) is important for me, as this provides transparency and recognition for all contributors, whether someone is viewing the project on GitHub or locally.
