### ISSUE TITLE
Fix: Help is not aligned with settings

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1374]
![CleanShot 2024-10-23 at 23 09 23@2x](https://github.com/user-attachments/assets/19246fb3-9e7b-4a5e-9497-4c0b8e4680d8)

Both icons and text should be aligned. For setting and about menu.

**Comment by marceloams** [comment]
Hey @dartpain, I'd like to contribute. Could you please assign this issue to me?
