### ISSUE TITLE
🚀 Feature: Add "Back to Top" Button

### ISSUE THREAD

**Issue by Ayushjhawar8** [arc53/DocsGPT#1380]
### 🔖 Feature description

I would like to add a "Back to Top" button on the page to allow users to quickly navigate back to the top without manually scrolling. This feature aims to improve usability, especially on pages with a lot of content.

### 🎤 Why is this feature needed ?

This feature would improve navigation and the overall user experience. It allows users to return to the top of the page with a single click, making it more convenient, especially for pages with detailed documentation or long lists.

In my use-case, I find it inconvenient to scroll all the way up when I need to access the top links or navigation menu, so this button would be a time-saver.

### ✌️ How do you aim to achieve this?

I would like this feature to include a "Back to Top" button, styled in alignment with the current UI design. Ideally, it would be positioned at the bottom right or center of the page and remain visible as the user scrolls down.

### 🔄️ Additional Information

I tried using some keyboard shortcuts to scroll up quickly, but they aren’t as intuitive for all users. Another potential solution could be a floating sidebar, but that might add visual clutter.

Sample Screenshot
![image](https://github.com/user-attachments/assets/88db1fbd-653b-4a50-93ce-4202a9be116e)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Ayushjhawar8** [comment]
please review this and if found usefull assign me =)

**Comment by dartpain** [comment]
Think we already have a back to top button in the conversation.

Thank you so much!

**Comment by ManishMadan2882** [comment]
Don't think that we will need this issue

**Comment by Ayushjhawar8** [comment]
i was saying for the readme file back to top , im pretty sure i cant see one
![image](https://github.com/user-attachments/assets/32f04c47-107e-4758-b018-3be916ea6ae7)
