### ISSUE TITLE
🚀 Feature: Want to add Model "Type" Selection on Top 

### ISSUE THREAD

**Issue by mehdi621-git** [arc53/DocsGPT#1387]
### 🔖 Feature description

Just like in Chat gpt the model type selection is also present on top where you could select the model between gpt 4.0 gpt 3.5 etc.

### 🎤 Why is this feature needed ?

Just like I want to add that on Top . It has many benefit:
=> Means in future may a person using your pro model and his credits went away then he could not switch to basic or default mode . He should have to start new message and this will loose his focus to work and provides bad impact
=>Sometimes you need some basic task which you want to ask through your basic mode by remaining in your pro conversation then it would be too difficult to switch.

### ✌️ How do you aim to achieve this?

The functionality is provided on first page I want to make that functionality global without distructing ui.
![req docgtp](https://github.com/user-attachments/assets/b1682d3f-c1d2-49b7-885a-d5045d66936a)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by ManishMadan2882** [comment]
Thanks for your suggestion, we have planned for this feature but this component couldn't be accessed on this repository
