### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by gulugulu888** [arc53/DocsGPT#148]
app.py", line 51, in <module>
    template = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 1814: illegal multibyte sequence

**Comment by dartpain** [comment]
Whats the python version that you are using,
You can check it with  `python --version
`

**Comment by gulugulu888** [comment]
> Whats the python version that you are using, You can check it with `python --version `

3.9.12

**Comment by dartpain** [comment]
Can you try with python 3.10 please?
