### ISSUE TITLE
an error after running python ingest.py ingest

### ISSUE THREAD

**Issue by gulugulu888** [arc53/DocsGPT#156]
Traceback (most recent call last):
  File "ingest.py", line 14, in <module>
    from parser.file.bulk import SimpleDirectoryReader
ModuleNotFoundError: No module named 'parser.file'; 'parser' is not a package

**Comment by gulugulu888** [comment]
python version 3.8.1

**Comment by dartpain** [comment]
Can you try running with python 3.9 or 3.10 please?

**Comment by gulugulu888** [comment]
> Can you try running with python 3.9 or 3.10 please?

sure, but the error still exists. I've created a new conda env with python 3.9

**Comment by dartpain** [comment]
Make sure you use your cli from scripts folder

**Comment by gulugulu888** [comment]
> 

I use anaconda env and change directory to scripts folder, but the error still exists

**Comment by dartpain** [comment]
Parser is just a python module.

Can you tell me more about the environment:
what os

then once you do get the error please send me a full error traceback and include the command please

**Comment by dartpain** [comment]
And please check your python version using `python --version` and submit the output here too
