### ISSUE TITLE
in-conversation memory

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#16]
Should be done in two parts
1. pass history with each api request
2. Add history section in the template and include it in the prompt template(limit it two two questions and answers)

**Comment by dartpain** [comment]
done in #96

**Comment by DSXiangLi** [comment]
@dartpain I The history Prompt is  not used in the chatgpt, only in other llm. Is that correct ?

**Comment by nikohd12** [comment]
> @dartpain I The history Prompt is not used in the chatgpt, only in other llm. Is that correct ?

Yes, I think it does not use history in OpenAI. Atleast in port 5173.
