### ISSUE TITLE
UI Update. Added arrow to go back to the end of conversation

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#170]
Added an arrow to go back to the end of conversation when the convesation is long enough. The arrow appears when the user scrolls away from the last message
![arrow](https://user-images.githubusercontent.com/17906039/225041820-2cc4199e-4893-4f8e-90fc-3d5936cb6d26.PNG)

On movile the arrow should be transparent when it overlaps text. Use ChatGPT as a referece

**Comment by hirenchauhan2** [comment]
Hi, I would like to work on this! Could you please assign this to me?

**Comment by dartpain** [comment]
Perfect, thank you! assigned
