### ISSUE TITLE
query time

### ISSUE THREAD

**Issue by fjun99** [arc53/DocsGPT#182]
Currently, DocsGPT use VectorDBQA. According to my local test in Jupyter Note, a query costs 1-2 mins.

```
   chain = VectorDBQA.from_chain_type(
      llm=llm, 
      chain_type="map_reduce", 
      vectorstore=docsearch,
      k=4,
      return_source_documents= True ,
      search_type = 'mmr',
      chain_type_kwargs={"question_prompt": p_chat_reduce,
                         "combine_prompt": p_chat_combine}
      )
   result = chain({"query": question})
```

When I change it to ChatVectorDBChain.from_llm, a query costs 15-25 seconds.

```
chain = ChatVectorDBChain.from_llm(
    llm=llm,
    vectorstore=docsearch,
    prompt=p_chat_combine,
    qa_prompt=p_chat_reduce,
    top_k_docs_for_context=3,
    return_source_documents=False,
    # kwargs= {
    #     "question_prompt": p_chat_reduce,
    #     "combine_prompt": p_chat_combine
    #     }
    )
```

Would you please consider to make the query faster?

**Comment by dartpain** [comment]
Done, updated, thank you!

**Comment by 137-rick** [comment]
> Done, updated, thank you!

hi sire @fjun99  @dartpain please test the answer 

it's seem the reply not good and smart now~

**Comment by dartpain** [comment]
Hmm. 
I see, its a bit more strict now, but for my mock tests it works well.
I suggest you provide me with your vectors and mock questions so i can try work on that specific case

**Comment by 137-rick** [comment]
wow……it's see i need some skill to export this.how can i do this

**Comment by 137-rick** [comment]
> Hmm. @137-rick I see, its a bit more strict now, but for my mock tests it works well. I suggest you provide me with your vectors and mock questions so i can try work on that specific case

hi, sir i found out why not smart

because map_reduce is tree sum 
it s will scan more doc and make sum
make the sum answer the question 
it s slow but provide more info
