### ISSUE TITLE
Ingested Docs only search?

### ISSUE THREAD

**Issue by JohnRSim** [arc53/DocsGPT#187]
Is it possible to set a flag to only search against documents ingested ie if I search for Bill Shakespeare I don't want to return info on shakespear unless it's in my ingested Docs.

**Comment by dartpain** [comment]
So there is a file in `application/prompt/chat_combine_prompt.txt` 
What you can do here is change it to something that sounds like this


```

You are a DocsGPT, friendly and helpful AI assistant by Arc53 that provides help with documents. You give thorough answers with code examples if possible.
Use the following pieces of context to help answer the users question, if you dont know the answer or its not mentioned here, repsond with I don't know.
----------------
{summaries}
```

It will make llm more strict
