### ISSUE TITLE
failed to index, any suggestion for relatively bigger (15MB) text files?

### ISSUE THREAD

**Issue by jneygor8504** [arc53/DocsGPT#188]
hello

I am indexing my own text files (10 files, 0.5~15MB each) thru langchain， with codes similar to https://github.com/arc53/DocsGPT/blob/main/scripts/ingest.py, however it raised APIError: The server had an error while processing your request".

Please shed me a light on how to handle those bigger text file, or I can divide and conquer?but how to "conquer"/Combine index together ?
Thank you so much 

Embedding 🦖:  28%|███████████████████▉                                        | Time Left: 26:49WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 597cd18763c ec0ab9a5ac5b61bc8f49 in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 597cd18763c9dc0ab9a5ac5b61bc8f49 in your message.)",
"type": "server_error",
"param": null,
  ode": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 597cd18763c9dc0ab9a5ac5b61bc8f49 in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Wed, 22 Mar 2023 11:21:52 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Organization': 'user-2wvisc1sdclkxmw3kskmow9d', 'Openai-Processing-Ms': '30026', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Ratelimit-Limit-Requests': '3000', 'X-Ratelimit-Remaining-Requests': '2999', 'X-Ratelimit-Reset-Requests': '20ms', 'X-Request-Id': '597cd18763c9dc0ab9a5ac5b61bc8f49'}.
Embedding 🦖: 100%|███████████████████████████████████████████████████████████████████████| Time Left: 00:00

**Comment by dartpain** [comment]
Check if your vectors have updated

**Comment by jneygor8504** [comment]
thanks you

.faiss and .pkl sounds there .
let me try to lauch
