### ISSUE TITLE
Maximum token issue

### ISSUE THREAD

**Issue by Thayalan21** [arc53/DocsGPT#195]
### Discussed in https://github.com/arc53/DocsGPT/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **Aiman-astios** March 17, 2023</sup>
Hi, I'm new to this OpenAI thing.  
for context I use the same rst file to generate the faiss and pkl file and also ask the same question.

> This is the previous version of the docsgpt. 
![image](https://user-images.githubusercontent.com/110952815/225869397-3bbbf978-0697-4f6c-9cc4-a2fab2976e7b.png)

> This is the latest version of the docsgpt after the changes to the langchain and faiss file (officially).
![image](https://user-images.githubusercontent.com/110952815/225869283-4c8d8f95-c71b-4b54-bb30-fd9ad1c8e38c.png)

why do it get this error, i dont think that the message output from this rst file is more than 8000 words.
</div>

**Comment by Thayalan21** [comment]
![image](https://user-images.githubusercontent.com/104500045/228779922-314d0640-6ff4-43c1-a76d-7ce9873d0844.png)

**Comment by dartpain** [comment]
The context is too large to proces, there are two options, reduce k in the app.py or reduce max_token_length in worker.py
