### ISSUE TITLE
Live demo error

### ISSUE THREAD

**Issue by Duwl-HQ** [arc53/DocsGPT#198]
Demo said there was a problem:

I entered the following question:
How do I setup a connection to moralis web3 api using JavaScript 

Maybe I asked the wrong question?

**Comment by Duwl-HQ** [comment]
No its the same

[PastedGraphic-1.png]

On 3 Apr 2023, at 17:21, Alex ***@***.***> wrote:



Can you try refreshing your page and asking the questions again please

**Comment by Duwl-HQ** [comment]
No its the same

<img width="918" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/108667218/229588405-d21e8612-06eb-4532-98ab-d4b6360fb4ff.png">

**Comment by dartpain** [comment]
Interesting, 
1. What is your email that is used for this account?
2. What extensions do you have installed on your browser
3. can you open developer instruments in your browser and click network, refresh the page and send me a screenshot with data there

If you want to send some of this information confidentially use my email a@tushynski.me

**Comment by Duwl-HQ** [comment]
Nothing to see in network or console, same on safari and chrome on Mac.

Im not actually uploading a source doc, just typing the question

On 3 Apr 2023, at 19:03, Alex ***@***.***> wrote:



Interesting,

  1.  What is your email that is used for this account?
  2.  What extensions do you have installed on your browser
  3.  can you open developer instruments in your browser and click network, refresh the page and send me a screenshot with data there

If you want to send some of this information confidentially use my email ***@***.******@***.***>

**Comment by Duwl-HQ** [comment]
Actually when I select python on the left, it still fails but I get an error in console

<img width="2052" alt="image" src="https://user-images.githubusercontent.com/108667218/229889092-bef489af-1519-4921-b421-60e09f065cf3.png">
