### ISSUE TITLE
What does the source in prompt means?

### ISSUE THREAD

**Issue by buger** [arc53/docsgpt#2]
In prompt https://github.com/arc53/docsgpt/blob/main/application/combine_prompt.txt we can see values like this: `SOURCES: 28-pl 30-pl`. What does it mean? 

Does it related to https://github.com/arc53/docsgpt/blob/main/scripts/ingest_rst.py#L32?
And if so, how do I determine the right number if I want to generate similar prompt example file for my docs?

Thanks!

**Comment by dartpain** [comment]
So sources will basically allow us to find what names of source materials model used to provide an answer. 28-pl is just a name of the document.

So in our use case it will generate names of files that it used.

**Comment by buger** [comment]
I see, so it can be url or anything else which uniquely describe content section.

**Comment by dartpain** [comment]
Exactly!
