### ISSUE TITLE
No .env file 

### ISSUE THREAD

**Issue by darrentmorgan** [arc53/DocsGPT#205]
I'm new to contributing to projects, but I'm curious to why the project couldn't have a .env file and reference the api key using the docker compose:

OPENAI_API_KEY=sk-xxxxxxxxxxxx

-environment
${OPENAI_API_KEY}

Happy to hear what your feedback on doing this would be.

**Comment by cgso** [comment]
Adding to this: There are both a .env_sample file in the solution (which captures OPENAI API Keys) and the Dockerfile which captures the same. Additionally, Readme and Wiki does not agree on where to specify this.

**Comment by dartpain** [comment]
Updated the wiki, just create .env in your root folder and set your OPENAI_API_KEY with your openai api key, docker will pick it up, other instructions are for dev environments
