### ISSUE TITLE
M1 mac support

### ISSUE THREAD

**Issue by darrentmorgan** [arc53/DocsGPT#206]
I'm on the m1 Macbook pro with apple silicone, I'm getting this error from the docker-compose logs mongo command:

```
❯ docker-compose logs mongo
docsgpt-mongo-1  | 
docsgpt-mongo-1  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
docsgpt-mongo-1  |   see https://jira.mongodb.org/browse/SERVER-54407
docsgpt-mongo-1  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
docsgpt-mongo-1  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
```

From reading the documents, it doesn't look like mongodb 6 is support on macos arm chips in many cases:

> https://www.mongodb.com/docs/manual/administration/production-notes/#arm64

Would there be any issue with using mongodb 5 instead for m1 architecture to be backwards compatible?

**Comment by dartpain** [comment]
Im working on mac os, maybe you need rosetta?
