### ISSUE TITLE
Cite sources

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#21]
Add sources section to every reply by the AI in the UI
AI already generates sources. you need to only add it to the frontend. Required data is in the fetch request

**Comment by ouyangtu** [comment]
explainable answers would be a great feature, for human to check for potential error, improve confidence, safety, etc

**Comment by jaredbradley243** [comment]
Is this something @ajaythapliyal and @TaylorS15? are planning on implementing?

**Comment by ajaythapliyal** [comment]
Hey @jaredbradley243 thanks for the suggestion. At the moment we are focusing on completing the current iteration of the project. This sounds like a great feature. Something we can take up in future iterations. Thanks!

**Comment by c0desl1ng3r** [comment]
This will be critical for people to trust the bot's responses, and for developers to understand why it is getting things wrong. To demonstrate the need for this, here are the results from the first, very basic question I asked it (why would I need Docker?!):

![image](https://user-images.githubusercontent.com/1309834/225570113-33297ba5-8abd-4aa5-a538-ab22811608dc.png)

**Comment by dartpain** [comment]
I think it probably saw this page and decided to add it
https://langchain.readthedocs.io/en/latest/tracing/local_installation.html?highlight=docker

**Comment by dartpain** [comment]
just added https://github.com/arc53/DocsGPT/commit/610adcbefc7671d56b3367e6074215480c00ea73
