### ISSUE TITLE
安装后提示no default documentation,下拉框无任何选项，无法进行下一步

### ISSUE THREAD

**Issue by lkjulius** [arc53/DocsGPT#215]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/52229268/233294088-f79abf1d-64b6-4c7f-b725-fd4a9c75552b.png">

**Comment by dartpain** [comment]
Seems lika a backend issue, have you launched all services via docker-compose?
Can you verify that all containers are up and running please

**Comment by bttung-2020** [comment]
did you deployed it to a remote server ?
the frontend side could not communicate to backend site so the pull-down cant show anything.
check browser (chrome) console log for more about error.
in docker-compose.yml change 
- VITE_API_HOST=http://localhost:5001
to - VITE_API_HOST=http://{remote-server-ip-address}:5001
or did you open port 5001 on remote server ?

**Comment by dartpain** [comment]
Everything is hosted on one server for our example, how did you deploy it?

**Comment by xRayCoder** [comment]
@lkjulius 首次打开先在浏览器把弹窗遮罩的元素手动删掉, 上传文档之后下次再打开就可以了.

**Comment by garyfeng** [comment]
same problem. In my case, steps to repeat:
1. in github, start a codespace from `main` branch
2. add `.env`
3. do `docker-compose build && docker-compose up`. This takes 15 min. 
4. launch the browser to the app using the codespace port forwarding. 
5. Can see the initial UI with a modal box to select the initial index. 
6. When selecting, you see the `no default documentation` error in the OP. Cant dismiss the modal so can't do anything. 

I was able to launch the app from a fork about a week ago. Not sure what changed. 

PS: I initially followed the same steps above on a PC where I was running a DocsGPT instance (via docker-compose on the host PC). Interestingly, the `codespace` DocsGPT UI shows the correct URL from github codespace, but it seemed to be connected to the localhost version of the datastore, i.e., it was showing the docs and indices from my localhost. I had to test the above steps on a different machine (mac) with no docker setup.

**Comment by darth-pika-hu** [comment]
@garyfeng @bttung-2020 HTTP connection only allowed for VITE local development. HTTPS connection is required for remote connection. So VITE_API_HOST=http://xxxxx:5001 won't work with codespace or any other remote connections. 

To make it work. If you use some services like Cloudflare tunnel, get an HTTPS connection for the backend. And change it to VITE_API_HOST=https://xxx.yourdomain.com.

**Comment by QiuZiXian** [comment]
我重现了该bug：（即该bug的原因）不是本地运行，而是在服务器上运行。
解决方案：
如果运行在服务器上，要修改docker-compose.yaml中的VITE_API_HOST，将localhost改为服务器ip即可
