### ISSUE TITLE
The "OPENAI_API_KEY" variable is not set

### ISSUE THREAD

**Issue by dfb-hov** [arc53/DocsGPT#216]
I creat .env and set API_KEY/EMBEDDINGS_KEY，but warn this：

**WARN[0000] The "OPENAI_API_KEY" variable is not set. Defaulting to a blank string.** 

![image](https://user-images.githubusercontent.com/116617174/233558800-9bc35091-085c-495f-821e-0ff788b8559a.png)

**Comment by dartpain** [comment]
You have to create .env in the project folder not application now, we changed documentation recently

**Comment by Alignment-Lab-AI** [comment]
> You have to create .env in the project folder not application now, we changed documentation recently

is this still the case?
i receive this error in the project folder
