### ISSUE TITLE
remove styling on the input UI box

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#226]

**Comment by samezzz** [comment]
Can you please provide more info about the issue?

**Comment by dartpain** [comment]
So if you copy paste things into the input box, it will keep some of the sources styling, resulting in things like this
<img width="833" alt="image" src="https://user-images.githubusercontent.com/15183589/236620807-0c6100a5-5cf3-421c-aaa0-02b37581d563.png">

**Comment by samezzz** [comment]
Ahhh oh okay

**Comment by Thayalan21** [comment]
Its solved for me after adding this code


import { forwardRef, useState } from 'react';
import Avatar from '../Avatar';
import { FEEDBACK, MESSAGE_TYPE } from './conversationModels';
import Alert from './../assets/alert.svg';
import { ReactComponent as Like } from './../assets/like.svg';
import { ReactComponent as Dislike } from './../assets/dislike.svg';
import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/cjs/styles/prism';

const ConversationBubble = forwardRef<
  HTMLDivElement,
  {
    message: string;
    type: MESSAGE_TYPE;
    className?: string;
    feedback?: FEEDBACK;
    handleFeedback?: (feedback: FEEDBACK) => void;
  }
>(function ConversationBubble(
  { message, type, className, feedback, handleFeedback },
  ref,
) {
  const [showFeedback, setShowFeedback] = useState(false);
  let bubble;

  function copyToClipboard(text: string) {
    const tempTextArea = document.createElement('textarea');
    tempTextArea.value = text.replace(/(```.*[\r\n])|(~~~.*[\r\n])|([_*]{1,2})/g, '');
    document.body.appendChild(tempTextArea);
    tempTextArea.select();
    document.execCommand('copy');
    document.body.removeChild(tempTextArea);
  }

  if (type === 'QUESTION') {
    bubble = (
      <div 
      
        ref={ref} 
        className={`flex flex-row-reverse self-end ${className}`}
        onCopy={(event) => {
          event.preventDefault();
          const text = window
         .getSelection()
         .toString()
         .replace(/\u200B/g, ''); // remove zero-width space characters
        event.clipboardData.setData('text/plain', text);
       }}
    >
        <Avatar className="mt-4 text-2xl" avatar="🧑‍💻"></Avatar>
        <div className="mr-2 ml-10 flex items-center rounded-3xl bg-blue-1000 p-3.5 text-white">
          <ReactMarkdown className="whitespace-pre-wrap break-words">
            {message}
          </ReactMarkdown>
        </div>
      </div>
    );
  } else {
    bubble = (
      <div
        ref={ref}
        className={`flex self-start ${className}`}
        onMouseEnter={() => setShowFeedback(true)}
        onMouseLeave={() => setShowFeedback(false)}
        onCopy={(event) => {
          event.preventDefault();
         const text = window
          .getSelection()
          .toString()
          .replace(/\u200B/g, ''); // remove zero-width space characters
        event.clipboardData.setData('text/plain', text);
      }}
    >
        <Avatar className="mt-4 text-2xl" avatar="🦖"></Avatar>
        <div
          className={`ml-2 mr-5 flex items-center rounded-3xl bg-gray-1000 p-3.5 ${
            type === 'ERROR'
              ? ' rounded-lg border border-red-2000 bg-red-1000 p-2 text-red-3000'
              : ''
          }`}
          style={{ userSelect: 'all' }} // Add this line
        >
          {type === 'ERROR' && (
            <img src={Alert} alt="alert" className="mr-2 inline" />
          )}
          <ReactMarkdown
            className="whitespace-pre-wrap break-words"
            components={{
              code({ node, inline, className, children, ...props }) {
                const match = /language-(\w+)/.exec(className || '');

                return !inline && match ? (
                  <SyntaxHighlighter
                    PreTag="div"
                    language={match[1]}
                    {...props}
                    style={vscDarkPlus}
                  >
                    {String(children).replace(/\n$/, '')}
                  </SyntaxHighlighter>
                ) : (
                  <code className={className ? className : ''} {...props}>
                    {children}
                  </code>
                );
              },
            }}
          >
            {message}
          </ReactMarkdown>
        </div>
        <div
          className={`mr-2 flex items-center justify-center ${
            feedback === 'LIKE' || (type !== 'ERROR' && showFeedback)
              ? ''
              : 'md:invisible'
          }`}
        >
          <Like
            className={`cursor-pointer ${
              feedback === 'LIKE'
                ? 'fill-blue-1000 stroke-blue-1000'
                : 'fill-none  stroke-gray-4000 hover:fill-gray-4000'
            }`}
            onClick={() => handleFeedback?.('LIKE')}
          ></Like>
        </div>
        <div
          className={`mr-10 flex items-center justify-center ${
            feedback === 'DISLIKE' || (type !== 'ERROR' && showFeedback)
              ? ''
              : 'md:invisible'
          }`}
        >
          <Dislike
            className={`cursor-pointer ${
              feedback === 'DISLIKE'
                ? 'fill-red-2000 stroke-red-2000'
                : 'fill-none  stroke-gray-4000 hover:fill-gray-4000'
            }`}
            onClick={() => handleFeedback?.('DISLIKE')}
          ></Dislike>
        </div>
      </div>
    );
  }
  return bubble;
});

export default ConversationBubble;

**Comment by Thayalan21** [comment]
Basically i added the code below to the question and answer bubble in convsersationbubble.tsx

ref={ref} 
        className={`flex flex-row-reverse self-end ${className}`}
        onCopy={(event) => {
          event.preventDefault();
          const text = window
         .getSelection()
         .toString()
         .replace(/\u200B/g, ''); // remove zero-width space characters
        event.clipboardData.setData('text/plain', text);
       }}

**Comment by Achandu905** [comment]
Is this issue resolved.? Please reply

**Comment by Kishan-Ved** [comment]
Is this issue still open?

**Comment by SandeepJoel** [comment]
Is this issue still open?

**Comment by dartpain** [comment]
Just fixed it #298
