### ISSUE TITLE
directly addressing documents fails and calling docs other than that visible in source docs fails

### ISSUE THREAD

**Issue by bozo32** [arc53/DocsGPT#230]
command: please compare the claims in trump_speech.txt and rutte_speech.txt
and
command: please summarize trump_speech.txt
produces: I'm sorry, but I cannot do that task as neither the trump_speech.txt nor the rutte_speech.txt was mentioned before, and they are not available for me to access.
when both are in the vector store
what does trump say in his speech produces a valid output when selected in the source docs window
what does Rutte say in his speech does not produce an output when it is not selected in the source docs window

please compare the claims in trump_speech.txt and rutte_speech.txt

🦖
I'm sorry, but I cannot do that task as neither the trump_speech.txt nor the rutte_speech.txt was mentioned before, and they are not available for me to access.

Please provide more information or the full text of both speeches so I can compare the claims made in each.

🧑‍💻
what do trump and rutte say in their speeches?

🦖
I'm sorry, I would need you to specify which specific speeches by Trump and Rutte you are referring to in order to provide an accurate answer. Can you please provide more information or context about the speeches?

🧑‍💻
what does trump say in his speech

🦖
In his speech, Trump addresses the Coronavirus outbreak and outlines various actions his administration is taking to combat its spread. He emphasizes the importance of following guidelines provided by local officials and practicing good hygiene such as washing hands and covering the mouth when coughing or sneezing. He also announces emergency financial relief for workers affected by the virus and calls on Congress to take legislative action to extend this relief. He instructs the Small Business Administration to provide economic loans for businesses affected by the virus and calls for an increase in funding for this program. Additionally, he defers tax payments for certain individuals and businesses negatively impacted by the virus and calls for immediate payroll tax relief. Trump stresses the need for unity and putting politics aside, as well as the resilience of the American people in overcoming adversity.

🧑‍💻
what does rutte say in his speech?

🦖
I'm sorry, but without further information, it is difficult to answer your question. Rutte could be any person with that surname, and they could have given multiple speeches on various topics. If you could provide more context or information on which Rutte you are referring to and what speech it is, I would be happy to try and assist you better.

**Comment by dartpain** [comment]
Solved by mentioning metadata in ingested chunks
