### ISSUE TITLE
Dont close modal window "Select Source Documentation"

### ISSUE THREAD

**Issue by pomazanbohdan** [arc53/DocsGPT#248]
As soon as I go to the page, this window immediately appears, which blocks everything else, you cannot close it

![image](https://github.com/arc53/DocsGPT/assets/696713/6a700e2a-28a0-470a-8110-66dc7f8d0517)

**Comment by pomazanbohdan** [comment]
![image](https://github.com/arc53/DocsGPT/assets/696713/f4d0d5b1-3eb0-40df-b558-815135a392f4)

**Comment by pomazanbohdan** [comment]
Need move HOST env to .env

I changed in docker-composite to an external IP where the port is 5001 and the window was closed, and the file upload also worked

**Comment by Jacky-fe** [comment]
I have meet the same problem~

**Comment by marcospolanco** [comment]
The port changed to `7091` and now what works is a line such as:
`VITE_API_HOST=http://docsgpt.example.com:7091`

**Comment by tenokami** [comment]
The modal no longer appears. Closing
