### ISSUE TITLE
Please update the README file to reflect the latest instructions to build the project as a dev

### ISSUE THREAD

**Issue by magedhelmy1** [arc53/DocsGPT#258]
I try to follow the readme but it said that some files to do not exist, can I please ask you to update the dev readme instructions? thank you

**Comment by RikSchoonbeek** [comment]
I followed the instructions yesterday and they seem to work. I only had one problem where I received an openai.error.APIConnectionError when asking a question to a document, for which I made a [similarly named issue](https://github.com/arc53/DocsGPT/issues/276), and suggested a solution, which is also merged.

I followed these instruction on the main GitHub page: https://github.com/arc53/DocsGPT#development-environments

Should work.

Maybe post the error that you have.

**Comment by Cioraz** [comment]
Hey, how did you setup the celery worker?
The flask app runs but celery is running into issues

**Comment by dartpain** [comment]
I updated and tested instructions
https://github.com/arc53/DocsGPT/blob/main/README.md#development-environments

Please check it out and tell me where its failing @Cioraz

**Comment by Cioraz** [comment]
Working now
