### ISSUE TITLE
OpenAPI3 (Swagger) parsing

### ISSUE THREAD

**Issue by shadowbq** [arc53/DocsGPT#26]
OpenAPI3 (Swagger api) parsing of the json file would be extremely helpful as this is commonly published docs.

**Comment by Junaid-Bashir-Kernel** [comment]
can i work on it ?

**Comment by dartpain** [comment]
Yes please, this would be great! Thank you!

**Comment by tmikaeld** [comment]
This is really interesting! @dartpain what's your strategy for the structured content? Using the swagger paths object with nested schemas or just ingest the whole thing?

**Comment by dartpain** [comment]
I think we have to figure out how to correctly convert it to txt basically, think of a way we can represent important information in a clean way

**Comment by ahmed1hsn** [comment]
@dartpain This looks like an interesting problem. Can you give few examples of the format in which you want to convert OpenAPI3 file? Any sample from existing code?

**Comment by daemon-reconfig** [comment]
is this issue still open?

**Comment by dartpain** [comment]
Yep, still open

**Comment by Exterminator11** [comment]
hey @dartpain, if this issue is still open I would like to contribute and if you could further explain the issue it would be very helpful
Thanks

**Comment by dartpain** [comment]
Please do @Exterminator11 , this would be very helpful.
To start woriking on it, I think we need to figure out how to convert important information from swagger fromat into text / prompt. The you need to createa a concrete class in the /scripts/parser/file folder and call it openapi3_parser.py and similarly to other files in that folder we need to create parse_file method that simply returns text. If you need more guidance, please dont hesitate reaching out in our discord as well

**Comment by Exterminator11** [comment]
thanks for the swift reply, will start working immediately😃.

**Comment by staticGuru** [comment]
Hi @dartpain 
I am new to this repo.
can I work on this feature?

**Comment by Exterminator11** [comment]
> Hi @dartpain I am new to this repo. can I work on this feature?

I'm currently working on it, but if I happen to drop it I'll be sure to drop you a comment😀.
Thanks
