### ISSUE TITLE
'str' object has no attribute 'reverse'

### ISSUE THREAD

**Issue by trattaa** [arc53/DocsGPT#262]
DocsGPT is running in a Docker environment v24.0.2 on the Ubuntu 22.04.2, along with Traefik v2.10. Traefik has been properly configured for both the Frontend and Backend. When making requests to the documentation through the Answer endpoint in the Backend environment, the following error occurs.
_Here is the payload that is being sent in the request:_
![2023-06-14_120604](https://github.com/arc53/DocsGPT/assets/44088228/fe25cf97-c8d7-44a1-941d-f264d1899a24)

_Here are the Docker logs for the Backend:_
![2023-06-14_120615](https://github.com/arc53/DocsGPT/assets/44088228/a9535e79-8cfc-4fd5-8bb8-d487ac4f55fe)

Initially, this endpoint was functioning correctly, but after a few requests, a similar error started occurring. Reloading the page, restarting the entire stack, and even restarting the stack with a complete removal of all DocsGPT data, including the Mongo data, did not resolve the issue.

**Comment by mepuntojr1** [comment]
Same issue with me. I used AWS Lightsail in this guide: https://github.com/arc53/DocsGPT/wiki/Hosting-the-app

![image](https://github.com/arc53/DocsGPT/assets/58497534/e1bd37e7-a517-4566-9c9f-1c83eb2c7afb)

**Comment by dartpain** [comment]
Oh guys its not recomennded to use that frontend, its depreciated now, please use http://localhost:5173/
Basically port 5173 to serve FE
