### ISSUE TITLE
Please support RWKV world model

### ISSUE THREAD

**Issue by xiaol** [arc53/DocsGPT#268]
As stated in the title
RWKV(https://rwkv.com) world model support 100+ languages ,https://huggingface.co/BlinkDL/rwkv-4-world 
 can try it online here 7B world 75%(training in process)
https://rwkv-next-web.ai-creator.net/

**Comment by abdulhakam** [comment]
and in addition to that, some 3B_q4 models too , my PC is ****, so . . . please?

**Comment by dartpain** [comment]
Should be supported or any openai compatable endpoint.
https://docs.docsgpt.cloud/Guides/How-to-use-different-LLM#for-openai-compatible-endpoints
