### ISSUE TITLE
UI/UX Updates 

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#279]
I've made some updates to the [Wireframes](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=empTAOgMt6xN8qBu-1)

- [ ] 1. A section with sources with updated design. 

![image](https://github.com/arc53/DocsGPT/assets/17906039/9c682a50-379f-4a4f-b8e7-ab72d0658ba2)

From left to right the source labels depict different state: 1. Selected 2. Hovered 3. Inactive
![image](https://github.com/arc53/DocsGPT/assets/17906039/777cf332-9af0-4c5a-988d-778119ae799f)

- [ ] 2. Clickable suggested follow-up questions 

![image](https://github.com/arc53/DocsGPT/assets/17906039/c982faf0-44b3-4091-81fe-b52513c205e0)

On click a message from the user will be automatically sent and visible in that chat as if the user sent it. After clicking any suggested question, the suggested questions will dissapear and a new set of them will generate under the last response by DocsGPT

if the question is to long, the label wraps and the corners get clightly less rounded:

![image](https://github.com/arc53/DocsGPT/assets/17906039/2ec6ee52-d718-4efb-ba8c-1fe465170fa8)

- [x] 3. Rounded up the corners for consistency (highlighted in yellow)

![image](https://github.com/arc53/DocsGPT/assets/17906039/f3da5290-b7d9-48f1-8458-ab474360cbf7)

Same for all of the buttons

![image](https://github.com/arc53/DocsGPT/assets/17906039/5e6c3976-45f2-4e20-be73-2143dbd0ec87)

- [ ] 4. Updated Empty state chat screen

![image](https://github.com/arc53/DocsGPT/assets/17906039/8aa71e96-2f1b-41c3-bcfa-c06afaf078ac)

Mobile
![Frame 108](https://github.com/arc53/DocsGPT/assets/17906039/3434b9b8-a0fa-45d8-8aaf-f921f5d8ee13)

Hit me up on Discord with @Nick for review and questions.

**Comment by DenyTwice** [comment]
Hey, I'd like to work on task 3 and 4. Could this be assigned to me?

**Comment by dartpain** [comment]
Yep, absolutely, Thank you, if you have any questions please dont hesitate to contact me

**Comment by vikaschouhan97** [comment]
Hey,
Since 3rd and 4th task is already completed can I take up 1st and 2nd point given in description. Can it be assigned to me

**Comment by dartpain** [comment]
Absolutely, that would be great!

**Comment by siiddhantt** [comment]
Hey! I've created a PR for the first task that isn't complete yet. 
Could someone please review it, thanks.

**Comment by lakshmi930** [comment]
Hey, can I pick up 4th task if it's not completed and no one's working on it?
