### ISSUE TITLE
Possible to use without openAI and use instructor embeddings or any other MTEB?

### ISSUE THREAD

**Issue by Ananderz** [arc53/DocsGPT#286]
Hi,

Wondering if there is a way to truly use this locally with local embeddings, chroma and a open source LLM. It would be a great addition!

**Comment by dartpain** [comment]
You can use local embeddings from sentence transformer by swapping out embeddings name. 
You can supply a huggingfaces name in a `EMBEDDINGS_NAME` env variable to use anything else.
