### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by kackbob** [arc53/DocsGPT#287]
when traning show below message:

 error_code=rate_limit_exceeded error_message='Rate limit reached for default-text-embedding-ada-002 in organization org-xx on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

then ask question,message is:
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-xxx on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..

Do you have any suggestions?

**Comment by jungleHxj** [comment]
me too

**Comment by dartpain** [comment]
Probably your accrount is new, I would suggest adding payment method and to wait a day or two
