### ISSUE TITLE
Can you share the code with google Auth?

### ISSUE THREAD

**Issue by gamingflexer** [arc53/DocsGPT#289]
I did searched it but couldn’t find it, while also added it in the discussion.

Thanks a lot !

**Comment by dartpain** [comment]
I use clerk.dev for auth on demo, here is a quick wrapper for your app.tsx


```
import { Routes, Route } from 'react-router-dom';
import Navigation from './Navigation';
import Conversation from './conversation/Conversation';
import About from './About';
import { useState } from 'react';
import { ActiveState } from './models/misc';
import { inject } from '@vercel/analytics';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/clerk-react';

const clerkPubKey = import.meta.env.VITE_REACT_APP_CLERK_PUBLISHABLE_KEY;

inject();

export default function App() {
  //TODO : below media query is disjoint from tailwind. Please wire it together.
  const [navState, setNavState] = useState<ActiveState>(
    window.matchMedia('(min-width: 768px)').matches ? 'ACTIVE' : 'INACTIVE',
  );

  return (
    <ClerkProvider publishableKey={clerkPubKey}>
      <SignedIn>
        <div className="min-h-full min-w-full">
          <Navigation navState={navState} setNavState={setNavState} />
          <div
            className={transition-all duration-200 ${
              navState === 'ACTIVE' ? 'ml-0 md:ml-72 lg:ml-60' : 'ml-0 md:ml-16'
            }}
          >
            <Routes>
              <Route path="/" element={<Conversation />} />
              <Route path="/about" element={<About />} />
            </Routes>
          </div>
        </div>
        <div className="absolute top-4 right-4 z-50">
          <UserButton />
        </div>
      </SignedIn>
      <SignedOut>
        <div className="min-h-full min-w-full">
          <Navigation navState={navState} setNavState={setNavState} />
          <div
            className={transition-all duration-200 ${
              navState === 'ACTIVE' ? 'ml-0 md:ml-72 lg:ml-60' : 'ml-0 md:ml-16'
            }}
          >
            <Routes>
              <Route path="/" element={<Conversation />} />
              <Route path="/about" element={<About />} />
            </Routes>
          </div>
        </div>
      </SignedOut>
    </ClerkProvider>
  );
}
```

**Comment by spencerwongfeilong** [comment]
> I use clerk.dev for auth on demo, here is a quick wrapper for your app.tsx
> 
> ```
> import { Routes, Route } from 'react-router-dom';
> import Navigation from './Navigation';
> import Conversation from './conversation/Conversation';
> import About from './About';
> import { useState } from 'react';
> import { ActiveState } from './models/misc';
> import { inject } from '@vercel/analytics';
> import {
>   ClerkProvider,
>   SignedIn,
>   SignedOut,
>   UserButton,
> } from '@clerk/clerk-react';
> 
> const clerkPubKey = import.meta.env.VITE_REACT_APP_CLERK_PUBLISHABLE_KEY;
> 
> inject();
> 
> export default function App() {
>   //TODO : below media query is disjoint from tailwind. Please wire it together.
>   const [navState, setNavState] = useState<ActiveState>(
>     window.matchMedia('(min-width: 768px)').matches ? 'ACTIVE' : 'INACTIVE',
>   );
> 
>   return (
>     <ClerkProvider publishableKey={clerkPubKey}>
>       <SignedIn>
>         <div className="min-h-full min-w-full">
>           <Navigation navState={navState} setNavState={setNavState} />
>           <div
>             className={transition-all duration-200 ${
>               navState === 'ACTIVE' ? 'ml-0 md:ml-72 lg:ml-60' : 'ml-0 md:ml-16'
>             }}
>           >
>             <Routes>
>               <Route path="/" element={<Conversation />} />
>               <Route path="/about" element={<About />} />
>             </Routes>
>           </div>
>         </div>
>         <div className="absolute top-4 right-4 z-50">
>           <UserButton />
>         </div>
>       </SignedIn>
>       <SignedOut>
>         <div className="min-h-full min-w-full">
>           <Navigation navState={navState} setNavState={setNavState} />
>           <div
>             className={transition-all duration-200 ${
>               navState === 'ACTIVE' ? 'ml-0 md:ml-72 lg:ml-60' : 'ml-0 md:ml-16'
>             }}
>           >
>             <Routes>
>               <Route path="/" element={<Conversation />} />
>               <Route path="/about" element={<About />} />
>             </Routes>
>           </div>
>         </div>
>       </SignedOut>
>     </ClerkProvider>
>   );
> }
> ```

hello can i check how to use this ? =D
