### ISSUE TITLE
How can I get longer answers

### ISSUE THREAD

**Issue by hiovi** [arc53/DocsGPT#294]
All answers get cut off short. I am running docsgpt locally. How could I increase the token limit in the response?
<img width="1899" alt="Screenshot 2023-08-04 at 03 24 17" src="https://github.com/arc53/DocsGPT/assets/43932002/184fda23-d6b2-44be-a438-004dfa320484">

**Comment by dartpain** [comment]
Go to your application/app.py file

somewhere in the /stream endpoint you will find this line
```
completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=messages_combine, stream=True,
                                                  max_tokens=500, temperature=0)
```

adjust max_tokens accrodingly, to 750 for example
