### ISSUE TITLE
Estimate costs

### ISSUE THREAD

**Issue by buger** [arc53/DocsGPT#3]
Hello!

Would be great to have an option to run ingest script in dry run mode, so it will print how many tokens it will cost, before calling OpenAI API.

Also can you give any idea on how to estimate it based on docs and metadatas fields https://github.com/arc53/docsgpt/blob/main/scripts/ingest_rst.py#L36?

Thanks!

**Comment by dartpain** [comment]
Great suggestion! Thank you, its totally posibble

Current example with docs from pandas coster around 2$ i think no more than 4

**Comment by jaredbradley243** [comment]
I'll take this one!

**Comment by jaredbradley243** [comment]
@buger This is almost finished. Code is waiting to be merged. Let me know what you think when you try it!
