### ISSUE TITLE
Error training on new docs

### ISSUE THREAD

**Issue by pshriwise** [arc53/DocsGPT#31]
Getting this error out of the gate when trying to train on a single new `.rst` file. Any thoughts?

```python
Traceback (most recent call last):
  File "/home/pshriwise/soft/doc-gpt/docsgpt/scripts/ingest_rst.py", line 36, in <module>
    store = FAISS.from_texts(docs, OpenAIEmbeddings(), metadatas=metadatas)
  File "/home/pshriwise/.pyenv/versions/3.9.1/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 192, in from_texts
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range
```

**Comment by bil0u** [comment]
@pshriwise Could you provide the `.rst` file that causes the error?

**Comment by pshriwise** [comment]
Sure thing! https://github.com/openmc-dev/openmc/blob/develop/docs/source/index.rst

**Comment by jaredbradley243** [comment]
@pshriwise Hey Patrick, 

If you haven't already, create a folder named "_**scikit-learn**_" inside the "_**scripts**_" folder and toss your **index.rst** inside of it. That should fix your problem.

You can really name the folder anything you would like, just make sure it matches the path in the **ingest_rst.py** and **ingest_rst_sphinx.py** files: 

```ps = list(Path("<FolderName>").glob("**/*.rst"))```

![image](https://user-images.githubusercontent.com/107898107/217136741-90b9718e-7a52-4b46-ad71-fe36b9b7b63a.png)

**Comment by jaredbradley243** [comment]
Let me know if that works for you so I can close the issue. :)

**Comment by pshriwise** [comment]
It did. Thanks! I appreciate the help!

**Comment by jaredbradley243** [comment]
No problem! Glad to help.
