### ISSUE TITLE
Demo to allow users hook up their own tokens in frontend

### ISSUE THREAD

**Issue by zeckem19** [arc53/DocsGPT#32]
getting a HTTP 500  when typing into the chat on https://docsgpt.arc53.com/

**Comment by dartpain** [comment]
Sorry our OpenAI credits finished, we need to hook up another

**Comment by dartpain** [comment]
Ill allow users to hook up their own tokens

**Comment by dartpain** [comment]
Its alive again https://docsgpt.arc53.com/
