### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [arc53/DocsGPT#321]
Dear DocsGPT developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. I hope to get in touch with you.

Best regards,
vansinhu

**Comment by dartpain** [comment]
Hi, I see that the model has huggingface page, this it should work locally for users too, using `from_pretrained`
If you want, you can provide some examples in our documentation.
You may want to check out https://github.com/arc53/DocsGPT/blob/main/CONTRIBUTING.md to get you started

**Comment by dartpain** [comment]
A quick not for people who are thinking about using a different LLM with docsgpt.
https://docs.docsgpt.cloud/Guides/How-to-use-different-LLM
