### ISSUE TITLE
Add a "continue generation" button

### ISSUE THREAD

**Issue by FCPercival** [arc53/DocsGPT#341]
As the title suggests it could be a useful feature.

**Comment by Aatmaj-Zephyr** [comment]
I would like to develop figma UI for this button

**Comment by dartpain** [comment]
Yep, would be great, @tenokami can take a look at that later

**Comment by Vaibhav91one** [comment]
Is the functionality for the continue generation button present. if it is can I implement it in the UI.

**Comment by Aatmaj-Zephyr** [comment]
Can you please assign the issue to me for the hacktoberfest?
Also How should I go about the PR and access to the Figma file?

**Comment by dartpain** [comment]
I think this issue consists of two parts, backend and frontend.
First we need to implement a similar endpoint to /api/answer for the backend (@Vaibhav91one  to answer your question - no)
Second is Frontend implementation in react

**Comment by Vaibhav91one** [comment]
> I think this issue consists of two parts, backend and frontend. First we need to implement a similar endpoint to /api/answer for the backend (@Vaibhav91one to answer your question - no) Second is Frontend implementation in react

Okay. But you can raise this backend issue if you like. then later the frontend issue.

**Comment by tenokami** [comment]
My suggestion for the UI of this button

Use search "Continue generating"

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=dl0y8pTiva7YoU6z-1

![image](https://github.com/arc53/DocsGPT/assets/17906039/311179b4-1d6a-47be-83eb-dee09ac84026)
