### ISSUE TITLE
Error when changing the source docs to other file.

### ISSUE THREAD

**Issue by Nhan-Vo** [arc53/DocsGPT#343]
When I use the default source docs it output normally but when I change to the other file, it gives the following error. Please help me fix it. 
![image](https://github.com/arc53/DocsGPT/assets/88568930/cccea783-230a-40f9-85a4-ba12ba1e7062)

**Comment by Nhan-Vo** [comment]
Here is what the log says:
![image](https://github.com/arc53/DocsGPT/assets/88568930/5b7ef9e2-01c3-4749-82cc-cc96bdcdb599)

**Comment by dartpain** [comment]
This issue should have been fixed. Otherwise its probably caused by launching the app from a wrong folder.
