### ISSUE TITLE
Error communicating with OpenAI

### ISSUE THREAD

**Issue by Bruse333** [arc53/DocsGPT#344]
When ask the question, I can see the error in my terminal:
Error communicating with OpenAI: Invalid URL '/embeddings': No scheme supplied. Perhaps you meant https:///embeddings?
How can I fix this error?  Please, Its important for me.

**Comment by predator094** [comment]
does this issue still persist.

**Comment by Bruse333** [comment]
I just figured the reason out. Thanks



---Original---
From: "Anshul ***@***.***&gt;
Date: Tue, Oct 3, 2023 18:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [arc53/DocsGPT] Error communicating with OpenAI (Issue #344)




 
does this issue still persist.

**Comment by jtopaz1** [comment]
> I just figured the reason out. Thanks
> […](#)
> ---Original--- From: "Anshul ***@***.***&gt; Date: Tue, Oct 3, 2023 18:32 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [arc53/DocsGPT] Error communicating with OpenAI (Issue #344) does this issue still persist. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

How did you fix it? thx

**Comment by jtopaz1** [comment]
> I just figured the reason out. Thanks
> […](#)
> ---Original--- From: "Anshul ***@***.***&gt; Date: Tue, Oct 3, 2023 18:32 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [arc53/DocsGPT] Error communicating with OpenAI (Issue #344) does this issue still persist. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi Bruse, How did you solve it? thx

**Comment by Bruse333** [comment]
This issue just happened when I run the app.py in Anaconda Powershell Prompt.I think the reason is that I did not export the required environment variables. When I use the pycharm to open the whole project and run the app.py,this issue just gone.
