### ISSUE TITLE
Can not go from the About Page to a Chat History/Old Conversation. You can only go to New Chat. 

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#346]

**Comment by Ankit-Matth** [comment]
Hello Sir, I have started working on this issue, please assign it to me...

**Comment by Ankit-Matth** [comment]
Thanks @dartpain for assigning this issue to me.

**Comment by Ankit-Matth** [comment]
Hi @dartpain, to fix this issue I want to verify it locally, for this I need a chat history but searching anything I am getting an error which is given below..
![77](https://github.com/arc53/DocsGPT/assets/146843890/3432c455-7dbc-4b67-90a2-58eed22ff58e)

**Please let me know what I need to do now to get the chat history?**

**Comment by dartpain** [comment]
Seems like you have an error, did you use docker to set up the environment, what env variables did you set?

**Comment by dartpain** [comment]
You can also use this mock api endpoint https://173b8390-8f99-4473-b858-9b05def79a0d.mock.pstmn.io/ to test just frontend. by setting VITE_API_HOST to it

**Comment by Ankit-Matth** [comment]
Yes, I used Docker to set up the environment.
env variables that I set are given below : 
![33](https://github.com/arc53/DocsGPT/assets/146843890/132aebe9-d24d-41ad-8b3c-15f558009ea8)

But I am getting the same error...

**Comment by Ankit-Matth** [comment]
Hello @dartpain, please unassign this issue from me as I am not able to fix this issue.....

**Comment by staticGuru** [comment]
Hi @dartpain 
Can you assign the issues to me.
I am always looking for challenges.
Thanks.

**Comment by daniel-shuy** [comment]
Sorry @staticGuru, I've already created a PR that will fix this (#491)

**Comment by staticGuru** [comment]
Okay,  No problem

**Comment by Ankit-Matth** [comment]
Hello @daniel-shuy, 
would you please tell me how you run DocsGPT locally?
Don't you get the errors I described above when searching for answers locally from DocsGPT?
what env variables did you set?

**Comment by daniel-shuy** [comment]
@Ankit-Matth simply replace the value of `VITE_API_HOST` in `docker-compose.yaml` with the mock api endpoint that @dartpain provided:
> You can also use this mock api endpoint https://173b8390-8f99-4473-b858-9b05def79a0d.mock.pstmn.io/ to test just frontend. by setting VITE_API_HOST to it

**Comment by Ankit-Matth** [comment]
Okay @daniel-shuy.
And thanks for your help.

> @Ankit-Matth simply replace the value of `VITE_API_HOST` in `docker-compose.yaml` with the mock api endpoint that @dartpain provided:
> 
> > You can also use this mock api endpoint https://173b8390-8f99-4473-b858-9b05def79a0d.mock.pstmn.io/ to test just frontend. by setting VITE_API_HOST to it
