### ISSUE TITLE
Improving the UI in Figma

### ISSUE THREAD

**Issue by outlivo** [arc53/DocsGPT#357]
The Chat GPT3 ui design can be improved with a better interface.

**Comment by dartpain** [comment]
What kind of imporvements do you want to make?

**Comment by AnamuddinAhmad** [comment]
@outlivo  which kind of improvement you want please text me fast ??

**Comment by outlivo** [comment]
> What kind of imporvements do you want to make?

The spacing in each modal seems inconsistent. Also, the basic text styles differ in various modals.

**Comment by tenokami** [comment]
@outlivo @smty2018 Thanks for the feedback. I'll take a look and clean it up. Meanwhile I would appreciate it If you could specify with screenshots the exact issues. Or copy the flawed elements, update them in a separate figma project, link them and then I move them to the main one. Thanks

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=Ua5UVmNvlLdOmhIb-1

**Comment by outlivo** [comment]
Here's the copied file I'm working on: https://www.figma.com/file/s16ms4IeaflfKjWFJvVIJt/DocsGPT-(Copy)?type=design&t=wJTXqh09UHkQrPFG-6

**Comment by outlivo** [comment]
> @outlivo @smty2018 Thanks for the feedback. I'll take a look and clean it up. Meanwhile I would appreciate it If you could specify with screenshots the exact issues. Or copy the flawed elements, update them in a separate figma project, link them and then I move them to the main one. Thanks
> 
> https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=Ua5UVmNvlLdOmhIb-1

Here's the copied file I'm working on: https://www.figma.com/file/s16ms4IeaflfKjWFJvVIJt/DocsGPT-(Copy)?type=design&t=wJTXqh09UHkQrPFG-6

Changes made:

- Icons with same dimensions
- Color styles for different themes at a single source
- Alignment of elements using grids
- Components for re-usability (light theme being the base)
- Updating API key modal

**Comment by outlivo** [comment]
@tenokami can you kindly check the changes?

**Comment by tenokami** [comment]
@outlivo That's wonderfull!

**Comment by tenokami** [comment]
@outlivo Would you like to to do more, or you want to make a mini PR with hacktober-accepted label for the merging your updates with the main figma project?

**Comment by outlivo** [comment]
@tenokami I would like to make a few changes and then make a final PR, if possible.

**Comment by tenokami** [comment]
> @tenokami I would like to make a few changes and then make a final PR, if possible.

Sure, go ahead :)

**Comment by tenokami** [comment]
@outlivo Can you please make the list of new changes?

**Comment by outlivo** [comment]
@tenokami sure.

The new changes:
- Updated the API key modal designs
- Updated stop generating modal (in light theme)
- Updated continue generating modal (in dark theme)
- Active and inactive states of the scroll-down button

**Comment by tenokami** [comment]
@outlivo Do you by API key modal mean Upload New Documentation?

**Comment by tenokami** [comment]
@outlivo Wonderful job with organizing using styles, components and auto layout!

I can't promise I will copy 100% everything, but I appreaciate your help.

**Comment by outlivo** [comment]
> @outlivo Do you by API key modal mean Upload New Documentation?

Yes - sorry for causing confusion.

**Comment by outlivo** [comment]
> @outlivo Wonderful job with organizing using styles, components and auto layout!
> 
> I can't promise I will copy 100% everything, but I appreciate your help. You can count this as confirmation

Thank you @tenokami ! As long as my contribution helps you, it's worth it.
I'm happy to be a part of this project ^^

**Comment by dartpain** [comment]
Appreciate you @outlivo
