### ISSUE TITLE
How to select Multi-Souce Documents?

### ISSUE THREAD

**Issue by jamsnrihk** [arc53/DocsGPT#358]
Each time only can select 1 souce documents? if i want chat with more than 2 doucments, how to select multi-souce documents?

**Comment by rc9000** [comment]
You can put multiple documents with supported extensions into a zip and then upload that. The resulting entry in the docs dropdown will consider all the files that were in the zip.

**Comment by jamsnrihk** [comment]
Great， thanks rc9000, it works.
