### ISSUE TITLE
how to enable "Sign Up" and "Sign in" button

### ISSUE THREAD

**Issue by jamsnrihk** [arc53/DocsGPT#359]
I success install and running DocsGPT, but can not find "Sign Up" "Sign In" button which showing in the demo video. How to Enable it?

**Comment by dartpain** [comment]
You will need to integrate authentification,
We used clerk.dev, its fast and easy to implement

**Comment by AnamuddinAhmad** [comment]
@dartpain sir please can you assigned me

**Comment by AnamuddinAhmad** [comment]
**i want to work on it ** can you tell me which kind of error are occur

**Comment by jamsnrihk** [comment]
> You will need to integrate authentification, We used clerk.dev, its fast and easy to implement

Thanks for your kindly advise, just wonder whether clerk.dev can handle source documents authentifications? for example, User A only can chat with file1.pdf, User B can chat with both file1.pdf and file2.pdf.

**Comment by dartpain** [comment]
You will need to make sure that in /combine request you return only his documents and swap out /local after ingest to user id, such that you can make sure only authentificated users have access

Also check out this issue https://github.com/arc53/DocsGPT/issues/369
