### ISSUE TITLE
Improving the DocsGPT Docs Home page

### ISSUE THREAD

**Issue by Smartmind12** [arc53/DocsGPT#365]
Proposed changes to make the documentation landing page user friendly:
1. Update the landing page with the video of Demo Usage
2. Rearrange the widgets in the logical sequence so that quick start and hosting are at the top instead of being in the bottom last of the sequence.
3. Improve the language of hacktoberfest and try-it demo to make it more user enticing.

![Screenshot 2023-10-02 at 11 00 42 AM](https://github.com/arc53/DocsGPT/assets/91927689/ec826078-bbaf-4362-af36-2af8674c2902)

**Comment by Aditya-Chaurasia11** [comment]
can you assign me the issue
