### ISSUE TITLE
Adding Documentation Tab in the DocsGPT landing Page

### ISSUE THREAD

**Issue by Smartmind12** [arc53/DocsGPT#367]
Proposed changes to make the DocsGPT landing page more efficient:
1. Update the landing page by adding a link to the documentation as currently it is absent

![Screenshot 2023-10-02 at 11 23 28 AM](https://github.com/arc53/DocsGPT/assets/91927689/de39a20f-d799-4da6-922c-4fbd1f33ef0d)

Kindly review the pull request that I will add (in some time) in which the above mentioned changes will be initiated upon.

**Comment by Vaibhav91one** [comment]
Can I work on this issue?

**Comment by Smartmind12** [comment]
> Can I work on this issue?

Hey @Vaibhav91one I am currrently working on this issue. Kindly take up another one to work on!
