### ISSUE TITLE
[feature]: adding dark mode

### ISSUE THREAD

**Issue by djv03** [arc53/DocsGPT#371]
what is feature:
all developer prefers dark mode except 0.0001%. So it would be very nice to have dark mode on app 

How it will be implemented:
I would provide a toggle button on top right corner to to enable as well as disable dark mode

**Comment by dartpain** [comment]
This [figma](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0-1&mode=design) outilnes dark mode design (in the bottom) 
Thank you for creating the issue @djv03 
If anyone want to contribute this would be great

**Comment by Nkiriobasi** [comment]
Please, I'll like to take this up

**Comment by dartpain** [comment]
Amazing, I assigned you to this issue

**Comment by djv03** [comment]
@dartpain I am working on this as soon as I have raised issue, can I work continue on it if @Nkiriobasi is not started yet?

**Comment by AnamuddinAhmad** [comment]
Hello sir 
               Greetings sir can you assigned me i will handle better so please could you assigned me ???

**Comment by djv03** [comment]
@AnamuddinAhmad can you explain that how would you do it

**Comment by dartpain** [comment]
I think @djv03 is currently most active in thread, if someone wants to cooperate with you @djv03 you can create a PR and link it to this issue and they can contribute.

@AnamuddinAhmad I understand you are very eager to help, please try to cooperate with other people in this PR.

**Comment by AnamuddinAhmad** [comment]
@dartpain  ok sir

**Comment by tenokami** [comment]
The design for Dark Mode is finished 

The design is finished 

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=JRSPdwDjihImrXLx-1

**Comment by djv03** [comment]
got it @tenokami, I think I need a css guy to colloborate on this issue. there is lot of styling here. what do you think @Nkiriobasi

**Comment by aryabyte21** [comment]
Hey @djv03 I am open to collaborate

**Comment by djv03** [comment]
hey @aryabyte21 Can you explain, how could you collaborate on this issue? can you explain little bit. Like what would you do and what you expect me to do?

**Comment by dartpain** [comment]
You can collaborate if a PR is created  (draft) and for example both of you have access to the same repo where it was pushed from(you can add another person), then both of you can commit to the same PR @djv03  @aryabyte21

**Comment by Vaibhav91one** [comment]
Is this issue open or closed? @dartpain

**Comment by dartpain** [comment]
@Vaibhav91one Im not sure if anyone has created a PR yet.
@djv03 @aryabyte21 Is anyone active?

**Comment by Muntasir-Zin-Alabadin** [comment]
hello, I read that you needed with CSS. What can I do for you?

**Comment by dartpain** [comment]
Basically need a dark theme as specified here https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0-1&mode=design
