### ISSUE TITLE
[feature]: Add issue and pr templates for this repository

### ISSUE THREAD

**Issue by adeyinkaezra123** [arc53/DocsGPT#380]
## Description
As I was raising issue #379, I noticed that this project doesn't have a predefined structure and template for raising issues or pull requests. 

## Implementation
I'd like to create a PR and issues ( feature requests and bug report ) templates following the guidelines specified [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) and [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

I'd start working on this as soon as this issue is approved

**Comment by dartpain** [comment]
Good, I agree! Thank you!
