### ISSUE TITLE
How to remove needless source docs

### ISSUE THREAD

**Issue by jamsnrihk** [arc53/DocsGPT#385]
If i just want to keep the source docs I uploaded, how to remove needless source docs from the list?
![cap1](https://github.com/arc53/DocsGPT/assets/134043330/91cc7b4f-94ca-4047-a5df-bb420528d751)

**Comment by dartpain** [comment]
Got to application/api/user/routes.py, then inside /api/combine route, juts delete this (lines 185 to 189)

```
if settings.VECTOR_STORE == "faiss":
        data_remote = requests.get("https://d3dg1063dc54p9.cloudfront.net/combined.json").json()
        for index in data_remote:
            index["location"] = "remote"
            data.append(index)
```
