### ISSUE TITLE
Feedback for “Home”

### ISSUE THREAD

**Issue by rS7Y** [arc53/DocsGPT#387]
Sumbit needs to be submit  :)

![rusty Google Chrome-10-03 at 20 48 55@2x](https://github.com/arc53/DocsGPT/assets/20349989/fb8758d3-33a8-4cc5-bf22-f3a2c357fbe4)

**Comment by Cioraz** [comment]
Hey, I can resolve this
Could you assign me the issue?

**Comment by dartpain** [comment]
@Cioraz please try at it, for some reason I cant replication

**Comment by sohomdatta1** [comment]
Fixed at #389
