### ISSUE TITLE
🚀 Feature: [UI] Add hover effect to the sign up and sign in button

### ISSUE THREAD

**Issue by smty2018** [arc53/DocsGPT#388]
### 🔖 Feature description

Want to add hover effect to the sign up and sign in button
![Screenshot 2023-10-03 211103](https://github.com/arc53/DocsGPT/assets/74114936/d0449f97-59f9-447f-8d38-9ce36fd3a67f)

### 🎤 Why is this feature needed ?

Enhanced user experience 

### ✌️ How do you aim to achieve this?

Define CSS for Hover Effect

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
Unfortunately this issue applies to our cloud deployment, we currently dont have authentification on open source version but are working on it, check out #369
