### ISSUE TITLE
🚀 Feature: Mock backend for previews

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#391]
### 🔖 Feature description

Currently we have vercel previews, but they dont work as there is not backend behind them, can't provide a publick openai backend thus i think it should be a mock backend

### 🎤 Why is this feature needed ?

Will help people test things in preview or when building frontend.

### ✌️ How do you aim to achieve this?

1. Identify API Endpoints:

Identify the endpoints your frontend will be communicating with.

2. Create Mock Data:

Create a JSON file with mock data that represents the structure and data your actual backend would return.

3. Using Tools like JSON Server or smth else:

There are tools like [JSON Server](https://github.com/typicode/json-server) that can help you mock REST APIs. You can install JSON Server globally and serve your mock data.

4. Integration with React:

Now React app can make requests to these endpoints, and they’ll return the mock data. Swap out the base URL from your actual Flask API to your mock server during development.

### 🔄️ Additional Information

Running actual backend without auth is a bit dangerous and costly

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Cioraz** [comment]
Hey,
I would be interested in picking this issue

**Comment by dartpain** [comment]
I assigned it to you

**Comment by Cioraz** [comment]
Tried attempting wasnt able to do much :> 
Removed my assignment

**Comment by dartpain** [comment]
No worries

**Comment by akshay11298** [comment]
Hi, if this issue is still open, can I try to work on this?

**Comment by dartpain** [comment]
Assigned

**Comment by perryHV** [comment]
Hii @dartpain  would like to work on this issue! Can you assign it to me?

**Comment by dartpain** [comment]
@perryHV Thank you for your enthusiasm, but I think @akshay11298 is working on this issue.
