### ISSUE TITLE
There should be an about page independent of the Github repository

### ISSUE THREAD

**Issue by jaredbradley243** [arc53/DocsGPT#40]
For end users who are interested in the technology but are not developers and/or do not have experience with Github. The _**about**_ link currently takes the user directly to the Github repo. 

![image](https://user-images.githubusercontent.com/107898107/217140657-436af7d5-3641-423d-b7ca-a2d815abc0cf.png)

**Comment by dartpain** [comment]
Will add it to our new UI once its ready. Its part of the mockups now
