### ISSUE TITLE
🚀 Feature: Changing icons for Discord & Github in left sidebar.

### ISSUE THREAD

**Issue by Ankit-Matth** [arc53/DocsGPT#403]
### 🔖 Feature description

On DocsGPT, in the left sidebar, icons related to Chat, About, Upgrade are provided but icons for Discord and GitHub are missing. Instead of the appropriate icons for discord and github, the arrow-up-right-from-square-icon has been used.
Actual Icons : 
![Actual-icons](https://github.com/arc53/DocsGPT/assets/146843890/8a5ba450-48fb-4b80-a4a1-7458ac485080)
Expected icons : 
![Expected-icons](https://github.com/arc53/DocsGPT/assets/146843890/de7204fe-18b3-488d-8e2a-44e946c4e9b0)

Please assign this issue to me, I want to add appropriate icons for Discord and Github in the left sidebar.

### 🎤 Why is this feature needed ?

If these icons are changed then they appear more beautiful and attractive.

### ✌️ How do you aim to achieve this?

These icons can be changed and added by using CDN link like fontawesome.com

### 🔄️ Additional Information

Please assign this issue to me, I want to add appropriate icons for Discord and Github in the left sidebar.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tenokami** [comment]
Thanks for your contribution. I think the following would be even better:

Add a dividing line to group logically similar buttons
Replace icons 
Add in text "Visit our" for both buttons to indicate that the link leads to an external site

![image](https://github.com/arc53/DocsGPT/assets/17906039/5fab3135-e303-467e-aa14-7531162ad409)

**Comment by Ankit-Matth** [comment]
Sure, please assign this issue to me so that I can fix it.

**Comment by Ankit-Matth** [comment]
Hi @dartpain, which do you think is better “Discord” or “Visit Our Discord”? I would like to add one of these after the Discord logo, please let me know what you are expecting?

**Comment by dartpain** [comment]
Please go with @tenokami  suggestion, he is our resident UI/UX person. 
Thank you!

**Comment by Ankit-Matth** [comment]
Okay
