### ISSUE TITLE
Updating Dark Mode In UX /UI And Much More

### ISSUE THREAD

**Issue by Shrit1401** [arc53/DocsGPT#405]
Following tasks were the issues found in the - figma file given in the UI
- the dark mode
- light mode advancements
- dark mode mobile

Kindly assign me the issue I'll be happy to work on it

**Comment by Shrit1401** [comment]
@dartpain hey I have made the changes can you tell me how can I send pull request for that? what has to updated for it?

**Comment by dartpain** [comment]
Create a fork and the make a pull request to this repository. Here is a good example https://github.com/firstcontributions/first-contributions

**Comment by dartpain** [comment]
You can create and just publish a figma file here in the comments or a link to it, we will check it out

**Comment by tenokami** [comment]
Dark theme design has been added to figma and is being implemented in this issue https://github.com/arc53/DocsGPT/issues/371
