### ISSUE TITLE
🐛 Bug Report: The text goes out of screen when query such as long string is typed.

### ISSUE THREAD

**Issue by Vaibhav91one** [arc53/DocsGPT#410]
### 📜 Description

When I typed a query such as long string the page got extended and there was no way to scroll.

### 👟 Reproduction steps

type "long string" as the query input. 

### 👍 Expected behavior

The answer should wrap, scrollable or something like that

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/108279746/0552baa0-4945-4329-a57a-b34f68400dc3)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Ill assing it to you then, thank you!

**Comment by Vaibhav91one** [comment]
@dartpain I have solved the issue just needed to add a Tailwind property. Should I make the PR now.

**Comment by dartpain** [comment]
Yes please, thank you!
