### ISSUE TITLE
[BUG] text overflow in chat's title

### ISSUE THREAD

**Issue by siiddhantt** [arc53/DocsGPT#411]
The text has overflown outside the box as shown below:
![image](https://github.com/arc53/DocsGPT/assets/47355538/281bf116-64e2-4fb9-afb3-911f0e3fd6bd)

If this is needed to be fixed, please assign me for this issue.

**Comment by MSaiKiran9** [comment]
Hi , i would like to contribute to this issue

**Comment by Lokendrakushwah12** [comment]
Hello @dartpain 
Can you please assign me this issue i will work on it?

**Comment by dartpain** [comment]
Oh my bad, sorry for misunderstanding

**Comment by siiddhantt** [comment]
No worries, thanks

**Comment by Lokendrakushwah12** [comment]
No prob I didn't read the last line
