### ISSUE TITLE
Improve home page text with good font and some some padding

### ISSUE THREAD

**Issue by ratishjain12** [arc53/DocsGPT#412]
### 📜 Description

@dartpain I want to improve this section 

By adding a good font and currently the text is taking full space which does not look good

![image](https://github.com/arc53/DocsGPT/assets/43003421/f8d3f3c6-80ec-4e5c-9ebc-0a51a8d2176d)

### 👟 Reproduction steps

-

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Currently we have this desing published on https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0-1&mode=design

also screenshot, so are you interested in this issue?
<img width="630" alt="Screenshot 2023-10-04 at 17 01 17" src="https://github.com/arc53/DocsGPT/assets/15183589/0baf9722-b0c3-44bf-a4a2-1d3d091795a8">

**Comment by ratishjain12** [comment]
Yes I can make it like this if you want @dartpain

**Comment by ratishjain12** [comment]
@dartpain just a question how do you wanna align the boxes for smaller screens during resize stacked in column?

**Comment by ratishjain12** [comment]
@dartpain I have created something like this
![image](https://github.com/arc53/DocsGPT/assets/43003421/ef0ad6f4-2394-4b5b-b083-b7371fa1c1e3)

**Comment by dartpain** [comment]
Good job @ratishjain12 
Just 2 things that i think need to be edited slightly:
1. Borders should be more rounded
2. On desktop overlap lines should be straight (basically try building border for the whole block on desktop vestion, and then add lines in a middle)

**Comment by ratishjain12** [comment]
So basically overlap lines should not be rounded right?

**Comment by dartpain** [comment]
Yep, exactly
