### ISSUE TITLE
Can not delete old source docs

### ISSUE THREAD

**Issue by jamsnrihk** [arc53/DocsGPT#414]
Can not delete source docs:
when i select documents from Source Docs, suppose i can delete some old uploaded documents by click X, but seems it still existing in the list after press X button.
![cap2](https://github.com/arc53/DocsGPT/assets/134043330/27905ce1-8453-4e50-9404-d1351b2b4e14)

**Comment by dartpain** [comment]
Yes, please try running git pull again, might help to fix it

**Comment by Gourav2609** [comment]
Hey @dartpain 
can i run docgpt without setting up the backend part ....i just want to correct few bugs regarding frontend ...can i do so

**Comment by dartpain** [comment]
Currently this issue is being worked on to do just this https://github.com/arc53/DocsGPT/issues/391
Otherwise you will need to set up backend, try using docker

**Comment by jamsnrihk** [comment]
> Currently this issue is being worked on to do just this #391 Otherwise you will need to set up backend, try using docker

Thanks for advise, i git clone the lastest version, seems ok now. I am using docker.
