### ISSUE TITLE
Update the UI for dropdown list for Source documentation selection to match the style of the menu for profile

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#415]
![CleanShot 2024-03-02 at 12 20 02@2x](https://github.com/arc53/DocsGPT/assets/15183589/4960de77-0005-4dcd-ab5c-98c0cb79fb90)

**Comment by Lokendrakushwah12** [comment]
I can work on it can you please assign me this issue

**Comment by dartpain** [comment]
Sorry just noticed this issue, think its resolved now.
We have some other issue open @lwooly check them out! Thank you!
