### ISSUE TITLE
🐛 Bug Report: Frontend fixes 

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#416]
### 📜 Description

The content of chat should be within the borders of the width of the input field. Currently:

![image](https://github.com/arc53/DocsGPT/assets/17906039/6200a369-0d45-431f-b443-bebeea42a4c4)

Should be: 
![image](https://github.com/arc53/DocsGPT/assets/17906039/0f1d1d35-5b06-4505-a4cf-e938456c3565)

Secondly, it would do good for readability to reduce the width of the input field as well.

### 👟 Reproduction steps

1. Go to https://docsgpt.arc53.com
2. Enter anything in the input field and click send

### 👍 Expected behavior

- [ ] The content of chat should be within the borders of the width of the input field. Currently:

![image](https://github.com/arc53/DocsGPT/assets/17906039/6200a369-0d45-431f-b443-bebeea42a4c4)

Should be: 
![image](https://github.com/arc53/DocsGPT/assets/17906039/0f1d1d35-5b06-4505-a4cf-e938456c3565)

- [ ] Secondly, it would do good for readability to reduce the width of the input field as well. I'd suggest to set max width for all the content on this screen to be 768px (in figma's measurement units). But you can use ChatGPT as reference for this

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/17906039/6200a369-0d45-431f-b443-bebeea42a4c4)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Something else

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anniebhalla10** [comment]
Could you assign this to me

**Comment by rahul0x00** [comment]
Hi @dartpain i was about to push the changes but it seems the issue got fix/resolved already, i guess someone on your team fixed it my increasing the width of the input filed which now looks very weird(attaching an image for you reference)

![image](https://github.com/arc53/DocsGPT/assets/104289350/aa7add17-d603-474f-a2eb-3a3ec1b49b86)

Maybe we should decrease the width of the input field a little bit and also keeping the chat content inside the input field
something like this:
![image](https://github.com/arc53/DocsGPT/assets/104289350/38ec3066-01f8-40d9-9c29-8e293090d49d)

**Comment by rahul0x00** [comment]
Hi @dartpain i was about to push the changes but it seems the issue got fix/resolved already, i guess someone on your team fixed it my increasing the width of the input filed which now looks very weird(attaching an image for you reference)

![image](https://github.com/arc53/DocsGPT/assets/104289350/aa7add17-d603-474f-a2eb-3a3ec1b49b86)

Maybe we should decrease the width of the input field a little bit and also keeping the chat content inside the input field
something like this:
![image](https://github.com/arc53/DocsGPT/assets/104289350/38ec3066-01f8-40d9-9c29-8e293090d49d)

**Comment by rahul0x00** [comment]
let me know if you want any new changes or any suggestions.

**Comment by tenokami** [comment]
@rahul0x00 I like the direction of your solution. But we really need the width of the input field to work as contrainst to everything in the chat, meaning no even icons, nor messages can go wider

**Comment by rahul0x00** [comment]
we could give the left div container 20% width and 70% width to to chat container and a few px for word-spacing and also decreased the input field but also keeping it as a constraint and it should look something like this

![image](https://github.com/arc53/DocsGPT/assets/104289350/781d7ff2-5898-4f3a-8d38-71cc59664cf6)

**Comment by rahul0x00** [comment]
![image](https://github.com/arc53/DocsGPT/assets/104289350/7e30c75f-8774-4a77-a169-4f27152947cb)

**Comment by tenokami** [comment]
@rahul0x00 This looks like I wanted I intended. I'd need to test this on bigger resolutions when the preview is available
