### ISSUE TITLE
🐛 Bug Report: Frontend: Chat Scrolling issue

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#418]
### 📜 Description

The content of chat looks incorrectly when scrolling appears

### 👟 Reproduction steps

1. Go to https://docsgpt.arc53.com/
2. Enter enough messages in the input field and send them to enable scrolling of the screen

### 👍 Expected behavior

Dissapear behind a white rectangle right above the input field. And the dynamic action button should float above it on the fixed distance from the input field 

![image](https://github.com/arc53/DocsGPT/assets/17906039/98cbdd82-ff4b-4500-80f7-6ef852f7c536)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/17906039/993eba55-150e-459c-92d6-7cff5c923da1)

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khurramrizvi** [comment]
Assign this to me

**Comment by Anniebhalla10** [comment]
Could you please assign this to me for hacktoberfest

**Comment by perryHV** [comment]
Hii @tenokami  would like to work on this issue! Can you assign it to me? thank you

**Comment by tenokami** [comment]
@perryHV 

@khurramrizvi  Is already assigned to it
