### ISSUE TITLE
🚀 Feature: Welcome screen update

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#419]
### 🔖 Feature description

Add a block with 3 paragraphs, icons, wrapped in a border

![image](https://github.com/arc53/DocsGPT/assets/17906039/73219b0d-73c8-458c-b760-cb95baa16298)

![image](https://github.com/arc53/DocsGPT/assets/17906039/a67309d0-c974-4cff-a1de-8c5dbb882ac1)

Figma: https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=dl0y8pTiva7YoU6z-1

### 🎤 Why is this feature needed ?

The introductory screen serves as the user's initial point of contact with the chatbot, ensuring a smooth and informative start to the interaction while enhancing engagement and user satisfaction

### ✌️ How do you aim to achieve this?

The welcome paragraphs combine effective content and design to provide a user-friendly introduction, ensuring that users are informed, engaged, and motivated to continue their interaction with the chatbot or application

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by rahul0x00** [comment]
H i would like to work on this issue, can you assign it to me?

**Comment by Lokendrakushwah12** [comment]
Alr @dartpain you can assign this

**Comment by dartpain** [comment]
Sorry @rahul0x00 @Lokendrakushwah12 asked about similar issue, but the one that wasnt a separate.

**Comment by rahul0x00** [comment]
No problem at all!

**Comment by tenokami** [comment]
@Lokendrakushwah12 I have updated the design and responsive behaviour for this in this issue https://github.com/arc53/DocsGPT/issues/497

**Comment by Lokendrakushwah12** [comment]
Got it, will make the necessary changes

**Comment by Lokendrakushwah12** [comment]
Hello @dartpain @tenokami 

## My Changes
Desktop view
![image](https://github.com/arc53/DocsGPT/assets/118094744/b3e45b3f-1d7e-4c52-bc0c-9f380e898282)
Mobile view
![image](https://github.com/arc53/DocsGPT/assets/118094744/f63fc7de-653b-44cd-b7f7-a072bc1ea80e)

I have created PR so please check it #656

**Comment by tenokami** [comment]
@Lokendrakushwah12 Thanks. Looks good to me

**Comment by Lokendrakushwah12** [comment]
@tenokami Please review the PR #646
