### ISSUE TITLE
🐛 Bug Report: "Sources" feature doesn't look as intended

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#421]
### 📜 Description

Make the "sources" functionality look like it is in figma

### 👟 Reproduction steps

1. Go to https://docsgpt.arc53.com
2. Type any message, send it
3. Under the response there are clickable buttons 

### 👍 Expected behavior

Basically, they should look and behave like this. If the response is too short, still increase the width of the background to cover its sources.

![image](https://github.com/arc53/DocsGPT/assets/17906039/a0eff767-15fe-4d71-808d-6dccad5556e8)

Look for "sources" frame in [figma ](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=tMBoGNoGdeHF8dmI-1)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/17906039/8cf250ac-d6ad-47df-a167-270b6c1842c1)

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Assinged, thank you, @adityagupta19

**Comment by akritimangal** [comment]
HiI would like to work on this issue! Can you assign it to me?

**Comment by rajvinder-kaur** [comment]
assign it to me

**Comment by adityagupta19** [comment]
Yes am working on it but I am having issue with open ai rate limit is there a way to get around it?

**Comment by dartpain** [comment]
@adityagupta19  It might take some time for them to chill about the limits

**Comment by perryHV** [comment]
Hii @tenokami  would like to work on this issue! Can you assign it to me?

**Comment by dartpain** [comment]
I think it was already fixed in #427 
Can you check on this @tenokami

**Comment by tenokami** [comment]
@adityagupta19 

1. Corners for the blue block should have the same radius as the messages have
2. The max width of the blue block should always be limited by the actual width of the message it is attached to 
![image](https://github.com/arc53/DocsGPT/assets/17906039/7f0783fa-d250-4ef3-8443-96067b81c95d)

3. The title Source: Guides should be bigger, black. Aligned with the left edge of the text box below it. And the name of the document should be semi-bold

![image](https://github.com/arc53/DocsGPT/assets/17906039/e2f99a7a-c027-4332-afe7-69ad60aa2569)


Thank you for your work!
