### ISSUE TITLE
🐛 Bug Report: Overflowing text when user inputs a long string without spaces

### ISSUE THREAD

**Issue by ArnabBCA** [arc53/DocsGPT#426]
### 📜 Description

When user inputs a long string without spaces it overflows

### 👟 Reproduction steps

Enter a long string without spaces 
![lonh string](https://github.com/arc53/DocsGPT/assets/113178195/924ce81c-6767-4192-b228-b7d31bb83fd3)

### 👍 Expected behavior

It should break works according to parent container size.

### 👎 Actual Behavior with Screenshots

It should not overflow when user inputs a long string without spaces

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by staticGuru** [comment]
@ArnabBCA 
It's an excellent approach to contribute.

**Comment by dartpain** [comment]
Closed in #427
