### ISSUE TITLE
Problems with embedding and replying 

### ISSUE THREAD

**Issue by Cometzyc** [arc53/DocsGPT#428]
embedding：
This will cause the training progress bar to remain at 0.
<img width="500" alt="50566ffe9890174f6d639ee1f587ee8" src="https://github.com/arc53/DocsGPT/assets/113234824/03d1ce85-ec6a-4382-a714-4637ddce8bca">

replying：
This will result in a reply of "something went wrong".
<img width="1000" alt="5313ad8aef3aeccc5c781024aff1b43" src="https://github.com/arc53/DocsGPT/assets/113234824/3c4e1239-0d54-43b8-8c3e-3f0dbdb6e60b">

**Comment by dartpain** [comment]
Can you expand more on the issue, what did you do for it to happen, what do you have in the .env file?

**Comment by Cometzyc** [comment]
I made two changes before docker compose. 
One was to write: API_KEY=sk-***
VITE_API_STREAMING=true
SELF_HOSTED_MODEL=false  in .env. 
The second was to put VITE_API_HOST to my own ubuntu server ip in docker-compose.yaml

**Comment by dartpain** [comment]
Seems like a directory map issue, should be solved
