### ISSUE TITLE
🐛 Bug Report: DocsGpt result bullets are not aligned properly 

### ISSUE THREAD

**Issue by saurabhbakolia** [arc53/DocsGPT#430]
### 📜 Description

DocsGpt result bullets are not aligned properly 
![image](https://github.com/arc53/DocsGPT/assets/78996216/38fcff2a-06d3-4f4c-96b0-28396ecee7a0)

### 👟 Reproduction steps

1. I just asked about a question 
2. I found this issue in DocsChat result. 
3. All the bullet points are not aligned

### 👍 Expected behavior

Need to fix the styling of the Chat Result element. And that change will fix this issue. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/78996216/1ae41567-5e1d-4aea-8c47-1092448b2ffb)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

Yes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parteek2813** [comment]
Hi, this seems a easy fix. Can i work on this?

**Comment by dartpain** [comment]
Absolutely!

**Comment by dartpain** [comment]
I think @saurabhbakolia  is on it already

**Comment by saurabhbakolia** [comment]
Yes, @dartpain  please assign this issue to someone else. I am getting some issue.

**Comment by dartpain** [comment]
Ok, removed your assignement, thank you for trying

**Comment by harshkasat** [comment]
Could you please assign me to a task?

**Comment by heysagnik** [comment]
I want to work on this issue @dartpain

**Comment by amrahs02** [comment]
can you assign this issue to me?

**Comment by amrahs02** [comment]
Could you please delegate this problem to someone else? I'm encountering difficulties with it.

**Comment by dartpain** [comment]
Yep, no worries, thank you for trying it!

**Comment by adityagupta19** [comment]
I want to work on this issue. Can you assign me?

**Comment by tenokami** [comment]
@adityagupta19 Assigned to you

**Comment by heysagnik** [comment]
@tenokami what is this behaviour, I requested first to work on this and you assigned him .This is not fair .

No don't assign me now .

**Comment by adityagupta19** [comment]
> @tenokami what is this behaviour, I requested first to work on this and you assigned him .This is not fair .
> 
> No don't assign me now .

I think this is because you commented on the issue before they assigned the last person so they were not sure if you would still like to work on this. But no worries man you can have it. I am unassigning myself.

**Comment by dartpain** [comment]
@heysagnik Sorry if it didnt match your expectations. I can see how you have felt ignored. We are experiencing a lot of activity and sometimes make quick decisions and mistakes too. I should have assigned the issue to you some time before, but sometimes I miss relevant context... 

Please confirm if you would still be interested, otherwise someone else can pick it up.
