### ISSUE TITLE
🚀 Feature: Dark Mode Design in Figma

### ISSUE THREAD

**Issue by bhumitbedse** [arc53/DocsGPT#433]
### 🔖 Feature description

Design the Mockups for Dark Mode In Figma.

### 🎤 Why is this feature needed ?

To give a better User Experience to end users.

### ✌️ How do you aim to achieve this?

Design Mockups in Figma and after will implement dark mode using Figma Designs

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
Sorry its an issue @tenokami is handling

**Comment by parteek2813** [comment]
Okay .... No worries!

**Comment by tenokami** [comment]
Design is completed

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=JRSPdwDjihImrXLx-1
