### ISSUE TITLE
🚀 Feature: sidebar update

### ISSUE THREAD

**Issue by byt3h3ad** [arc53/DocsGPT#440]
### 🔖 Feature description

![image](https://github.com/arc53/DocsGPT/assets/26319721/745f7be1-72f4-4fcb-93a6-e83a05d14920)

update the sidebar according to the figma design.

### 🎤 Why is this feature needed ?

update the website according to the design requirements.

### ✌️ How do you aim to achieve this?

refactor the existing component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by byt3h3ad** [comment]
![image](https://github.com/arc53/DocsGPT/assets/26319721/adea9b62-3dd3-4f85-8f77-8ee2ddf7b6a6)

https://docsgpt.arc53.com/ still shows this.

**Comment by dartpain** [comment]
No need, look the way its supposed
