### ISSUE TITLE
🐛 Bug Report: Different chat tabs overlaps.

### ISSUE THREAD

**Issue by adityagupta19** [arc53/DocsGPT#444]
### 📜 Description

There is a bug in the left side tabs section when you open multiple chats and a chat has large text.

### 👟 Reproduction steps

1. Ask a question.
2. Ask a question on different tab.
3. the text of different tabs overlap.

### 👍 Expected behavior

The tabs should have proper margin between them and text limiting.

### 👎 Actual Behavior with Screenshots

![bug](https://github.com/arc53/DocsGPT/assets/87007373/d147902d-5d50-4d76-a121-2c388a718412)

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akshay11298** [comment]
Hi, if this is still open, can I work on this?

**Comment by dartpain** [comment]
@adityagupta19  are you working on the issue, or should @akshay11298  pick it up?

**Comment by adityagupta19** [comment]
I am working on it.
