### ISSUE TITLE
🚀 Feature: Want to add left navigation bar acccording to figma UI

### ISSUE THREAD

**Issue by Sapna127** [arc53/DocsGPT#450]
### 🔖 Feature description

I want to make the left navigation according to the one provided in figma UI.. Will work on its frontend..

### 🎤 Why is this feature needed ?

The current UI is not up to the mark with the one that is updated in figma file..
The improvement in left navbar can provide more interactive experience to the user.

### ✌️ How do you aim to achieve this?

I'll be using react & vite and write the code for the same.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by staticGuru** [comment]
Hi
I want to work with this feature.
@dartpain I would be pleased if you assign this task to me.

**Comment by dartpain** [comment]
Sorry, can you please be more explicit on what things you want to fix here? @Sapna127

**Comment by Sapna127** [comment]
> Sorry, can you please be more explicit on what things you want to fix here? @Sapna127

yes sure.. 
the current ui of left nav looks like this 
<img width="236" alt="image" src="https://github.com/arc53/DocsGPT/assets/91309280/06b0221a-42bd-44b8-b139-b04033d8bd04">
and according to your figma design it should look like this 
<img width="121" alt="image" src="https://github.com/arc53/DocsGPT/assets/91309280/440d9ef3-190f-439d-a20f-8ee13470ed2c">

I want to code this design.. 
Thank you!

**Comment by tenokami** [comment]
@Sapna127  Keep in mind that you chose the dark theme design screenshot as refernce. We have both light and dark theme. Just making sure we are not replacing the colors here to dark

**Comment by Sa24miksha** [comment]
can you assign this to me? @dartpain
