### ISSUE TITLE
🐛 Bug Report: Text overflowing in source selection section.

### ISSUE THREAD

**Issue by staticGuru** [arc53/DocsGPT#452]
### 📜 Description

There is a bug in the left-side source selection section when you select the files the texts are overflowing.

### 👟 Reproduction steps

1. Go to the conversation page
2. Select the source files from the dropdown.
3. Selected texts overflow and break the design, if, the source file name is long.

### 👍 Expected behavior

The selected source file name should be a text ellipsis.

### 👎 Actual Behavior with Screenshots

![Text overflow issue](https://github.com/arc53/DocsGPT/assets/79417096/898fbf81-99eb-4eee-81e1-15ee5ac6f90e)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aman44444** [comment]
i want to work on this issue can you please assign this to me?

**Comment by staticGuru** [comment]
I am already working on this issue.

**Comment by dartpain** [comment]
@staticGuru guru indicated that he wants to work on this issue, thus its assigned to him.

Thank you for your interest @aman44444
