### ISSUE TITLE
🐛 Bug Report: Adding code of conduct file link in Readme file !

### ISSUE THREAD

**Issue by mohitd404** [arc53/DocsGPT#453]
### 📜 Description

code of conduct will be clearly visible if it would be in readme.md please assign this issue to me ! @larinam @

### 👟 Reproduction steps

Adding code of conduct file link in Readme file !

### 👍 Expected behavior

code of conduct file is not present in readme.md

### 👎 Actual Behavior with Screenshots

none

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohitd404** [comment]
@larinam @jbampton please assign this issue to me!

**Comment by alienishi** [comment]
@larinam @jbampton if this issue is still unassigned please do assign it to me

**Comment by mohit-dhote** [comment]
@alienishi I'm working on it !

**Comment by mohitd404** [comment]
@alienishi I'm working on it !!

**Comment by mohitd404** [comment]
@dartpain I have Fixed the bug kindly Review It !! Thank you so much!
