### ISSUE TITLE
Incorrect usage of "store" in README

### ISSUE THREAD

**Issue by vedant-z** [arc53/DocsGPT#457]
The expected behaviour should be:

"... and storage for other libraries"

![IMG_20231006_152212.jpg](https://github.com/arc53/DocsGPT/assets/93431609/b4827e0c-5b45-4550-b664-89848ba26231)

**Comment by alienishi** [comment]
@larinam @jbampton Please assign this issue to me 
I am new to open source and want to resolve this issue :)

**Comment by staticGuru** [comment]
@alienishi Is it typo error?

**Comment by alienishi** [comment]
@dartpain @larinam @jbampton 
I have resolved the issue 
Please review my PR :)
