### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#459]
### 📜 Description

the UI of hero.tsx does not match figma

### 👟 Reproduction steps

Go to the main page

### 👍 Expected behavior

![photo_2023-10-06 12 38 07](https://github.com/arc53/DocsGPT/assets/15183589/89a4eb81-a955-42bc-aed4-98217c37a4a7)

### 👎 Actual Behavior with Screenshots

<img width="952" alt="Screenshot 2023-10-06 at 12 13 58" src="https://github.com/arc53/DocsGPT/assets/15183589/b5aacbb1-d1b6-45cc-a788-4aafe2b4f9ad">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 📃 Provide any additional context for the Bug.

Please check out the font and the box sizes and text size

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tenokami** [comment]
Also, 

1. the border radius should be changed to the way it is in figma
2. Make sure than titles are less bold, more like in figma
3. try to keep line height like it is in figma

**Comment by staticGuru** [comment]
Hi @dartpain @tenokami 
I want to work on this issue.
I would be pleased if you assign this issue to me.

**Comment by staticGuru** [comment]
Thanks @tenokami
