### ISSUE TITLE
Create a railway deployments guide

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#461]
Just a guide on how to deploy docsgpt with railway

**Comment by QuantuM410** [comment]
I would like to work on it. Please assign this issue to me!

**Comment by iamakhileshmishra** [comment]
I would like to contribute on this please assign this to me & add Hacktoberfest tag in this

**Comment by QuantuM410** [comment]
@dartpain Hey ! I have been occupied with some work these days and I dont think I'll be able to work on this issue as for now. Please reassign to @iamakhileshmishra :)

**Comment by dartpain** [comment]
@iamakhileshmishra  assigned to you!
No worries @QuantuM410 , thank you!

**Comment by iamakhileshmishra** [comment]
Thanks for assigning this to me I would be very delightful to work on this

**Comment by iamakhileshmishra** [comment]
@dartpain Could you just confirm that you are talking about this https://railway.app/ railway platform for deployment.

**Comment by dartpain** [comment]
Hi @iamakhileshmishra yep thats what i meant, thank you for confirming with me

**Comment by harshita1611** [comment]
Hey, I would like yo work on this issue, can you please assign it to me

**Comment by iamakhileshmishra** [comment]
Hey @harshita1611 I am working on this issue kindly ask for another issue.

**Comment by iamakhileshmishra** [comment]
@dartpain Could you please check my commit and revert back to me if there is any issue with that so that I could rectify if required. Please consider it under Hacktoberfest Contribution.
Thanking You 
Akhilesh Kumar Mishra :)
