### ISSUE TITLE
🚀 Feature: run with CPU using llama_cpp guide

### ISSUE THREAD

**Issue by DawoodTouseef** [arc53/DocsGPT#466]
### 🔖 Feature description

Add a feature where we run in CPU using llama_cpp

### 🎤 Why is this feature needed ?

This feature need because we can run this Doc GPT in cpu without using any GPU 

### ✌️ How do you aim to achieve this?

It will aim achieve the model to run on CPU 

### 🔄️ Additional Information

I tried to run this model in CPU it overload the cpu would get crash so I use above model and converted into gguf model the i run the model in cpu 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
I think we already have this implemented. 
if you run .setup.sh and choose option 1
https://github.com/arc53/DocsGPT/blob/main/setup.sh

But I think we need to provide more info in guides on how to set it up this way, in the /docs/pages

**Comment by mnickrogers** [comment]
Looks like a straightforward docs update. I'm happy to take this one!
