### ISSUE TITLE
🚀 Feature: Tests with unittest

### ISSUE THREAD

**Issue by jonascarvalh** [arc53/DocsGPT#470]
### 🔖 Feature description

Starting to test with unittest can bring more contributors and keep the project more secure. Many people who use django, like me, like to use tests with unittest which is similar to the django testing structure.

### 🎤 Why is this feature needed ?

As unittest is standard in python, there is no need to install the dependency.

### ✌️ How do you aim to achieve this?

Creating some personalized and useful tests for the application.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
We are already using pytest
Also, pytest has a more user-friendly way to write tests compared to unittest, and it provides detailed output on test failures,
