### ISSUE TITLE
🚀 Feature: New prompt 

### ISSUE THREAD

**Issue by ayan-joshi** [arc53/DocsGPT#471]
### 🔖 Feature description

I would like to add a new prompt in the prompt folder
It would be named custom_prompt

### 🎤 Why is this feature needed ?

 This file provides a starting point for creating prompts for various tasks. Let me know if you'd like any modifications or additional content in the file!

### ✌️ How do you aim to achieve this?

I have knowledge regarding to this I can add this feature 

### 🔄️ Additional Information

Please assign this issue to me under hacktoberfest label I will work on it 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
What kind of prompt do you want to add? Maybe you can add more material to this guide
https://nextra-docsgpt-git-fork-5h0ov-patch-1-arc53.vercel.app/Guides/Customising-prompts

**Comment by ayan-joshi** [comment]
> What kind of prompt do you want to add? Maybe you can add more material to this guide https://nextra-docsgpt-git-fork-5h0ov-patch-1-arc53.vercel.app/Guides/Customising-prompts

Yess I'm looking to add the prompt in the same folder only the prompt will be named custom_prompt.txt file 
And we can use this file to create prompts for various tasks or experiments. Below are some examples of prompts.

**Comment by ayan-joshi** [comment]
> > What kind of prompt do you want to add? Maybe you can add more material to this guide https://nextra-docsgpt-git-fork-5h0ov-patch-1-arc53.vercel.app/Guides/Customising-prompts
> 
> Yess I'm looking to add the prompt in the same folder only the prompt will be named custom_prompt.txt file And we can use this file to create prompts for various tasks or experiments. Below are some examples of prompts.

@dartpain please assign it to me SO I can start the work

**Comment by ayan-joshi** [comment]
@dartpain can u add hacktoberfest label
