### ISSUE TITLE
🐛 Bug Report: Question is hidden under the question input box

### ISSUE THREAD

**Issue by staticGuru** [arc53/DocsGPT#474]
### 📜 Description

There is a bug in the chat conversation section. when they ask the question in the chat section, the asked question is hidden under the question input box.

### 👟 Reproduction steps

1. Go to the chat conversation section
2. Enter your questions in the chat input box and click to send icon button.
3. You can able to saw the issues, we can't able to saw the posted question until the response comes.

### 👍 Expected behavior

Questions should be visible and they should be rendered in the last chat conversation scroll section.

### 👎 Actual Behavior with Screenshots

![Questions Hidden](https://github.com/arc53/DocsGPT/assets/79417096/0458d1e1-fb31-4fbf-9372-75c9f86727c7)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by staticGuru** [comment]
Hi @dartpain 
I want to work on this issue.
I would be pleased, if, you assign this issue to me.

**Comment by dartpain** [comment]
I think @tenokami  Highlighted a similar issue https://github.com/arc53/DocsGPT/issues/418
But there was not much progress, so you can commit.

**Comment by staticGuru** [comment]
Thanks @dartpain
