### ISSUE TITLE
🐛 Bug Report: About page content is getting cropped in mobile view

### ISSUE THREAD

**Issue by akshitarora921** [arc53/DocsGPT#481]
### 📜 Description

Header is overlapping the about page title in mobile view
<img width="425" alt="Screenshot 2023-10-07 at 2 59 29 PM" src="https://github.com/arc53/DocsGPT/assets/11087313/3584e418-c22d-465b-84ed-1e402fb45fc8">

### 👟 Reproduction steps

1 visit https://docsgpt.arc53.com/about in mobile.

### 👍 Expected behavior

There should be some gap between header and main content.

### 👎 Actual Behavior with Screenshots

Gap between header and main content.
<img width="429" alt="Screenshot 2023-10-07 at 3 05 15 PM" src="https://github.com/arc53/DocsGPT/assets/11087313/3599120f-2ce2-46a0-b5be-94a36163c9b1">

### 💻 Operating system

Something else

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinparmar** [comment]
I want to work on this issue please Assign to me

**Comment by PrerakMathur20** [comment]
Hey, I have vast experience with Frontend Technologies and can fix this bug in no time, can I work on this?

**Comment by dartpain** [comment]
Thank you for enthusiasm
@akshitarora921  Has submitted this issue and indicated that he is willing to work on it, so this issue thiers.
