### ISSUE TITLE
🚀 Feature: In Mobile view, Sidebar should auto-close on click of any menu-item

### ISSUE THREAD

**Issue by akshitarora921** [arc53/DocsGPT#482]
### 🔖 Feature description

Sidebar should auto-close on click of any menu-item.

### 🎤 Why is this feature needed ?

Better UX.

### ✌️ How do you aim to achieve this?

Will call sidebar close function on click of sidebar Item

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by just-ctrlC-ctrlV** [comment]
@akshitarora921 can u assign this issue to me?

**Comment by just-ctrlC-ctrlV** [comment]
@dartpain can u assign this issue to me?

**Comment by dartpain** [comment]
@tenokami  should it auto close? I personally would prefer for the sidebar to be there, unless im short on space

**Comment by tenokami** [comment]
@dartpain I agree wit you here. For sidebar to close whenever the user clicks anything in it: chat, reset key, about, etc would be unexpected behaviour and cause frustration

**Comment by akshitarora921** [comment]
@dartpain @tenokami Just want to add a reference video https://github.com/arc53/DocsGPT/assets/11087313/ec29ca15-53b3-448f-bb9e-e1b86a862c64
