### ISSUE TITLE
🚀 Feature: Error state 

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#484]
### 🔖 Feature description

Design for error state. 

### 🎤 Why is this feature needed ?

To clearly display error when it occurs

### ✌️ How do you aim to achieve this?

By placing an error message in a visible place

Light theme:
![image](https://github.com/arc53/DocsGPT/assets/17906039/01f02d79-bf90-47df-9a1e-3ecfc64c1591)

Dark theme:
![image](https://github.com/arc53/DocsGPT/assets/17906039/afcbf921-1249-4328-a23c-5859a6f48d95)

Figma: https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=QOxybJLGCkPMZxMp-1

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by staticGuru** [comment]
Hi @tenokami 
I would like to work on the issues.
Can you assign this issue to me?

**Comment by tenokami** [comment]
@staticGuru Thanks!

**Comment by staticGuru** [comment]
Yeah sure, will working on it
