### ISSUE TITLE
🚀 Feature: Change color for action buttons.

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#485]
### 🔖 Feature description

All buttons and elements that are currently blue should be changed to color 7D54D1 to match figma design  (excluding the sources feature)

Right now (example from only one place): 
![image](https://github.com/arc53/DocsGPT/assets/17906039/5ede330e-3ccd-45ef-907a-06497e1ddec1)

Should be (in all places including loaders and, buttons, progress bar): 
![image](https://github.com/arc53/DocsGPT/assets/17906039/e694c6e4-66e2-4c6c-b7f8-08168cbd6822)

### 🎤 Why is this feature needed ?

Branding, consistency of design across all application

### ✌️ How do you aim to achieve this?

Updating the color to watch the brand color

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Ankit-Matth** [comment]
Hello @tenokami, I want to work on it, please assign it to me.
