### ISSUE TITLE
🚀 Feature: Add Offline Functionality with useOfflineMode Hook

### ISSUE THREAD

**Issue by vaibhavpnimkar** [arc53/DocsGPT#487]
### 🔖 Feature description

I propose adding offline functionality to the project using the useOfflineMode Hook to enhance user experience and improve application robustness.

### 🎤 Why is this feature needed ?

Improved user experience: Users can continue using the application even when their internet connection is unstable or lost.
Increased application reliability: Offline functionality ensures the application remains functional, reducing downtime due to connectivity issues.
Better branding and consistency: Ensuring that the application maintains a consistent design, including offline states, is essential for branding and user satisfaction.

### ✌️ How do you aim to achieve this?

In order to realize offline functionality I will make use of a custom hook called useOfflineMode with offline functionality will be achieved through localforage library. This library allows the browser’s IndexedDB store the user information for some time, and it can be retrieved once the user comes back online. It enables us to craft a strong offline experience whereby important user data is cached locally only being uploaded onto the server when the Internet connection has been reconnected. Integration of localforage into the OfflineMode hook makes it possible for us to effectively store data locally, which allows users to continuously use the platform without loss of information in case they are not accessing the internet when using it.

### 🔄️ Additional Information

Firstly, when the offline features were implemented through the Local Storage library initial, I had problems in handling asynchronous operations appropriately. Upon realising how this works I settled on a better solution involving the use of the localforage library given its strong offline data management capabilities.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by staticGuru** [comment]
@vaibhavpnimkar This is a nice idea. I appreciate you.
But, 
How to handle the AI request and response in the Offline mode?  explain

**Comment by vaibhavpnimkar** [comment]
It does not address off-line response generation first and foremost. Contrary, it makes available the previous chats and files in case of loss of network connection for users. It enables users to go back and review prior interactions and content on offline, which enhances users’ capability of handling and reviewing available document despite no internet connection.

**Comment by staticGuru** [comment]
Okay, From your point of view,
In Offline-mode, Do we prevent user input in the chat sections?

**Comment by vaibhavpnimkar** [comment]
In my opinion, this is a reasonable approach for taking user’s input in an offline mode while using the application. This may be done through the introduction of a request queue that will keep track of user requests that are made in offline mode. In online mode, once the application regains an internet connection, these requests will be queued up and sent to the API by themselves. This is how; it guarantees that the users never experience a hitch when using the chat feature. But again preventing user input in the chat sections can also be a viable approach

**Comment by staticGuru** [comment]
In general, query request queuing is not a viable approach. Becoz, It will hit more requests once the user comes online from offline mode. It will affect the user experience. So, I think, we should prevent the user input in offline mode.
Does it make sense?
@vaibhavpnimkar @dartpain

**Comment by vaibhavpnimkar** [comment]
Yes, I was also thinking along those lines. However, I believe it would be beneficial for us to explore and discuss all available alternatives before making a decision.  And I totally agree to your statement of preventing  the user input in offline mode.

**Comment by vaibhavpnimkar** [comment]
I'm ready to start working on it. Could it be assigned to me? Additionally, I'd like to confirm if the you are interested in adding this feature to the project. @staticGuru

**Comment by dartpain** [comment]
So you are proposing to add an offline mode essentialy. 

My only concern is that from users perspective it will not offer anything useful. Things will simply not works as most of the work gets done on the backend not on the clients browser. Unless user wants to reload and read his existing conversation.

From a users perspective what kind of useful interactions they may have in the offliine mode? @vaibhavpnimkar

**Comment by vaibhavpnimkar** [comment]
While I suggest the addition of an offline mode for enhanced accessibility. I understand the reasons you pose why this might be less helpful from a user’s perspective. Yes, a lot of back-end interactions with clients cannot occur in offline mode.

The main use for users of offline mode is to have an opportunity to read saved up materials and messages on which no internet is required. This can be helpful in cases, when a user has to look up previous conversations or documents.

While this is true, it’s just as important to consider the drawbacks of offline mode balance them with its advantages. Another approach involves assuming that there is not much the user can do in offline mode and accordingly concentrate on offering clear indications to user about what can be done offline. We should also research on any specific use cases or interactions that we may have in improving or optimizing and taking them offline.

Finally; it must match what a user expects and need. We should also aim for compromises when balancing online access versus a smooth flow of the user experience”.
