### ISSUE TITLE
🚀 Feature: A copy button is needed for the bot response

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#488]
### 🔖 Feature description

I will add a copy button on the right top of response, such that its visible on hover
As a user it feels like something is missing in the app :(
Please assign me this issue, need to work on this feature.
![image](https://github.com/arc53/DocsGPT/assets/96079232/246840f7-39e5-40c7-8887-69b2c324a17f)

### 🎤 Why is this feature needed ?

**DocsGPT** is an app which writes docs, selecting long responses is inconvenient for _lazy developers_ like me!

### ✌️ How do you aim to achieve this?

I will chose an icon for the copy button, add functionality using the copy-to-clipboard module and then add some hover effects to make the UI cool

### 🔄️ Additional Information

Also  navigator.clipboard.writeText(text) can be used instead of importing a copy-to-clipboard module

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ManishMadan2882** [comment]
I can work on this issue, _can you please assign_ .

**Comment by tenokami** [comment]
Thanks! Do you want to choose the icon and hover. Or ill do it and add to the figma and then implemet it?

**Comment by ManishMadan2882** [comment]
Are you designing the button right now?

**Comment by tenokami** [comment]
@tenokami I can. It will take just a couple minutes

**Comment by tenokami** [comment]
@ManishMadan2882 Done. If you like it, you can work with it

![image](https://github.com/arc53/DocsGPT/assets/17906039/260d912d-fdaa-4ac4-8d81-d5b7f31c1dfd)
![image](https://github.com/arc53/DocsGPT/assets/17906039/300a8e8d-5651-449f-80e9-2e091bb20b9e)
