### ISSUE TITLE
🚀 Feature: Chat room rename functionality

### ISSUE THREAD

**Issue by staticGuru** [arc53/DocsGPT#495]
### 🔖 Feature description

Presently, the inability to edit chat room names, which are automatically generated by the bot, can lead to difficulties in comprehending the chat room's content and recalling previous interactions with the bot. Therefore, implementing the chat room renaming feature has the potential to rectify these issues and improve overall clarity and understanding.

### 🎤 Why is this feature needed ?

The chat room renaming feature significantly enhances the user experience by providing a valuable means of contextualizing conversations within their respective chat rooms.

### ✌️ How do you aim to achieve this?

**Frontend:**
 - I will add the small edit icon on the right side of the chat room name.
  
**Backend:**
- I will add the new routes for the chat room rename, then, add the query changes in the respective routes.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by staticGuru** [comment]
Hi @dartpain 
I want to work on this feature.
Kindly, assign this feature to me.

**Comment by dartpain** [comment]
@tenokami can you support us with UI please?
Good idea
Thank you!

**Comment by tenokami** [comment]
UI is ready @staticGuru 

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=lSO86IRqK81Zuzpz-1
![image](https://github.com/arc53/DocsGPT/assets/17906039/c320a89b-a60b-4dfc-ad0e-0adbd47b9024)
![image](https://github.com/arc53/DocsGPT/assets/17906039/3fdb507a-a844-4dab-b087-c90494a3c2d9)

**Comment by staticGuru** [comment]
Thanks @tenokami .
You're UI design, exactly what I thought. 
I will work on it.
