### ISSUE TITLE
🚀 Feature: Update + change responsive behavior

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#497]
### 🔖 Feature description

Each block now has a separate border at all times
https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=rYYLIvdZwHWKD2zo-1

![image](https://github.com/arc53/DocsGPT/assets/17906039/b5e8ebcf-789a-403a-9751-621d699cc5a2)

![image](https://github.com/arc53/DocsGPT/assets/17906039/44e90c6e-0987-444c-8468-136fbf86952c)

On smaller screen, the blocks stay in the same line. And buttons for horizontal scroll will appear
![image](https://github.com/arc53/DocsGPT/assets/17906039/8722fa2a-8874-481a-9406-9885900fe610)
![image](https://github.com/arc53/DocsGPT/assets/17906039/0320f4f0-155a-4523-b2c4-11f85510c277)

Use bard as reference

![image](https://github.com/arc53/DocsGPT/assets/17906039/982e1948-ebd5-4ab2-9ca0-c5ea58a336f1)

### 🎤 Why is this feature needed ?

UI/UX enhancement 

### ✌️ How do you aim to achieve this?

Updating UI/UX

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by SanchitMahajan236** [comment]
Can you please assign this issue to me.
I am willing to contribute.

**Comment by tenokami** [comment]
@SanchitMahajan236 Please make sure that even though I added only right arrow, the left arrow should also appear. So I assume u will just take the right arrow and flip it

**Comment by SanchitMahajan236** [comment]
Ok, I will keep that in mind

**Comment by kesselly4099** [comment]
for the Ux?

**Comment by Kritika30032002** [comment]
May I contribute to this?

**Comment by tenokami** [comment]
@Kritika30032002 

@SanchitMahajan236 is already assigned to it. You can offer to collaborate

**Comment by Kritika30032002** [comment]
Okay @tenokami 


@SanchitMahajan236  Can we collaborate on this?
You can let me know on which part I can work !

**Comment by SanchitMahajan236** [comment]
Ya sure, would love to collaborate ☺️

**Comment by Kritika30032002** [comment]
Great! @SanchitMahajan236  You can let me know on which part I can work !

**Comment by Kritika30032002** [comment]
@tenokami You can also assign this to me

**Comment by codeslayed** [comment]
can i contirbute on this i know frontend

**Comment by Kritika30032002** [comment]
@SanchitMahajan236  Are you working on this?
If yes the tell me the component on which you are working?


@tenokami  It has been 4 days but there is no reply from @SanchitMahajan236 .
Can u plz tell what i can do now? Can I start working?

**Comment by SanchitMahajan236** [comment]
You can work on this issue @Kritika30032002, I will unassign myself from this issue as I am too entangled with some other stuff and sorry I wasn't able to reply earlier.

**Comment by dartpain** [comment]
UI is changed now according to new designs.
