### ISSUE TITLE
🚀 Feature: Like/dislike button behavior

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#500]
### 🔖 Feature description

The button like or dislike once clicked, should behave exactly like in ChatGPT. Meaning it should stay visible and not hide

### 🎤 Why is this feature needed ?

To make it clear that the feedback has been provided for this response

### ✌️ How do you aim to achieve this?

By making the clicked button stay visible after it was clicked

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Ankit-Matth** [comment]
Please assign this issue to me.

**Comment by manish7017** [comment]
Can you please assign this issue to me? I would like to work on it.

**Comment by tenokami** [comment]
assigned this to you @Ankit-Matth

**Comment by Ankit-Matth** [comment]
Thanks @tenokami for assigning this issue to me.

**Comment by Ankit-Matth** [comment]
Hi @tenokami, I think this issue should be closed as it is similar to issue #516 and will also be resolved.
