### ISSUE TITLE
[API Documentation] Add backlink to Vector Stores and Fix Grammar

### ISSUE THREAD

**Issue by beKoool** [arc53/DocsGPT#508]
In the API Docs, in [`/api/delete_old` section](https://docs.docsgpt.co.uk/Developing/API-docs#apidelete_old), there is written "vectorstores" but this documentation does not give info on what are Vector Stores. So adding a backlink to a wiki like [this](https://python.langchain.com/docs/modules/data_connection/vectorstores/) may help the user to understand what are Vector Stores. 

![image](https://github.com/arc53/DocsGPT/assets/76424367/a63cbb02-4548-450c-9ded-8cbe91645601)

And, In the [`/api/task_status` section](https://docs.docsgpt.co.uk/Developing/API-docs#apitask_status), there is a grammatical error. Fixing it would help the user understand the docs more easily. 👍

![image](https://github.com/arc53/DocsGPT/assets/76424367/a885df8f-f918-49b1-9545-61e27611e427)

**Comment by beKoool** [comment]
Hey @dartpain, I would like to work on this. Can you assign it to me?

**Comment by manish7017** [comment]
Can you please assign this issue to me? I would like to work on it.

**Comment by dartpain** [comment]
I suggest @beKoool we create a separate page in our wiki to talk about vector stores and how they work in our application. This would be more useful to a user.

Thank you

**Comment by beKoool** [comment]
Hey @dartpain, I will surely create a new page on wiki talking about Vector Stores.
