### ISSUE TITLE
🚀 Feature: Round corners 

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#514]
### 🔖 Feature description

Round the corners on "source documentation" and "enter message input field" to the maximum

![image](https://github.com/arc53/DocsGPT/assets/17906039/b95edbf4-f6ca-4530-ada0-9cb9f115137e)
![image](https://github.com/arc53/DocsGPT/assets/17906039/38d9b6c3-b784-4e78-a117-68b962d46b78)

### 🎤 Why is this feature needed ?

Consistency with the rest of design/style

### ✌️ How do you aim to achieve this?

by keep the corner radius consistent across elements

### 🔄️ Additional Information

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=bb8MENOYPjbHRqwx-1

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by SoumyadiptoPal** [comment]
I want to work on this issue
