### ISSUE TITLE
🚀 Feature: Revamp icon effects

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#516]
### 🔖 Feature description

Update how icons look when they are hovered and clicked.
The copy button when clicked should change to the checkmark for 3 seconds and then change back to copy icon

![image](https://github.com/arc53/DocsGPT/assets/17906039/5715c1f8-4934-457a-b643-11424acda8e8)

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=bb8MENOYPjbHRqwx-1

### 🎤 Why is this feature needed ?

Currently it doesn't look/feel good

### ✌️ How do you aim to achieve this?

By updating the UI/UX

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by manish7017** [comment]
Can you please assign this issue to me? I would like to work on it.

**Comment by dartpain** [comment]
Please make sure you have the latest version that already has a copy button that got merged here
#503

**Comment by Ankit-Matth** [comment]
Hey @manish7017, are you still working on this issue?

This issue was assigned to you 2 weeks ago but no PR has been created by you yet.

If you can't fix it, please let me know, I'm willing to fix this issue.

**Comment by manish7017** [comment]
Hey @Ankit-Matth, I'm still working on the issue but don't have enough time to test the fixes before making any PR. 

If you would like to contribute to this issue then go ahead.

**Comment by Ankit-Matth** [comment]
Hey @tenokami, I raised an PR #672 .
Please review it and merge it.
