### ISSUE TITLE
🚀 Feature:  Link with download to source document

### ISSUE THREAD

**Issue by cforce** [arc53/DocsGPT#517]
### 🔖 Feature description

Currently the Source info does not provide a link to the original document used to locate the answer. 

### 🎤 Why is this feature needed ?

This allows the user to better understand where the answer has been build from give a chance  to verify and get more trust .

### ✌️ How do you aim to achieve this?

If the document is uploaded it shall be stored and kept for linking as download below the answer. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by manish7017** [comment]
Can you please assign this issue to me? I would like to work on it.

**Comment by manish7017** [comment]
I would like to work on it.

**Comment by dartpain** [comment]
Hmmm, I agree that its cool to allow users to download the document, but I think we will have to come back to this issue later as currently we need to plan where user will download it from in the UI. And if its practical to store original document.
