### ISSUE TITLE
🚀 Feature: Side Menu Bar Should be Slidable. 

### ISSUE THREAD

**Issue by adcs1** [arc53/DocsGPT#521]
### 🔖 Feature description

The Side Menu Bar Should be  Slidable, the user can reduce its size by using a mouse.

### 🎤 Why is this feature needed ?

The Side Menu Bar Should be  Slideable, the user can reduce its size by using a mouse. The Text Behind the Menu Bar is Overalpping

### ✌️ How do you aim to achieve this?

The Side Menu Bar Should be Slidable.

### 🔄️ Additional Information

![image](https://github.com/arc53/DocsGPT/assets/88266244/d9aba661-4631-406d-98b3-d7f4aee7b3ed)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by hirentimbadiya** [comment]
I'd love to fix this issue. can anyone assign me ?

**Comment by tenokami** [comment]
Apologies @adcs1, there was an overlap. 
This issue is unnecesary. The same issue is already being fixed here https://github.com/arc53/DocsGPT/issues/527.
