### ISSUE TITLE
🐛 Bug Report: Content is not fully visible and will also add up the hamburger icon for managing the state.

### ISSUE THREAD

**Issue by abhay-raj19** [arc53/DocsGPT#527]
### 📜 Description

while i am opening the default deployed page,

there is the issue with the background text that gets hidden in the left side at 100% resolution and want to align it so that it gets fully visible to the users and also helps in better understanding with the project .

<img width="970" alt="image" src="https://github.com/arc53/DocsGPT/assets/96302417/e385214b-fbbe-4afd-ba56-5bdcf4e190d4">

will add up the hamburger also for managing and merging the sidebar into left side .

### 👟 Reproduction steps

1.Will add up the hamburger icon for merging the sidebar.

2.Will also align up the text in some more lines so that it gets wide and fully visible.

### 👍 Expected behavior

it should align up the text and will make text looks more good .

### 👎 Actual Behavior with Screenshots

after aligning up the text it should be looking like .

<img width="960" alt="image" src="https://github.com/arc53/DocsGPT/assets/96302417/f2d34ab2-fa8c-429a-8808-6af8abd4c88b">
 
and will also add up the hamburger for collasping up the navbar to the left side .

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhay-raj19** [comment]
@larinam pls assign me the issuse so that I start working on it and raise up the PR as soon as possible.

**Comment by just-ctrlC-ctrlV** [comment]
@dartpain If this bug needs fixing can u assign me this?

**Comment by tenokami** [comment]
@dartpain As I see, the test environment already has an arrpw icon to close the sidebar, which transforms into the hamburger.

**Comment by abhay-raj19** [comment]
@tenokami okay sure sure so i will update the text style that causes , half text hide behind the sidebar and will upgrade into its good version.
