### ISSUE TITLE
🚀 Feature: Does it support Nought If not then addition of it.

### ISSUE THREAD

**Issue by rajveer43** [arc53/DocsGPT#528]
### 🔖 Feature description

Nougat: Neural Optical Understanding for Academic Documents
Scientific knowledge is predominantly stored in books and scientific journals, often in the form of PDFs
However, the PDF format leads to a loss of semantic information, particularly for mathematical expressions), a Visual Transformer model that performs an Optical Character Recognition (OCR) task for processing scientific documents into a markup language, and demonstrate the effectiveness of our model on a new dataset of scientific documents. The proposed approach offers a promising solution to enhance the accessibility of scientific knowledge in the digital age, by bridging the gap between human-readable documents and machine-readable text. We release the models and code to accelerate future work on scientific text recognition.

### 🎤 Why is this feature needed ?

Nought has the potential to be a valuable tool for DocsGPT users

### ✌️ How do you aim to achieve this?

https://github.com/facebookresearch/nougat

### 🔄️ Additional Information

-

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by staticGuru** [comment]
Hi @rajveer43,
Thank you for submitting your feature request. Could you please provide detailed guidance on how these requested features can be effectively integrated into our system? We would greatly appreciate your insights and explanations.

**Comment by dartpain** [comment]
I think if we integrate it has to link to the file inside worker.py, ingest_worker.
1. check if pdf has any text inside
2. If no text parse it save as txt
3. Delete uploaded pdf
4. give it as txt into simple document reader.
