### ISSUE TITLE
🚀 Feature: Add pop up on "chat" if user is not registered/connected

### ISSUE THREAD

**Issue by DoTheBestToGetTheBest** [arc53/DocsGPT#531]
### 🔖 Feature description

Currently when clicking to "chat" without being registered or connected, nothing happen, so now we will need a pop up to say we need to be online or create account

### 🎤 Why is this feature needed ?

It is needed because it's better to handle this

### ✌️ How do you aim to achieve this?

Just adding pop up when clicking the chat button is okey

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by QuantuM410** [comment]
I am willing to work on this issue, please assign it to me !

**Comment by Ayush-Vish** [comment]
@DoTheBestToGetTheBest  @QuantuM410  Please assign me this issue .

**Comment by t-trafer** [comment]
i would love to work on this

**Comment by dartpain** [comment]
@DoTheBestToGetTheBest I currently dont see how this is going to be implemented in the open source version without auth. 

Otherwise for connection, are you suggesting we check if backend is up?
