### ISSUE TITLE
🐛 Bug Report: Remove the extra spaces

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#533]
### 📜 Description

Extra spaces need to be removed

### 👟 Reproduction steps

1. Go to https://docs-gpt-git-main-arc53.vercel.app
2. Type and send a message

### 👍 Expected behavior

![image](https://github.com/arc53/DocsGPT/assets/17906039/644df02f-94ee-4733-8fc1-e830939619d7)

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=h3DmOfFMiEpQ88fa-1

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/17906039/3e1fa871-e69f-4bd1-a7c5-d43d69c145d7)

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

No

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HeetVekariya** [comment]
I would like to work on this issue, can you please assign it to me.

**Comment by t-trafer** [comment]
Hi, i can work on this issue..

**Comment by tenokami** [comment]
@HeetVekariya Thank you!

**Comment by HeetVekariya** [comment]
Hey @tenokami while running :
```
#!/bin/bash

source .env

if [[ -n "$OPENAI_API_BASE" ]] && [[ -n "$OPENAI_API_VERSION" ]] && [[ -n "$AZURE_DEPLOYMENT_NAME" ]] && [[ -n "$AZURE_EMBEDDINGS_DEPLOYMENT_NAME" ]]; then
  echo "Running Azure Configuration"
  docker-compose -f docker-compose-azure.yaml build && docker-compose -f docker-compose-azure.yaml up
else
  echo "Running Plain Configuration"
  docker-compose build && docker-compose up
fi
```

- it gives error that docker-compose command not found.
- So i just changed it to ```docker compose``` and it worked, so is it correct ?

**Comment by HeetVekariya** [comment]
- I have completed docker set up.
- frontend
![image](https://github.com/arc53/DocsGPT/assets/91054457/2419d07a-6bb7-4106-bff5-0ea7764b7f67)

-backend
![image](https://github.com/arc53/DocsGPT/assets/91054457/ffe80024-0011-4b0d-93a2-866b244ad63b)

- But i am not able to get the responce:
![image](https://github.com/arc53/DocsGPT/assets/91054457/d3986814-6202-4b2f-9953-b3b3632df482)


- What should i do now ?

**Comment by tenokami** [comment]
@HeetVekariya, @dartpain will respond to as soon as he can

**Comment by dartpain** [comment]
Yep, docker compose build && docker compose up should be good @HeetVekariya

**Comment by HeetVekariya** [comment]
> - @tenokami  I have completed docker set up.
> - frontend
> ![image](https://github.com/arc53/DocsGPT/assets/91054457/2419d07a-6bb7-4106-bff5-0ea7764b7f67)
> 
> -backend
> ![image](https://github.com/arc53/DocsGPT/assets/91054457/ffe80024-0011-4b0d-93a2-866b244ad63b)
> 
> - But i am not able to get the responce:
> ![image](https://github.com/arc53/DocsGPT/assets/91054457/d3986814-6202-4b2f-9953-b3b3632df482)
> 
> - Also i get this in the backend:
> ![image](https://github.com/arc53/DocsGPT/assets/91054457/c14fd9a1-1dfc-4c42-a772-690a0ecb9f39)
> 
> 
> - What should i do now ?
> 

Thanks for that, but what should I do with this ?

**Comment by tenokami** [comment]
@alex is the tech guy. I'm the UI/UX guy

**Comment by dartpain** [comment]
So did it work for you here?

> So i just changed it to docker compose build && docker compose up and it worked, so is it correct ?

**Comment by HeetVekariya** [comment]
I think we should connect on discord

**Comment by HeetVekariya** [comment]
@tenokami As you know it's been two days the issue assigned to me, but still not able to figure out why i am getting the "Something went wrong, Please try again" in the response.
- So can i just do direct PR for this issue, i have made the solution given below, Please check it.

![image](https://github.com/arc53/DocsGPT/assets/91054457/4d3847ea-2fb1-46d9-a909-2e92af55dac9)

- I think that the extra spaces in the starting may get removed if we just trim the reponse before displaying it.
- Please let me if my solution is valid or any changes needed

**Comment by dartpain** [comment]
try the ./setup.sh script to launch docsgpt please
Thank you @HeetVekariya

**Comment by HeetVekariya** [comment]
> try the ./setup.sh script to launch docsgpt please
> Thank you @HeetVekariya 

- I have submitted the PR, so we can see check in preview also. 
- Do this submitted PR will be accepted ?

**Comment by dartpain** [comment]
I think i checked it and left a comment, please correct me if i missed something
Thank you @HeetVekariya

**Comment by dartpain** [comment]
Yes, please fill it in, thank you!
