### ISSUE TITLE
🐛 Bug Report: Like Dislike button in the message response should be at the top of the message bubble

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#536]
## It makes it difficult for the user to locate the Like Dislike buttons
![image](https://github.com/arc53/DocsGPT/assets/96079232/5ba92e8c-7f1d-41aa-b116-ea880ec36372)
### 👟 Reproduction steps

I will place the buttons together at the top of the response message

### 👍 Expected behavior

The buttons associated with a particular message should be expected to be present at the top of the message, to make it more suitable for messages comprising long documentations.

### 👎 Actual Behavior with Screenshots

![mobile (1)](https://github.com/arc53/DocsGPT/assets/96079232/174bdd72-7cc1-45a0-bfaa-9fdff8629ac9)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

API_KEY
LLM_NAME
VITE_API_STREAMING

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManishMadan2882** [comment]
I can work on this issue

**Comment by tenokami** [comment]
That's a great one Thanks! @ManishMadan2882

**Comment by dartpain** [comment]
Very neat bug report to @ManishMadan2882
