### ISSUE TITLE
🐛 Bug Report: When file isn't selected website should disable train button

### ISSUE THREAD

**Issue by MSaiKiran9** [arc53/DocsGPT#539]
### 📜 Description

In the DocsGpt website when we want to train from a new documentation it's training even if no file is selected and it's not completing the training task and staying in loading state for long time .

### 👟 Reproduction steps

select upload button in docsgpt 0.1.0 and train without choosing files 
<img width="384" alt="image" src="https://github.com/arc53/DocsGPT/assets/116418856/29c1e9df-abfa-486c-acf9-3fa51fc5b528">
and then it's not completing this task  like exiting and staying in this state entirely -> 
<img width="222" alt="image" src="https://github.com/arc53/DocsGPT/assets/116418856/5dec905a-f00f-4122-8d44-345c77eb0a61">

### 👍 Expected behavior

I think it should not allow to train if the document isn't provided . I'm new to this repository so correct me if i'm wrong :)

### 👎 Actual Behavior with Screenshots

It's not exiting "training in progress" in console also it's not updating .

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kritika30032002** [comment]
Assign me this

**Comment by MSaiKiran9** [comment]
@Kritika30032002 Glad that you also found this relevant but as I described above I want to contribute to this issue if it's reviewed as relevant

**Comment by dartpain** [comment]
Good issue!

**Comment by Kritika30032002** [comment]
@MSaiKiran9 If you want to collaborate on this issue, you can let me know.

**Comment by huicewang** [comment]
![1709963265985](https://github.com/arc53/DocsGPT/assets/19237481/d07a79b3-26b7-47ac-8ac8-c827009ce04b)
