### ISSUE TITLE
When ingesting data, ingest using chunks.

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#54]
Make sure if there are to many vectors process can be restarted

Include progress monitoring

**Comment by jwulf** [comment]
This is a good idea. Even without rate limiting, over capacity can cause an ingestion to fail part-way. You get charged for the ingestion up to that point, but you cannot resume it, you have to restart the entire thing.

**Comment by nehatkkhan786** [comment]
hello there I am also getting the same error. 
` # Split Into Chunks
        text_splitter = CharacterTextSplitter(
            separator="\n",
            chunk_size = 600,
            chunk_overlap = 200,
            length_function = len,
        )
        chunks = text_splitter.split_text(text)`
        
        I converted the Wikipedia page of Salman Khan to pdf and getting warning on warning saying 
        Created a chunk of size 3417, which is longer than the specified 600

**Comment by adityamahakalihsc1** [comment]
Why is this issue closed, I can not find a possible solution.
