### ISSUE TITLE
🐛 Bug Report: Home page not responsive

### ISSUE THREAD

**Issue by Kritika30032002** [arc53/DocsGPT#540]
### 📜 Description

Home page is not responsive 
content is getting hide

![image](https://github.com/arc53/DocsGPT/assets/83400697/32ee537c-0459-49a2-a9e1-b0a8b5f31f07)

### 👟 Reproduction steps

1. open the hosted link for the website on different devices

### 👍 Expected behavior

Content should be clearly visible

### 👎 Actual Behavior with Screenshots

Content is not visible 
![image](https://github.com/arc53/DocsGPT/assets/83400697/e17b4fb5-20ad-4976-98a8-2e3003604d29)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
This is a demo page, it does not reflect latest version. Please check out quickstart https://github.com/arc53/DocsGPT#quickstart and review that.

Thank you!
