### ISSUE TITLE
🐛 Bug Report: Home page's git hub link isn't visible in mobile's landscape view 

### ISSUE THREAD

**Issue by MSaiKiran9** [arc53/DocsGPT#541]
### 📜 Description

when we open the webpage in landscape mode in a mobile the github link isn't visible 
<img width="552" alt="image" src="https://github.com/arc53/DocsGPT/assets/116418856/83355294-4d21-4d51-bb74-c2439a940310">

### 👟 Reproduction steps

open the page in any browser and select mobile view and choose landscape view 

### 👍 Expected behavior

it should not appeach in search bar as it's below 

### 👎 Actual Behavior with Screenshots

<img width="522" alt="image" src="https://github.com/arc53/DocsGPT/assets/116418856/9cdb859c-066c-4659-8cf1-cb660ba466fb">

Here i set z-index of the link to 10 so it's actually getting into search bar as seen above 

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Edge,Chrome,Mozilla

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kritika30032002** [comment]
Hey @MSaiKiran9  , Can I work on this issue as you are assigned with one other issue also?

**Comment by MSaiKiran9** [comment]
@Kritika30032002 Sorry but I really need some prs for hacktober fest . I just started out . If I need any help I'll let you know

**Comment by Kritika30032002** [comment]
Okay @MSaiKiran9  No Problem. Go ahead

**Comment by MSaiKiran9** [comment]
@dartpain I can't see above git-hub icon in the local clone .Clone's UI is different . Is this issue still relevant ? If yes , in which repo should i work in ?

**Comment by dartpain** [comment]
Please check on the quickstart version or the newest open source version. There is no github badge.
Thank you
