### ISSUE TITLE
🚀 Feature: Settings menu UI

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#547]
### 🔖 Feature description

Basically a new page that will be a settings menu.

First we need to create UI, then we will add frontend and backend.

A new page will have 3 sub menus:
1. Prompt: this menu will have a form where you can select active prompt (will have pre built options, like creative and strict) and at the bottom of a for will be another form. Where you can create your prompt in one window and give it a name and save it.
- Should see active prompt
- Should be able to add new prompt by entering prompt name and text
- Should be able to edit old user added prompts

<img width="721" alt="Screenshot 2023-10-10 at 12 04 20" src="https://github.com/arc53/DocsGPT/assets/15183589/74ae4c4d-e017-4aa6-b8c1-1d904cf72395">

2. Source docs/ vectorstore
- Should be able to view all in a table with name date and location. 
- Should be able to delete
- Button to add new with the existing upload modal
<img width="556" alt="Screenshot 2023-10-10 at 12 14 10" src="https://github.com/arc53/DocsGPT/assets/15183589/0517fc18-c5e6-4fd5-ad70-8d628dcbd495">

3. Widgets: page where users can generate widget code and view intructions. 
- Should be able to select source doc
- Should be able to seletc method (react, html)
- Should be able to view intructions and code snippet with a copy button
- Small preview screenshot of how it will look like

<img width="545" alt="Screenshot 2023-10-10 at 12 14 59" src="https://github.com/arc53/DocsGPT/assets/15183589/f9ee2634-ec0d-46fc-b76c-a99ba9ae1a66">

Warning:
The screenshots are there just for guidance, in no ways it indicates how things should work or look, its just for functionality

### 🎤 Why is this feature needed ?

Users can edit prompts, have a better way to review their source docs and help to implement widgets.
Also very useful for future

### ✌️ How do you aim to achieve this?

Firts we need a figma UI

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by beKoool** [comment]
Hey, can you assign this to me?

**Comment by beKoool** [comment]
I have done PR and it is #647 . Hope, it is accepted and reviewed by the maintainers.
