### ISSUE TITLE
🚀 Feature: Uploads from other sources UI

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#548]
### 🔖 Feature description

Basically allows users to uload things from other sources (remote)
Could be a dropdown where users select source (from file, url, Github, sitemap ...) List will keep growing
And in that from there will be different fields depending on choice.

<img width="547" alt="Screenshot 2023-10-10 at 12 23 38" src="https://github.com/arc53/DocsGPT/assets/15183589/879c1621-e355-4e60-85e7-ff7fbb14b8a3">

### 🎤 Why is this feature needed ?

We are adding remote sources

### ✌️ How do you aim to achieve this?

Figma UI

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by beKoool** [comment]
Hey! Can I work on this issue? 🚀

**Comment by beKoool** [comment]
I have submitted a PR to fix this issue https://github.com/arc53/DocsGPT/pull/725 . Hope, it is accepted and reviewed by the maintainers. 🚀
