### ISSUE TITLE
🐛 Bug Report: Fix Dialog box overlapping for gpt version selection (important)

### ISSUE THREAD

**Issue by harshita-2003** [arc53/DocsGPT#552]
### 📜 Description

BUG : When click to select gpt version the dialog box appearing overlaps the written section and unable to scroll down to that level 

### 👟 Reproduction steps

go to default (gpt 3.5) and click it

### 👍 Expected behavior

![Screenshot 2023-10-11 023819](https://github.com/arc53/DocsGPT/assets/119532943/38a7f116-34ba-413e-9cbe-d5c980fff0f0)

**It will not overlap and will be able to scroll down smoothly**

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-11 024513](https://github.com/arc53/DocsGPT/assets/119532943/2028ac70-28e6-4a6d-8a5c-eb24a8dcb763)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshita-2003** [comment]
@larinam @dartpain can you assign me this issue . I would love to work on this

**Comment by tenokami** [comment]
@dartpain Is there a need to keep this dropdown, duplicating the one in the sidebar? 

Current design:

![image](https://github.com/arc53/DocsGPT/assets/17906039/1f8a5cec-fc7f-419d-8364-891360b4df8c)

**Comment by dartpain** [comment]
This issue is for deployed demo, we will soon add model selection dropdown for open source version, my only concern here is that it will be more complicated to configure, thus once we have settings meny we can start thinking on how we can make this work
