### ISSUE TITLE
🐛 Bug Report: failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize

### ISSUE THREAD

**Issue by mehdimo** [arc53/DocsGPT#555]
### 📜 Description

Get this error when run ./setup.sh in venv based on python 3.11. 
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnode%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
ERROR: Service 'frontend' failed to build : Build failed
```

### 👟 Reproduction steps

1. Create venv based on python 3.11 -> commented lines from here: [link](https://github.com/arc53/DocsGPT/blob/e91b30f4c762e01347cc708846cdf687ce4deeff/setup.sh#L33)
2. Run ./setup.sh

### 👍 Expected behavior

Run the docker images and serve UI.

### 👎 Actual Behavior with Screenshots

<img width="879" alt="Screenshot 2023-10-10 at 6 27 38 PM" src="https://github.com/arc53/DocsGPT/assets/5948831/49fe8bec-a492-43e3-9082-3a1a1899b1da">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chitti-g-k** [comment]
https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0

This might help

**Comment by mehdimo** [comment]
restarting my docker desktop resolved the issue.
