### ISSUE TITLE
🐛 Bug Report: Add Icons For Discord And Github Link

### ISSUE THREAD

**Issue by viditagrawal56** [arc53/DocsGPT#559]
### 📜 Description

Currently on the sidebar, the discord and and github links do not have an icon.
However, the UI/UX can be improved by adding icons for both the links.

### 👟 Reproduction steps

1. Go to https://docsgpt.arc53.com/
2. See the links on the left panel

### 👍 Expected behavior

Both the Discord and Github links have their respective icons before the links

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-10 231856](https://github.com/arc53/DocsGPT/assets/52532308/f5f41284-27d0-47ba-9522-ff913a127fe1)
As seen in the above image, the about link has an icon but the discord and github links do not have any icons.

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by viditagrawal56** [comment]
Please assign me this issue

**Comment by tenokami** [comment]
Thank you for taking your time making this issue.

We have already added the icons but there are still on the text environment

**Comment by tenokami** [comment]
I'll close this as duplicate @dartpain
