### ISSUE TITLE
🐛 Bug Report: Is it possible to configure each port in a single configuration file?

### ISSUE THREAD

**Issue by dinghuanghao** [arc53/DocsGPT#560]
### 📜 Description

Is it possible to configure each port in a single configuration file? I am deploying on a remote server and I need to reconfigure the ports, but I found that I have to modify many files.

### 👟 Reproduction steps

I need config so many file to change a port
```
	修改：     application/app.py
	修改：     docker-compose-local.yaml
	修改：     docker-compose.yaml
	修改：     frontend/Dockerfile
	修改：     frontend/vite.config.ts
```

### 👍 Expected behavior

juse one line configuration.

### 👎 Actual Behavior with Screenshots

.

### 💻 Operating system

Linux

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Yes, your docker-compose files port will become the exsit port. There are few different docker-compose files for different set ups.
