### ISSUE TITLE
Lack of space between input box and "continue" button

### ISSUE THREAD

**Issue by vedant-z** [arc53/DocsGPT#564]
It doesn't look good with button and text box touching without any space.

I am willing to make a PR.

@dartpain Please assign me this.

![IMG_20231011_153644.jpg](https://github.com/arc53/DocsGPT/assets/93431609/4dcab55b-c2e0-4dd6-b399-9e20fd1f690f)

**Comment by ydv-ankit** [comment]
i want to work onn this

**Comment by Binitha12** [comment]
i would like to work on this.please assign this to me.
#hackoctoberfest

**Comment by dartpain** [comment]
Sorry this is not the open source version of docsgpt, this is the cloud version. Furthermore this UI is done by clerk
