### ISSUE TITLE
🚀 Feature:  Is there any papers or docs to describe how DocsGPT work in detail

### ISSUE THREAD

**Issue by ydove0324** [arc53/DocsGPT#567]
### 🔖 Feature description

I am really intersting in some technical detail, but have trouble just reading the code to understand it

### 🎤 Why is this feature needed ?

It can help many other people to contribute to this repo

### ✌️ How do you aim to achieve this?

search for some wikis

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by CherutoSharleen** [comment]
I'd love to work on this with you if approved, also if you aren't willing to submit a PR, how will your changes or docs be accessed? @ydove0324

**Comment by dartpain** [comment]
Looks like @ydove0324 didnt indicate that they want to work on this PR.
@CherutoSharleen You can pick up this issue and write a short explanation in the docs/pages if you want
I think it could be quite useful!
Please tell me if you want to work on it so i can assign you

**Comment by CBID2** [comment]
> Looks like @ydove0324 didnt indicate that they want to work on this PR.
> @CherutoSharleen You can pick up this issue and write a short explanation in the docs/pages if you want
> I think it could be quite useful!
> Please tell me if you want to work on it so i can assign you

Hi @dartpain. It’s been a while since Cheruto has expressed interest, so can I be assigned to this issue? I’ll respond quickly as possible.

**Comment by dartpain** [comment]
Assigned to @CBID2 , thank you!

**Comment by CBID2** [comment]
> Assigned to @CBID2 , thank you!

Hi @dartpain. I unassigned myself to this issue. I'm not too familiar with the app, so I would be able to write the guide effectively.
