### ISSUE TITLE
🚀 Feature: adds contributing guideline

### ISSUE THREAD

**Issue by ankur0904** [arc53/DocsGPT#578]
### 🔖 Feature description

The current contribution guidelines in the repository need enhancement and clarification. This issue is opened to discuss, propose, and implement improvements to our contribution guidelines to make it easier for potential contributors to understand how to participate in this project effectively.

### 🎤 Why is this feature needed ?

The feature is needed to improve the clarity and accessibility of our contribution guidelines, making it easier for both new and experienced contributors to participate effectively in the project.

### ✌️ How do you aim to achieve this?

I do make changes in the `CONTRIBUTION.md` file.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dartpain** [comment]
Good PR, thank you!
