### ISSUE TITLE
🐛 Bug Report: Fix features on hero

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#581]
### 📜 Description

Looks good on firefox, but on safari and chrome 
<img width="943" alt="Screenshot 2023-10-12 at 11 18 46" src="https://github.com/arc53/DocsGPT/assets/15183589/0730a852-8e25-4574-b3a8-b10f7f0a4f98">

Also when viewport is shrunk it starts to breaks
<img width="704" alt="Screenshot 2023-10-12 at 11 20 05" src="https://github.com/arc53/DocsGPT/assets/15183589/d83346ca-8fdb-4475-992f-869f85c93556">

<img width="476" alt="Screenshot 2023-10-12 at 11 19 03" src="https://github.com/arc53/DocsGPT/assets/15183589/d4dc1333-46e8-4906-aaa1-3ab3e85c6895">

### 👟 Reproduction steps

Launch
open main page
Shrik browser or open in chrome/safari

### 👍 Expected behavior

Should look like this 
<img width="963" alt="Screenshot 2023-10-12 at 11 28 33" src="https://github.com/arc53/DocsGPT/assets/15183589/2f97ac12-0c5d-4a31-8898-cdcb827f1951">

or 
<img width="365" alt="Screenshot 2023-10-12 at 11 29 06" src="https://github.com/arc53/DocsGPT/assets/15183589/52b43088-1880-4bf8-a390-e0dd8b36b693">

### 👎 Actual Behavior with Screenshots

<img width="704" alt="Screenshot 2023-10-12 at 11 20 05" src="https://github.com/arc53/DocsGPT/assets/15183589/b95abe27-cd51-4943-8cd8-d8d8f3c47da3">

<img width="476" alt="Screenshot 2023-10-12 at 11 19 03" src="https://github.com/arc53/DocsGPT/assets/15183589/4869ca8d-9edd-4bef-9c37-b40d9b1231e9">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome, Safari

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

No

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayushnangia** [comment]
Hey can i work on this issue?

**Comment by Rajiv-paul** [comment]
Can I get assign to this issue please

**Comment by AD11-web** [comment]
@dartpain can you assign me> so I can work on this issue...

**Comment by codeslayed** [comment]
@dartpain can you assign this to me so i can work on this

**Comment by akash0708** [comment]
Hello @dartpain , this looks like a nice issue, would love to work on it!

**Comment by dartpain** [comment]
Hey @ayushnangia how is the progress?
Thank you!

**Comment by lakshmi930** [comment]
@dartpain can I pick this up? I have a fix ready to be raised PR if there's no else actively working on it.

**Comment by dartpain** [comment]
@lambagayatri08 @Rajiv-paul @AD11-web @codeslayed @akash0708 anyone wants to pick this issue up?

**Comment by akash0708** [comment]
Yes @dartpain I would love to!
