### ISSUE TITLE
🐛 Bug Report: Sidebar glitch on Desktop

### ISSUE THREAD

**Issue by mozi47** [arc53/DocsGPT#582]
### 📜 Description

When toggling sidebar on desktop there is miss-alignment transition.

when sidebar is transition to left-most, the sidebar move down a bit and slide to left and same when slide from left to right, the sidebar move from top to current position.
  

### 👟 Reproduction steps

1. Visit https://docsgpt.arc53.com/
2. Toggle the sidebar

### 👍 Expected behavior

Not smooth left and right transition

### 👎 Actual Behavior with Screenshots

Transition to left:
move a bit to bottom and Slide to left

Transition to right:
move from top and Slide to right.
![image](https://github.com/arc53/DocsGPT/assets/20722868/df6e6d7b-7001-468b-a5d4-b8afb62e060d)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shivam200446** [comment]
hey, I want to work on it. Assign me!

**Comment by dartpain** [comment]
@mozi47 indicated that they want to work on the issue when it was created.
I appreciate the energy @shivam200446
