### ISSUE TITLE
🚀 Feature: enhancement in the style of the home page and text must be centralised .

### ISSUE THREAD

**Issue by abhay-raj19** [arc53/DocsGPT#583]
### 🔖 Feature description

Want to change up the font style and make the font eye catchy and can also introduce  up the auto completing letters for the main webapplication so that it looks more pretty.

<img width="801" alt="image" src="https://github.com/arc53/DocsGPT/assets/96302417/f1c65148-10fa-4d81-803b-8e3a016e3dcd">

will enhance it up 

### 🎤 Why is this feature needed ?

right now it is all stable text if we gets some auto-completion text on the dashboard it might catch the eyes of  the users and make it more look better.

### ✌️ How do you aim to achieve this?

by intoducing the auto text completing the docsGPT will grow mote and will be used by individual .

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by shivam200446** [comment]
hey, I want to work on it. Assign me!

**Comment by abhay-raj19** [comment]
@larinam pls assign me me this i will we converting it into a better version as explained above.

**Comment by dartpain** [comment]
@tenokami Please check this out, what do you think?

**Comment by tenokami** [comment]
@abhay-raj19 Could you please describe what you want to do in my details (I mean the visual changes, not technical detail)

I guess we should start with changes to the design in figma?
