### ISSUE TITLE
Problems with the execution of the./run with docker composite. sh command

### ISSUE THREAD

**Issue by XYTriste** [arc53/DocsGPT#584]
When I execute this command:
`./run with docker composite. sh`
The following error occurred:
`Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5173 -> 0.0.0.0:0: listen tcp 0.0.0.0:5173: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`  
I confirmed through the `netstat - no | findstr 5173` command that the port is not occupied, and then through the `netsh interface ipv4 show excludedportrange protocol=tcp` command, I found that my computer prohibits these ports from using the TCP protocol within the range of 5141-5240.
So I tried using the `netsh interface ipv4 delete excludedportrange protocol=tcp startport=5141 numberofports=100` command to make these ports available to use the TCP protocol. I executed this command with administrator privileges, but still received a prompt for 'Access denied'.
May I ask what I should do now to enable it to be deployed locally? I'm not familiar with Docker..., so I don't know how to modify the port number 5173...

**Comment by XYTriste** [comment]
In addition, I added the inbound rule according to the instructions in the guide, but still received the same error prompt..

**Comment by dartpain** [comment]
Unfrotunately you will have to solve this issue with your system or use different container ports in your docker-compose.yaml file. Try changing ports there to something that ok
