### ISSUE TITLE
🐛 Bug Report: typo on docs page

### ISSUE THREAD

**Issue by barkhaaroraa** [arc53/DocsGPT#585]
### 📜 Description

the spelling of submit is incorrect

### 👟 Reproduction steps

go to https://docs.docsgpt.co.uk/ and click on need help with docsgpt

### 👍 Expected behavior

spelling error should be corrected

### 👎 Actual Behavior with Screenshots

<img width="363" alt="image" src="https://github.com/arc53/DocsGPT/assets/115429121/89d56b03-00ac-40bb-9448-8fc5f370ec5c">

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rajiv-paul** [comment]
please assign me with this issue

**Comment by sohomdatta1** [comment]
Fixed at #387
