### ISSUE TITLE
🐛 Bug Report: Wrong render of lists in conversation

### ISSUE THREAD

**Issue by krabbi** [arc53/DocsGPT#594]
### 📜 Description

Ordered and unordered lists looks the same(with discs). It seems to me that ordered list should be numbered.
Also sometime with long values it break layout

### 👟 Reproduction steps

1. Go to dialog
2. Ask to give you ordered\unorderd list

### 👍 Expected behavior

Ordered list should be numbered
Unordered list should have a disc as marker(as it is)
Long values should look in the same way as shorter(not on the next line after marker)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/5084613/d215fd6f-45c5-4552-a66f-bf87acec2929)
![image](https://github.com/arc53/DocsGPT/assets/5084613/58d2ed6b-eca6-46e4-b85a-6e1f87f4fd25)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome, Something else

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Appreciate it!

**Comment by krabbi** [comment]
Also noticed that sublists are flat
![image](https://github.com/arc53/DocsGPT/assets/5084613/721248b0-3b22-4542-8cd9-bd78636787f3)
Fixed with PR above

**Comment by krabbi** [comment]
resolved with https://github.com/arc53/DocsGPT/pull/623
