### ISSUE TITLE
Stream of warnings about chunk size longer than the specified 1500

### ISSUE THREAD

**Issue by jwulf** [arc53/DocsGPT#60]
Ingestion of a large text file emits a stream of warnings similar to the following:

> Created a chunk of size 2799, which is longer than the specified 1500

I'm not sure what this means (what the implications are), and what I should do about this. 

I read the comment in the source code that says: 

`# We do this due to the context limits of the LLMs.`

Does this mean that uploading this data set will be a waste of money - that it won't work?
Is there something that I can do to mitigate this?

A more helpful message - maybe even with a link to more info - would be great.

**Comment by dartpain** [comment]
Should be solved in #54
