### ISSUE TITLE
🚀 Feature: Multiple Docs Knowledge Database and Chinese Language Support

### ISSUE THREAD

**Issue by mamingsuper** [arc53/DocsGPT#604]
### 🔖 Feature description

Dear friends,

Thanks for developing this fantastic tool!

I was wondering it would be fantastic if it could support inquiry toward multiple docs.

I have tried other tools like Quivr but found it performs not well regarding multiple rounds of conversation, which means it easily forget former prompt and responses.

Also, asking DocGPT in Chinese cannot achieve same level performance compared to asking in English. Do not know the reasons.

Thanks and looking forward to see updates in the future.

### 🎤 Why is this feature needed ?

Multiple documents is useful for understanding complex questions.

### ✌️ How do you aim to achieve this?

a function could upload multiple documents and transform it into embeddings.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
You can currently upload in a .zip, but yeah i agree multiple files in the frontend is a needed feature

**Comment by dartpain** [comment]
Multiple docs is a separate issue bundles with remote syncable sources.
We recently added translations btw
