### ISSUE TITLE
🐛 Bug Report: Wrong redirection after pressing about button

### ISSUE THREAD

**Issue by MSaiKiran9** [arc53/DocsGPT#605]
### 📜 Description

When pressed about button it's redirecting to the landing page automatically it's wrong redirection & ruins the user experience !

### 👟 Reproduction steps
goto : [docsgpt.arc53.com/](https://docsgpt.arc53.com/)
Click on the about button .

### 👍 Expected behavior

It should just display the about page.

### 👎 Actual Behavior with Screenshots

https://github.com/arc53/DocsGPT/assets/116418856/773c9384-9b9d-4bc5-a9f4-526e4f1387c2

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MSaiKiran9** [comment]
@dartpain let me know if it's a valied issue to work on !

**Comment by tenokami** [comment]
@MSaiKiran9 Assigning to you!

**Comment by MSaiKiran9** [comment]
@tenokami @dartpain As this issue isn't showing up in main repo clone , if it's irrelevant please close this issue else suggest me how to approach solving this ?

**Comment by tenokami** [comment]
@dartpain Please confirm if we don't have this issue it the most recent build

**Comment by dartpain** [comment]
Closing it
