### ISSUE TITLE
🐛 Bug Report: Upload Button overflows when the PDF File Name is large

### ISSUE THREAD

**Issue by Rutam21** [arc53/DocsGPT#608]
### 📜 Description

The Upload button on the UI moves out of the left navigation pane when the PDF file name is large.

### 👟 Reproduction steps

- Name a PDF file something like `WorldHealthCovidDataAnalysisDataset.pdf`.
- Upload the file on the UI.
- In the Source Docs selection section, select this newly uploaded file.

### 👍 Expected behavior

The name should be adjusted within the container properly and the upload button should stay inside the left navigation pane.

Something like this:

![uploadDocs](https://github.com/arc53/DocsGPT/assets/47860497/67c828e3-9acb-4689-90a0-43a6eb5544ff)

### 👎 Actual Behavior with Screenshots

But the container showing the PDF file name expands and thus the Upload button goes out of the left navigation panel.

![uploadDocsBug](https://github.com/arc53/DocsGPT/assets/47860497/2ee6a581-7564-41ea-bde3-42c5608c6f07)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

This is irrelevant for this bug as this is only a UI Fix.

### 📃 Provide any additional context for the Bug.

This needs to be changed in the `/frontend` folder as it relates to a UI/UX bug.

### 📖 Relevant log output

```shell
Log outputs are irrelevant for this bug.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gourav2609** [comment]
Can i work on this issue

**Comment by Gourav2609** [comment]
Can i work on this issue

**Comment by Rutam21** [comment]
@Gourav2609 Feel free to work on this and open a PR as you're the 1st person to comment. Someone from the team will assign it to you. Join the Discord to resolve your queries, if any. Thanks for your contribution 👍 

cc: @dartpain @tenokami

**Comment by Gourav2609** [comment]
sure @Rutam21 ....will open a PR soon

**Comment by just-ctrlC-ctrlV** [comment]
@dartpain can u assign this issue to me?

**Comment by dartpain** [comment]
Assigned to @Gourav2609 
Thank you for the enthusiasm @just-ctrlC-ctrlV

**Comment by dartpain** [comment]
@Rutam21 I appreciate you!

**Comment by Gourav2609** [comment]
@Rutam21 @dartpain @tenokami Please review the PR #676

**Comment by dartpain** [comment]
Done, thank you!
