### ISSUE TITLE
🚀 Feature: Creating a Separate page for Signup and Signin 

### ISSUE THREAD

**Issue by Hemant2335** [arc53/DocsGPT#611]
### 🔖 Feature description

This feature brings more Interactivity into the website for the users because in current state it looks no so good to just click over there and get a popped out signup and signin page so i can create a new page for that purpose with some great UI and will try to keep the same vibe with that page too 

### 🎤 Why is this feature needed ?

This feature is needed for the future developments like in future you might wanted to add some more things to the Homepage then it might not be the good idea to keep signup and signin button on the homepage itself 

### ✌️ How do you aim to achieve this?

As I am quite proficient in react and tailwind and using these I can easily achieve this .

### 🔄️ Additional Information
Please assign this issue to me

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by codeslayed** [comment]
yes please assign me this

**Comment by dartpain** [comment]
@Hemant2335 I really do appreciate your enthusiasm. Please create UI first, just simple mock desing such that @tenokami  can approve it and the you can proceed with the chages.

**Comment by Hemant2335** [comment]
> @Hemant2335 I really do appreciate your enthusiasm. Please create UI first, just simple mock desing such that @tenokami  can approve it and the you can proceed with the chages.

Okk I am on it

**Comment by Hemant2335** [comment]
I have created a figma design link : 
https://www.figma.com/file/I6CU2tCjvjUvbvFzukRGWR/Login_mockup?type=design&node-id=0%3A1&mode=design&t=Sos0T5JhsDwPIDMS-1

And mockup image : 
![Group 7](https://github.com/arc53/DocsGPT/assets/85656999/085586db-0400-45ac-9c52-974e4fb51b5d)

**Comment by tenokami** [comment]
@Hemant2335 Thank you! Font looks too bold comparatively to what is we have. Continue should be our main purple color

For more consistency we could use the same MUI style input fields that are already in DocsGPT

I think the cricles around socials icons in neutral state aren't needed

"Or continue with" I'd prefer not to use capitalization on every word here cause it lowers readability

The illustration on the right could be replaced with something more "on brand" Like some art we have on tshirts @dartpain 

I don't see the "forgot password" button. We can have it right? @dartpain 

I'd replace icons. I'd go with something more minimalistic

**Comment by tenokami** [comment]
@Hemant2335 Would you be so kind to update the design according to this feedback?

After that Ill polish it up and maybe we can proceed with implementation

**Comment by Hemant2335** [comment]
Thank you for the feedback, I'll be updating you soon

**Comment by Hemant2335** [comment]
I have Made the required changes the updated image : 
<img width="1000" alt="Group 3" src="https://github.com/arc53/DocsGPT/assets/85656999/adabca2c-0cc9-432c-9382-a9b717e180ca">

If I left something or misinterpreted , please let me know

Thank you

**Comment by tenokami** [comment]
@dartpain What picture would you like to use on the right

**Comment by Hemant2335** [comment]
Ok I'll catch up from there

**Comment by Hemant2335** [comment]
Ok I'll catch you from there

**Comment by jamsnrihk** [comment]
> @Hemant2335 Thank you. I will polish this and then let you know when it is ready for implementation

any update for this?

**Comment by Hemant2335** [comment]
No reply came from @tenokami regarding design

**Comment by tenokami** [comment]
> No reply came from @tenokami regarding design

I apologize for giving no response. I need to confirm something regarding updating the design of authorization

**Comment by Hemant2335** [comment]
Okay got it

**Comment by dartpain** [comment]
I think @tenokami can advise in terms of desing, but I want something simple, maybe just a form in a middle

**Comment by tenokami** [comment]
@Hemant2335 Thank you for waiting!

The design for Login/Registration is [here](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=WgoMoXk3o0PumXdL-1) 

It includes hover and select effects. The state when input is active and for error states. Also validation text is at the end

**Comment by Hemant2335** [comment]
Okk Thank you Nick , Should I start Working on the same

**Comment by tenokami** [comment]
@Hemant2335 We would appreciate it!

**Comment by Rutam21** [comment]
@tenokami This issue can be closed now as the changes are merged in https://github.com/arc53/DocsGPT/pull/799
