### ISSUE TITLE
🐛 Bug Report: Header is broken in mobile viewports.

### ISSUE THREAD

**Issue by Bitnagar** [arc53/DocsGPT#618]
### 📜 Description

Currently the header stays at the back and everything else flows over it while chatting with the docs, as shown below

![image](https://github.com/arc53/DocsGPT/assets/88842947/7bc82d1c-9f3d-492d-817f-836bd494c0a7)

### 👟 Reproduction steps

- Go to the website, login and train the model.
- Start chatting. Send a couple of prompts.
- Reduce the window size, scroll the messages and observe the header/nav and the issue.

### 👍 Expected behavior

The header should be at the front.

![image](https://github.com/arc53/DocsGPT/assets/88842947/2a485af6-a473-4c08-9711-1b95f7828989)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/88842947/7e9bf749-3539-49cb-97c3-590f08985fb9)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bitnagar** [comment]
I am willing to submit a PR. Kindly assign. Thanks!

**Comment by chinmay7016** [comment]
I am willing to submit a PR. Kindly assign. Thanks!

**Comment by Anurag-space** [comment]
@Bitnagar 
Yes, I am willing to submit a PR!

**Comment by Creativecuts45** [comment]
@Bitnagar pls I wanna contribute pls assign me
