### ISSUE TITLE
🐛 Bug Report: GPT Switching  Dropdown getting overlapped

### ISSUE THREAD

**Issue by lakshmi930** [arc53/DocsGPT#644]
### 📜 Description

Switching the GPT version as a new user using the dropdown is broken, that is the last item is getting hidden behind the input box.

### 👟 Reproduction steps

1. I am a new user with no chats
2. I see GPT 3.5 as option to choose and I click
3. On clicking, a dropdown opens with multiple options
4. I try scrolling but the last 1 or 2 items are always behind the input box.an 

### 👍 Expected behavior

It should let users scroll through all the items and the two should not overlap each other.

### 👎 Actual Behavior with Screenshots

It is actually that there's an overlap with the dropdown and the input button
<img width="246" alt="Screen Shot 2023-10-19 at 1 34 35 AM" src="https://github.com/arc53/DocsGPT/assets/79132440/3de6935a-d430-47dd-946a-2466fb95a2d6">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

It actually happened on https://docsgpt.arc53.com/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shivam-shah12** [comment]
Yes, I am willing to submit a PR!

**Comment by dartpain** [comment]
Its on a cloud version, thus does not apply to open source one. Thank you!
