### ISSUE TITLE
🐛 Bug Report: About-section is not properly aligned in the center on about page.

### ISSUE THREAD

**Issue by Ankit-Matth** [arc53/DocsGPT#645]
### 📜 Description

According to figma design the about-section (on the about page) should be aligned in the center. 
But, actually, it is attached with the bottom instead of in the center as shown below in the screenshots.

### 👟 Reproduction steps

1. Go to home page on DocsGPT. 
2. Click on the About (go to the about page).
3. See the error.

### 👍 Expected behavior

It should be aligned to the center, as shown below :

![expected_aboutPage](https://github.com/arc53/DocsGPT/assets/146843890/c34faa31-3d63-4f45-b93d-3974a915fc5b)

### 👎 Actual Behavior with Screenshots

On the about page, the about-section is attached with the bottom instead of in the center :

![actual_aboutPage](https://github.com/arc53/DocsGPT/assets/146843890/0f422326-2191-4fe9-97b3-176ad313b17e)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 📃 Provide any additional context for the Bug.

Hey @dartpain, I want to fix this bug, please assign this issue to me.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ankit-Matth** [comment]
Hey @dartpain, I have started working on it, please assign this isssue to me.

**Comment by Ankit-Matth** [comment]
Hey @SamsShow, that's not fair. I've created this issue and it also says "I'm willing to submit a PR". Apart from this I also commented for the assignment.
Now, it is quite clear that this will be assigned to me, not you because I am the first one to come to this issue.

**Comment by SamsShow** [comment]
It's okay the issue was open and wasn't been assigned to anyone that's why I fixed the issue
