### ISSUE TITLE
🐛 Bug Report: The home page doesn't match with Figma design.

### ISSUE THREAD

**Issue by Ankit-Matth** [arc53/DocsGPT#646]
### 📜 Description

As per Figma design, there should be proper margin around the three boxes on the home page and all the boxes should be the same size. But in reality, there is no margin around all three boxes and the rightmost box is also larger in size.

### 👟 Reproduction steps

1. Go to the home page.
2. See the error.

### 👍 Expected behavior

As per Figma design, there should be proper margin around the three boxes on the home page as shown below :

![expected](https://github.com/arc53/DocsGPT/assets/146843890/0f15ee9a-70b6-45cf-afc5-5431f7e3e992)

### 👎 Actual Behavior with Screenshots

There is no margin around all three boxes and the rightmost box is also larger in size :

![actual](https://github.com/arc53/DocsGPT/assets/146843890/bf5f41c7-0531-4ff7-869b-83a42c27c6d2)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 📃 Provide any additional context for the Bug.

Sir, I want to fix this bug, please assign this issue to me.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ankit-Matth** [comment]
Hey @dartpain, please assign this issue to me.

**Comment by Shivam-shah12** [comment]
hii , please assign this issue to me.

**Comment by Ankit-Matth** [comment]
Sorry @Shivam-Shah12, but I am already working on this issue..
Since this issue was created by me, it will be assigned to me fairly.

**Comment by Ankit-Matth** [comment]
Hey @tenokami, please tell me which of the following preferable :-

1. ![sample1.jpg](https://github.com/arc53/DocsGPT/assets/146843890/bc7438f8-22d3-43d0-a00e-de701039ab46)

2. ![sample2.jpg](https://github.com/arc53/DocsGPT/assets/146843890/d344915d-821e-414d-afd1-71682ac26506)

**Which design should I make 1 or 2?**

**Comment by tenokami** [comment]
@Ankit-Matth The first one. But I feel like somebody already did this...

**Comment by tenokami** [comment]
@Ankit-Matth here https://github.com/arc53/DocsGPT/issues/419

**Comment by Ankit-Matth** [comment]
> @Ankit-Matth The first one. But I feel like somebody already did this...

No worries!
