### ISSUE TITLE
🚀 Feature:  Custom Page Not Found page

### ISSUE THREAD

**Issue by parthrc** [arc53/DocsGPT#648]
### 🔖 Feature description

A custom 404 page with link to the homepage when a user visits a page which does not exist.

### 🎤 Why is this feature needed ?

Currently when a user tries to visit a page which does not exist, a vercel error page is shown which contains a link to the vercel documentation which is confusing for the user. The feature above if implemented will greatly improve user experience and keeps users on our website.

### ✌️ How do you aim to achieve this?

I would create a new route to handle pages which do not exist.

### 🔄️ Additional Information

I am willing to submit a PR, please assign it to me. Thank you.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rakshixh** [comment]
Hey, @parthrc I'm also interested to contribute for this 404 page. Please let me know if we can collaborate on this.

**Comment by Shivam-shah12** [comment]
hi parth, I'm interested to contribute . Kindly assign

**Comment by parthrc** [comment]
@dartpain any feedback?
