### ISSUE TITLE
🐛 Bug Report: UI Bug on Source Doci

### ISSUE THREAD

**Issue by lakshmi930** [arc53/DocsGPT#657]
### 📜 Description

Small UI Bug on Source Documentation Dropdown

### 👟 Reproduction steps

1. Open the DocsGPT
2. Focus at the Source Docs Dropdown
3. Click on it and see the arrow rotation

### 👍 Expected behavior

The arrow should point downwards in rest state and should be upwards on active/open state

### 👎 Actual Behavior with Screenshots

Rest State:
<img width="300" alt="Screen Shot 2023-10-19 at 1 33 26 AM" src="https://github.com/arc53/DocsGPT/assets/79132440/a152340b-691e-4bbf-ba0b-6941ec175301">

Active/ Open State:
<img width="298" alt="Screen Shot 2023-10-19 at 1 33 37 AM" src="https://github.com/arc53/DocsGPT/assets/79132440/8bf03e33-cce1-4825-b8f6-7965335abab4">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmi930** [comment]
@tenokami Can you please let me know if this is something I can fix or is there revamp already planned that I can pick up if there's no issue assigned for it yet?

**Comment by tenokami** [comment]
@lakshmi930 Assigned. Thx

**Comment by lakshmi930** [comment]
Hello, checked locally the issue is no longer there, so closing this.
