### ISSUE TITLE
🐛 Bug Report: Select Source Documentaiton modal blocks interface

### ISSUE THREAD

**Issue by pablo-aledo** [arc53/DocsGPT#660]
### 📜 Description

Following the installation instructions, both running with `run.sh` and with `run-with-docker-compose.sh`, when executing for the first time, a modal requesting the source documentaiton prevents using the page.

![image](https://github.com/arc53/DocsGPT/assets/2785725/693da6a5-a550-4ec8-b98a-a92e97722d0c)

Application contains the indexes with the default documentation:

```
-rw-rw-r-- 1 pga_gcp_10 pga_gcp_10 343K Oct 19 11:41 index.faiss
-rw-rw-r-- 1 pga_gcp_10 pga_gcp_10  27K Oct 19 11:41 index.pkl
```

### 👟 Reproduction steps

./run.sh

Follow the instructions

open localhost:5173

### 👍 Expected behavior

I can use the interface

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/2785725/693da6a5-a550-4ec8-b98a-a92e97722d0c)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

API_KEY
LLM_NAME
VITE_API_STREAMING

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthasdey2304** [comment]
I would love to work on this issue would you please assign this to me!

**Comment by pablo-aledo** [comment]
I can't assign issues to developers, but I would be happy if you have a look. Please tell me if you need anything :).

Thanks!!

**Comment by Zexiong-Xiang** [comment]
I have the same question

**Comment by gyxxgzy** [comment]
I also have the same question

**Comment by finalxcode** [comment]
@pablo-aledo i also have the same problem

**Comment by blue-eyed-g** [comment]
me too, did u solve it?

**Comment by dartpain** [comment]
Its a networking issue, happens if your frontend cannot connect to the backend.
Please avoid creating similar issues and describe how you launched docsgpt and your environment.
Ensure that Both frontend and backend containers are exposed and accessible, and that frontend is aware of correct backend location.
