### ISSUE TITLE
🚀 Feature: Add "Settings" Button to sidebar

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#664]
### 🔖 Feature description

"Settings" Button to sidebar. When it's clicked, It opens a page within DocsGPT which will have a headline and 4 empty tabs (no content inside tabs at the moment):

For both light and dark themes

General, Prompts, Documents, Widgets.

![image](https://github.com/arc53/DocsGPT/assets/17906039/775d6f97-5f4f-42dc-8bae-e3b5750fa26a)
![image](https://github.com/arc53/DocsGPT/assets/17906039/5e065039-7b88-4378-b29c-adbdbade116e)
![image](https://github.com/arc53/DocsGPT/assets/17906039/ad2272d4-90d7-4944-b528-b15a94aa52a2)
![image](https://github.com/arc53/DocsGPT/assets/17906039/5dcd1705-e03a-47ae-a7be-c66bdb9f62d1)

Figma: 

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=hodJdNH0wH8O0Tu6-1

### 🎤 Why is this feature needed ?

Adding a new page "Settings" with tabs will create a good place to put DocsGPT settings such as language select, theme, prompts, documents, widgets and more

### ✌️ How do you aim to achieve this?

By adding a new page "Settings" with tabs and then adding elements to these pages

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by SamsShow** [comment]
I would like to work on this issue Please Assign this to me

**Comment by tenokami** [comment]
@SamsShow thank you

**Comment by tenokami** [comment]
@SamsShow For the mobile screen size, I would like the tabs to scroll horizontally please. Similar to YouTube

**Comment by SamsShow** [comment]
I'm a frontend Developer and I'm an intermediate so I'll try to complete as much I can

**Comment by SoumyadiptoPal** [comment]
I would like to work on this issue. Pls assign this to me

**Comment by SamsShow** [comment]
@SoumyadiptoPal i think you haven't checked the Figma file for the complete setting page functions

**Comment by SamsShow** [comment]
@tenokami please create a separate branch for this as i have completed the 50% work so i want to push that code so that you review it

**Comment by dartpain** [comment]
@SamsShow  I ahve created a branch, thank you!

**Comment by SamsShow** [comment]
@tenokami please review the code and the issue I've mentioned in my PR

**Comment by tenokami** [comment]
@SamsShow Hey. Code review is for @dartpain 

Thank you! I need to get the clickable preview to test everything

**Comment by SamsShow** [comment]
> @SamsShow Hey. Code review is for @dartpain
> 
> Thank you! I need to get the clickable preview to test everything

ok thank you please review the code and update me so that I can make changes if needed any from my side @dartpain

**Comment by SamsShow** [comment]
@tenokami here's a preview 
[Screencast from 2023-10-31 01-06-52.webm](https://github.com/arc53/DocsGPT/assets/74039834/dc020925-0307-4089-8b76-4f3a4713c9af)
