### ISSUE TITLE
🐛 Bug Report: "Something went wrong" message is broken

### ISSUE THREAD

**Issue by lakshmi930** [arc53/DocsGPT#666]
### 📜 Description

The "Something went wrong" message pops when the stream has failed to fetch to the question. 

### 👟 Reproduction steps

1. Open a new chat
2. Ask a question
3. If the fetch stream failed, the error message will be shown.

*The fetch streaming can be blocked via network requests.

### 👍 Expected behavior

The icon and test should be in one line

<img width="971" alt="image" src="https://github.com/arc53/DocsGPT/assets/79132440/30757327-e5b9-46f0-aff4-2b79ad33084b">

### 👎 Actual Behavior with Screenshots

<img width="1134" alt="image" src="https://github.com/arc53/DocsGPT/assets/79132440/6c4aa585-b7d9-4b96-ad6e-a78f80eabae3">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmi930** [comment]
@tenokami if there's no further change on this bubble, do you mind if I raise a PR? Thank you.

**Comment by tenokami** [comment]
@lakshmi930 Please go ahead. But @dartpain will have to approve it
