### ISSUE TITLE
🚀 Feature: Improve Mobile Responsiveness for Home Page

### ISSUE THREAD

**Issue by varundhand** [arc53/DocsGPT#682]
### 🔖 Feature description

Currently, when users access the home page of the DocsGPT website via **mobile devices**, the users **need to scroll down** in order to **access** the input field, which is highly **inconvenient**.

Hence, this issue aims to enhance the **mobile responsiveness** of the _home page_, ensuring that users can instantly input their queries without the need for unnecessary scrolling.

### 🎤 Why is this feature needed ?

_The users need to scroll down in order to access the input field:_ 

https://github.com/arc53/DocsGPT/assets/110025628/cdee8d26-0f96-48b9-8b81-a5307d2556c8

### ✌️ How do you aim to achieve this?

**- Mobile-Responsive Classes:** I utilised Tailwind CSS classes to make various page elements adapt seamlessly to different screen sizes.

**- JavaScript Conditional Rendering:** To detect the user's screen width dynamically, I implemented conditional rendering using JavaScript and the `window.innerWidth` property. 

### 🔄️ Additional Information

_The corrected version would look somewhat like this:_

![Screenshot 2023-10-24 at 6 21 32 PM](https://github.com/arc53/DocsGPT/assets/110025628/f6e6c68f-8438-4549-a84d-e514a6356227)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Vaibhav91one** [comment]
Is this issue still open @dartpain .

**Comment by dartpain** [comment]
@varundhand nearly finished his PR
