### ISSUE TITLE
🚀 Feature: How to use the Docsgpt-40b-falcon model as my local model.

### ISSUE THREAD

**Issue by Jallen-Yang** [arc53/DocsGPT#687]
### 🔖 Feature description

The local installation uses the Docsgpt-7b-f16 model by default. But if I want to use the Docsgpt-40b-falcon model, where can I download it and what configurations should I modify?

### 🎤 Why is this feature needed ?

Use the Docsgpt-40b-falcon model as my local model.

### ✌️ How do you aim to achieve this?

Use the Docsgpt-40b-falcon model as my local model.

### 🔄️ Additional Information

None.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
I think we need to create a guide on how to load external models, good issue, if someone is interested to pick it up it would be great. 
Basically there are 2 ways right now:
1. Through huggingface
2. through llama.cpp

**Comment by IamSenthilKumar** [comment]
Hi @dartpain, I would like to work on this issue, I think from the `docs/pages/Guides/How-to-use-different-LLM.md` guide, there is option to choose models, by configuring .env file and below are the available models:
- openai
- manifest
- cohere
- Arc53/docsgpt-14b
- Arc53/docsgpt-7b-falcon
- llama.cpp

1. Through huggingface, we can use those 4 available fine-tuned models (llama-2 [7b and 14b] and falcon[7b and 40b]). If we use hf module(`application/llm/huggingface.py`), the default model is **Arc53/DocsGPT-7B**. Here we can change it via .env file and use it in `huggingface.py` module.
2. Through llama.cpp as it uses the default quantized model **docsgpt-7b-f16.gguf** from the settings module, but the `LLM_NAME` is set as "openai". I think it should be configured and overridden via .env file. Am I right?

**Comment by dartpain** [comment]
Good issue please do @IamSenthilKumar 
1. Yep
2. No LLM_NAME should be llama.cpp

Thank you

**Comment by Jallen-Yang** [comment]
HI @dartpain ，I try to use Docsgpt-7b-falcon model.But there are some things what I  wonde:
1.I should set "LLM_NAME=Arc53/docsgpt-7b-falcon" in .env file,isn't is?
2.But what I should set the "EMBEDDINGS_NAME" parameter in .env file?
3.I also found there is " MODEL_PATH: str = os.path.join(current_dir, "models/docsgpt-7b-f16.gguf")" sets in application/core/settings.py file ,should I change it?

**Comment by IamSenthilKumar** [comment]
> Good issue please do @IamSenthilKumar
> 
>     1. Yep
> 
>     2. No LLM_NAME should be llama.cpp
> 
> 
> Thank you

Ok @dartpain. Could you please clarify the 2nd one, is the `Settings` class from the `application/core/settings.py` module is alternate of .env file for configuring application.

Thank you.

**Comment by dartpain** [comment]
Settings.py uses your .env file settings. such that if you set LLM_NAME='llama.cpp' your settings.py will use those values

**Comment by bonuschild** [comment]
> Hi @dartpain, I would like to work on this issue, I think from the `docs/pages/Guides/How-to-use-different-LLM.md` guide, there is option to choose models, by configuring .env file and below are the available models:
> 
> * openai
> * manifest
> * cohere
> * Arc53/docsgpt-14b
> * Arc53/docsgpt-7b-falcon
> * llama.cpp
> 
> 1. Through huggingface, we can use those 4 available fine-tuned models (llama-2 [7b and 14b] and falcon[7b and 40b]). If we use hf module(`application/llm/huggingface.py`), the default model is **Arc53/DocsGPT-7B**. Here we can change it via .env file and use it in `huggingface.py` module.
> 2. Through llama.cpp as it uses the default quantized model **docsgpt-7b-f16.gguf** from the settings module, but the `LLM_NAME` is set as "openai". I think it should be configured and overridden via .env file. Am I right?

Is it correct that we can deploy a total local offline system with docsgpt-7b-falcon model instead of using OpenAI ChatGPT interface online?
> I just want to make sure of this because I saw nothing on the homepage README.md of this repository about content on local deploying :)

**Comment by dartpain** [comment]
Yea @bonuschild check out setup.sh file, it can set up your system this way

**Comment by bonuschild** [comment]
> Contributor

I will try it out now :) Thanks~

**Comment by IamSenthilKumar** [comment]
Hi @dartpain, #754 resolves this issue, could you please close it? 
Thanks
