### ISSUE TITLE
🐛 Bug Report: Misspelling on button

### ISSUE THREAD

**Issue by CBID2** [arc53/DocsGPT#700]
### 📜 Description

I was scrolling through the website, and noticed the Submit button that is supposed to take people to the chat is spelled as "Sumbit". This can cause users to wonder if they have to submit their questions. 

### 👟 Reproduction steps

1. Go to the main site
2. Go to the bubble that says "Need help with documentation?
DocsGPT AI assistant will help you with docs
Ask DocsGPT"
3. See a button that says Sumbit

### 👍 Expected behavior

Users know to submit their questions. 

### 👎 Actual Behavior with Screenshots

![screenshot of error](https://github.com/arc53/DocsGPT/assets/105683440/446d5aa4-01f4-4a73-ab6c-59c856d3ad8e)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CBID2** [comment]
Solved

**Comment by DevanshKyada27** [comment]
Hey @dartpain can I work on this issue?
Can you please assign me with this issue.
