### ISSUE TITLE
🚀 Feature: ChatGPT responds with old version of documentation rather than provided documentation

### ISSUE THREAD

**Issue by luhanbing** [arc53/DocsGPT#708]
### 🔖 Feature description

Improve default prompt and/or language model chaining and retrieval in order to provide responses based on the latest version of documentation and not old answers from original training.

### 🎤 Why is this feature needed ?

ChatGPT's training dataset contains very old versions of documentation websites.

Even after using DocsGPT to provide only the latest version of the documentation, ChatGPT still provides old answers which don't work anymore, based on the old version of the documentation it originally learned.

**How can we improve DocsGPT so that ChatGPT responds giving answers based on the latest documentation provided to DocsGPT** and stops providing answers based on old documentation version that ChatGPT was originally trained on by OpenAI?

For long established software, there are many breaking changes over the years, so it's important that DocsGPT prioritises the documentation that is provided to it rather than the ChatGPT model's learning of a very old version of the documentation.

### ✌️ How do you aim to achieve this?

Improve default prompt and/or language model chaining and retrieval in order to provide responses based on the latest version of documentation and not old answers from original training.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
Usually to achieve this result you need to upload index with the source material that you want the questions to be answered on top of. 
Have you tried uploading source docs?

**Comment by luhanbing** [comment]
Can you clarify what you mean by _uploading source docs_?

If you mean uploading a ZIP of Markdown files from the latest documentation site and then choosing that source from the drop-down in the UI, then yes, that is the issue I am reporting (perhaps I could have been clearer above).

I expected the default behavior of DocsGPT would be to prioritize the latest version of docs (i.e. the uploaded docs rather than ChatGPT's original training which includes the very old version of the docs website).

So DocsGPT with ChatGPT backend appears to currently have very limited value for well established projects (that are old enough projects for ChatGPT to have originally trained on the old versions of their docs) as it can provide a lot of outdated responses that are no longer relevant or correct.

I assume their are improvement that we can make to the default DocsGPT prompt and/or language model chaining and retrieval in order to resolve this and make DocsGPT more useful for well established projects that ChatGPT originally trained on?

**Comment by dartpain** [comment]
I see, In this case I would recommend making your prompts strict to use only the information from the uploaded docs:
https://docs.docsgpt.co.uk/Guides/My-AI-answers-questions-using-external-knowledge
