### ISSUE TITLE
🚀 Feature: How to batch train files without OpenAI?

### ISSUE THREAD

**Issue by Jallen-Yang** [arc53/DocsGPT#713]
### 🔖 Feature description

Following the guidance from https://github.com/arc53/DocsGPT/wiki/How-to-train-on-other-documentation, I can batch train files. But this requires openai. What I want to ask is how can I batch train my files when I can't connect to openai or use local model.

### 🎤 Why is this feature needed ?

 Batch training files without OpenAI use local model.

### ✌️ How do you aim to achieve this?

 Batch training files without OpenAI use local model.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
You can use huggingface model, for embeddings, make sure you set EMBEDDINGS_NAME to huggingface_sentence-transformers/all-mpnet-base-v2
