### ISSUE TITLE
🚀 Feature: Sidebar & Logo update

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#720]
### 🔖 Feature description

 UI update for DocsGPT sidebar
 https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=M8rjHZLwUfyo6UXk-1
 
 1. New sidebar for light and dark themes. 
 2. Replaced logo on "home" and "about" screens and also next to chat messages that are from DocsGPT
 
![image](https://github.com/arc53/DocsGPT/assets/17906039/c3670db9-92db-4206-9a50-7615772dc351)
![image](https://github.com/arc53/DocsGPT/assets/17906039/d3e36587-d030-468e-a3dd-ed7c5dfbf3c7)

![image](https://github.com/arc53/DocsGPT/assets/17906039/8bb08209-541f-4cf8-8ae2-9df2fbb46fc3)
![image](https://github.com/arc53/DocsGPT/assets/17906039/25d5e248-fa37-434a-a309-76bf50b25f89)

![image](https://github.com/arc53/DocsGPT/assets/17906039/2ac403ab-ffb1-4cde-926f-93292dad0cc5)
![image](https://github.com/arc53/DocsGPT/assets/17906039/6e670484-585a-41b4-b358-ed01030319a4)

### 🎤 Why is this feature needed ?

UI/UX improvements

### ✌️ How do you aim to achieve this?

UI/UX improvements

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by ayan-joshi** [comment]
I want to work on this issue @tenokami

**Comment by tenokami** [comment]
@ayan-joshi  Thank you!

**Comment by ayan-joshi** [comment]
> @ayan-joshi Thank you!

Can you help me find the path for the file

**Comment by lakshmi930** [comment]
Can I work on this issue as well?

**Comment by tenokami** [comment]
> > @ayan-joshi Thank you!
> 
> 
> 
> Can you help me find the path for the file 

@dartpain help

**Comment by tenokami** [comment]
@lakshmi930 @ayan-joshi You can collaborate with each other

**Comment by tenokami** [comment]
@ayan-joshi let me know if you want to collaborate and then I'll also assign @lakshmi930

**Comment by lakshmi930** [comment]
@tenokami just to confirm the hover effect on "New Chat" button, search input, and the Chat list are also part of this feature?

**Comment by tenokami** [comment]
> @tenokami just to confirm the hover effect on "New Chat" button, search input, and the Chat list are also part of this feature?

"New chat" button yes. Search input: don't have a hover for it in Figma. But can make one. It could be a slight darkening of the borders of the input on hover and use universally for all inputs in this app. Not sure what you mean by the chat list hover. Currently there is already implemented hover effect for chats.

**Comment by lakshmi930** [comment]
I meant the arrangement itself. After the new chats button, next element is a search input field and a heading with a list of all previous chats. Didn't see this locally but is part of the figma so wanted to know if this is also part of the change.

**Comment by tenokami** [comment]
@lakshmi930 Oh. Yes we are adding the heading "Chats"

**Comment by lakshmi930** [comment]
Okay, adding both.

**Comment by lakshmi930** [comment]
@tenokami Thank you for the quick responses!
