### ISSUE TITLE
🚀 Feature: Implement "Uploads from different sources" 

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#726]
### 🔖 Feature description

Slight redesign + new features for the upload new documentation modal.

![image](https://github.com/arc53/DocsGPT/assets/17906039/3f897850-4339-4c68-abd1-6304d10329aa)
![image](https://github.com/arc53/DocsGPT/assets/17906039/81e23d3a-d9d5-42c0-b5f8-a9cc11f20de6)
![image](https://github.com/arc53/DocsGPT/assets/17906039/fcc5dd2d-ca08-4849-91c9-6d56bf69b128)
![image](https://github.com/arc53/DocsGPT/assets/17906039/6b3f68bc-14b8-4465-b85b-77cef487d252)

https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=0%3A1&mode=design&t=DZMPxtSnArUQwzc5-1

### 🎤 Why is this feature needed ?

UI/UX + technical updates

### ✌️ How do you aim to achieve this?

UI/UX + technical updates

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by khushi2502** [comment]
Hi @tenokami, please assign me this issue. I would like to work on this.

**Comment by tenokami** [comment]
@khushi2502 Thank you!

**Comment by khushi2502** [comment]
Hi, you can assign this issue to someone else as I'm not able to currently work on it. 
Thank you.
