### ISSUE TITLE
🐛 Bug Report: DocsGPT version gets hidden on smaller screen

### ISSUE THREAD

**Issue by Vaibhav91one** [arc53/DocsGPT#735]
### 📜 Description

https://github.com/arc53/DocsGPT/assets/108279746/8bb2f814-12e9-411d-985a-76183aa08e6c

The version select gets hidden when on smaller screens.

### 👟 Reproduction steps

1. Open drop down from the version select.
2. Open inspect and go to a smaller screen size.
3. And click outside the select and it will vanish.

### 👍 Expected behavior

It should be present  on smaller screens.

### 👎 Actual Behavior with Screenshots

--

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vaibhav91one** [comment]
@dartpain Can you look into this, if this if genuine or not and assign me.

**Comment by dartpain** [comment]
This is a cloud version bug and it was fixed. Thank you!
