### ISSUE TITLE
🐛 Bug Report: MacOS cannot hold two file with same filename but different character cases in a same folder

### ISSUE THREAD

**Issue by Jarvan12th** [arc53/DocsGPT#736]
### 📜 Description

After cloning this repository onto an Apple M1 Pro, it shows changes in the files located at (frontend/src/assets/) named checkMark.svg. This might be because macOS cannot hold two files with the same filename but with different character cases in the same folder.
![image](https://github.com/arc53/DocsGPT/assets/48536395/fcffa455-35fa-479b-b274-a42faea11d58)

### 👟 Reproduction steps

Clone this repository onto an Apple machine.

### 👍 Expected behavior

No changes are shown after cloning.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/48536395/dcb59fb3-bc8d-428b-84ed-9cb991749f00)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Ahhh i see, ok ill do a quick rename

**Comment by dartpain** [comment]
Fixed, thank you for reporting the issue!
