### ISSUE TITLE
🚀 Feature: UI/UX Improvement for icons

### ISSUE THREAD

**Issue by tenokami** [arc53/DocsGPT#740]
### 🔖 Feature description

![image](https://github.com/arc53/DocsGPT/assets/17906039/16f1dee1-62a6-4a6f-a0df-3edf4f244629)

Change icons for tab scrolling to the ones in figma, use the hover state style for when it is clicked:

![image](https://github.com/arc53/DocsGPT/assets/17906039/b2af5cda-1625-4d47-aa8c-a4bed5963da6)

Link to selection: https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&node-id=2490%3A5297&mode=design&t=O1hn2rLEcaC8uvUa-1

Link to project: https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?type=design&mode=design&t=O1hn2rLEcaC8uvUa-1

### 🎤 Why is this feature needed ?

UI/UX enhancement 

### ✌️ How do you aim to achieve this?

UI/UX enhancement 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by SoumyadiptoPal** [comment]
@tenokami Please assign this issue to me. I want to work on it
