### ISSUE TITLE
🐛 Bug Report: Error While trying to generate a response Local LLM

### ISSUE THREAD

**Issue by Aiman-astios** [arc53/DocsGPT#745]
### 📜 Description

This error popped up when DocsGPT trying to response.

### 👟 Reproduction steps

1. execute setup.sh 2. ask question on the web browser. 3. got 500 error and message Something went wrong. Please try again later. 4. check on the logs found the cause (image attached above).

### 👍 Expected behavior

it should response to the question.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/110952815/dadd31e6-6191-4d1d-b622-ef3db7194372)

![image](https://github.com/arc53/DocsGPT/assets/110952815/208702be-1825-4ba9-a7d3-82f1232d063a)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Antonio-Vela** [comment]
In settings change this line:
`EMBEDDINGS_NAME: str = "openai_text-embedding-ada-002"
`
by this one:
`EMBEDDINGS_NAME: str = "huggingface_sentence-transformers/all-mpnet-base-v2"
`

**Comment by dartpain** [comment]
Also please upload your own docs. as default ones use the openai embeddings

**Comment by Aiman-astios** [comment]
> In settings change this line: `EMBEDDINGS_NAME: str = "openai_text-embedding-ada-002" ` by this one: `EMBEDDINGS_NAME: str = "huggingface_sentence-transformers/all-mpnet-base-v2" `

Orait thanks for that insight will test it out.

**Comment by Aiman-astios** [comment]
> Also please upload your own docs. as default ones use the openai embeddings

owh thanks for the information, but when i upload my custom docs other issue arise where the response take too long to have a feedback and i think [Antonio-Vela](https://github.com/Antonio-Vela) idea will solved that issue.

**Comment by dartpain** [comment]
What issue did you get @Aiman-astios
