### ISSUE TITLE
🚀 Feature: reply with markdown style support

### ISSUE THREAD

**Issue by bonuschild** [arc53/DocsGPT#760]
### 🔖 Feature description

reply with markdown style support

### 🎤 Why is this feature needed ?

Currently it does not have this feature, comparing to other GPT frontend like https://github.com/Yidadaa/ChatGPT-Next-Web and others.

### ✌️ How do you aim to achieve this?

Reach the effect how https://github.com/Yidadaa/ChatGPT-Next-Web does...or ChatGPT style.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
We already have Markdown styling 
<img width="906" alt="Screenshot 2023-11-03 at 12 56 04" src="https://github.com/arc53/DocsGPT/assets/15183589/c3fce418-5ac3-43ce-b702-7dad1ae58a0f">

If you have something more specific that you want to add or improve I would highly appreciate it.
Thank you!

**Comment by bonuschild** [comment]
Wow, I may misunderstanding the markdown implementation. I take the example page as the current stats:
![image](https://github.com/arc53/DocsGPT/assets/135304748/2aa38f4e-acc1-4e0e-8616-006a531cbd9f)

So may be the markdown hint "```" won't display markdown style but it is OK, thanks!

**Comment by dartpain** [comment]
Hmmm, try reloading the page again or try to click on that conversation please

**Comment by dartpain** [comment]
And make sure you have the latest version too please
