### ISSUE TITLE
Create setting API backend

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#761]
Tasks

- [x] Modify /stream to accept saved prompt id or name
- [x] Modify /api/answer to accept saved prompt id or name
- [x] Api to create prompt
- [x] Api to get existing prompts
- [x] Api to delete prompt
- [x] Api to change prompts name

**Comment by AnshuPathak-88825** [comment]
can I work on it @dartpain

**Comment by dartpain** [comment]
Sorry, I already started working on this issue, if you want to help, we need to create a lot of tests, most of the code is not covered yet

Thank you!

**Comment by AnshuPathak-88825** [comment]
sure I'm ready to create test when code is done  please ping me up
