### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by kevin-pki** [arc53/DocsGPT#767]
### 📜 Description

I installed DocsGPT myself, then uploaded the pdf file (first API), the second API kept returning PROGRESS, and finally the API returned 500 errors.
![image](https://github.com/arc53/DocsGPT/assets/79350043/bdd1f718-9f9a-44e0-8233-6f68b69d8cca)

/api/upload
return
{
  "status": "ok",
  "task_id": "eb5d3a3c-efbf-490a-a041-a2e0ed0123d8"
}
/api/task_status?task_id=eb5d3a3c-efbf-490a-a041-a2e0ed0123d8
return
{
  "result": {
    "current": 1
  },
  "status": "PROGRESS"
}
![image](https://github.com/arc53/DocsGPT/assets/79350043/b8a3836e-8f40-429e-9b0e-794502113f7d)

### 👟 Reproduction steps

I installed DocsGPT myself, then uploaded the pdf file (first API), the second API kept returning PROGRESS, and finally the API returned 500 errors
/api/upload
return
{
  "status": "ok",
  "task_id": "eb5d3a3c-efbf-490a-a041-a2e0ed0123d8"
}
/api/task_status?task_id=eb5d3a3c-efbf-490a-a041-a2e0ed0123d8
return
{
  "result": {
    "current": 1
  },
  "status": "PROGRESS"
}
![image](https://github.com/arc53/DocsGPT/assets/79350043/e92dd118-b0b2-4031-a344-ccd328c8b4f6)

### 👍 Expected behavior

succeed

### 👎 Actual Behavior with Screenshots

api return 500 error

### 💻 Operating system

Linux

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Do you have any error trace from your upload?

**Comment by kevin-pki** [comment]
> Do you have any error trace from your upload?

I've been stuck in this picture
![image](https://github.com/arc53/DocsGPT/assets/79350043/60f46624-551a-4025-950a-ad6c6f1da817)
