### ISSUE TITLE
🐛 Bug Report:  Error in faiss::FileIOReader::FileIOReader(const char*) 

### ISSUE THREAD

**Issue by kevin-pki** [arc53/DocsGPT#768]
### 📜 Description

I installed DocsGPT myself, used default, then asked and returned 500 errors. 
/api/answer
request
{
    "question": "What is DocsGPT?",
    "api_key": "",
    "embeddings_key": "",
    "history": [
        {
            "prompt": "What is DocsGPT?"
        }
    ],
    "active_docs": "local/default/",
    "conversation_id": null
}
return
{
  "error": "Internal Server Error",
  "message": "You exceeded your current quota, please check your plan and billing details."
}

Use python 3.11.1
/api/answer
request
{
    "question": "What is DocsGPT?",
    "api_key": "",
    "embeddings_key": "",
    "history": [
        {
            "prompt": "What is DocsGPT?"
        }
    ],
    "active_docs": "python/.project/3.11.1/openai_text-embedding-ada-002/",
    "conversation_id": null
}
return
{
  "error": "Internal Server Error",
  "message": "Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open application/vectors/python/.project/3.11.1/openai_text-embedding-ada-002/index.faiss for reading: No such file or directory"
}

### 👟 Reproduction steps

I installed DocsGPT myself, used default, then asked and returned 500 errors
/api/answer
request
{
    "question": "What is DocsGPT?",
    "api_key": "",
    "embeddings_key": "",
    "history": [
        {
            "prompt": "What is DocsGPT?"
        }
    ],
    "active_docs": "local/default/",
    "conversation_id": null
}
return
{
  "error": "Internal Server Error",
  "message": "You exceeded your current quota, please check your plan and billing details."
}

Use python 3.11.1
/api/answer
request
{
    "question": "What is DocsGPT?",
    "api_key": "",
    "embeddings_key": "",
    "history": [
        {
            "prompt": "What is DocsGPT?"
        }
    ],
    "active_docs": "python/.project/3.11.1/openai_text-embedding-ada-002/",
    "conversation_id": null
}
return
{
  "error": "Internal Server Error",
  "message": "Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open application/vectors/python/.project/3.11.1/openai_text-embedding-ada-002/index.faiss for reading: No such file or directory"
}

### 👍 Expected behavior

Get the answer

### 👎 Actual Behavior with Screenshots

return 500 error

### 💻 Operating system

Linux

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
So you launched with docker-compose, whats in your .env file?

**Comment by kevin-pki** [comment]
> So you launched with docker-compose, whats in your .env file?

yes

.env file:
API_KEY=
LLM_NAME=openai
VITE_API_STREAMING=false
