### ISSUE TITLE
🐛 Bug Report: UI fix is needed when clicking on API-docs.md, text overflowing

### ISSUE THREAD

**Issue by shriyaMadan** [arc53/DocsGPT#769]
### 📜 Description

Under the sources we see 2 options:
 1. API-docs.md 
 2. How-to-use-different-LLM.md

When I click on "1. API-docs.md", a text line is **overflowing** out of the text-box, this is because the complete statement has no space between it, and we did not add styling for such case, so the styling needs to be fixed.

### 👟 Reproduction steps

1. Type "Hi"/"Hello" in the textbox
2. You will see sources fetching 2 options for you 1. API-docs.md  2. How-to-use-different-LLM.md  
3. Click on "1. API-docs.md"
4. A textbox is received with overflowing text line, which is our bug to be fixed.

### 👍 Expected behavior

The text line in the above mentioned Description should break according to the response's text-box confinement.

### 👎 Actual Behavior with Screenshots

<img width="1715" alt="image" src="https://github.com/arc53/DocsGPT/assets/38863530/dfe78708-57bb-409a-adef-5b9c579ef643">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome, Safari

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 📃 Provide any additional context for the Bug.

I see this bug on the live site running at https://docsgpt.arc53.com/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shriyaMadan** [comment]
please assign this issue to me, thanks!

**Comment by HeetVekariya** [comment]
- @dartpain I have found the solution for this issue. If no one is working on this issue, i can make a PR.

Approach:
- I don't wanted to make the content scroll-able, so add the css to break-down the long words and wrap onto the next line using **```word-wrap: break-word;```**
- Screenshort
![Screenshot from 2023-11-21 11-01-30](https://github.com/arc53/DocsGPT/assets/91054457/d1629010-658d-46a6-8534-35fa4ce52229)
- If you find this solution correct, can you please assign this issue to me.

**Comment by shriyaMadan** [comment]
Yes this is the right solution that I wanted to apply in the codebase. But the issue for me is that I am unable to run and test this dialog message locally, the backend setup for me isn't working as per the instructions using Docker.
