### ISSUE TITLE
Extract out common modal functionalities to a generic modal component

### ISSUE THREAD

**Issue by ajaythapliyal** [arc53/DocsGPT#78]
[Both of the existing modal components](https://www.figma.com/file/OXLtrl1EAy885to6S69554/DocsGPT?node-id=0%3A1&t=Xqi6tyl2G3mghdiP-0) have few things in common:
1]They both overlay over existing page. Both have similar CSS design(rounded corners, shadows).
2]Both have some similar functions as well, both will go away when "save" is clicked. As for now one of them have cancellation feature but as we add more modals, this too can be a common functionality.

These things should be moved to a generic <Modal> component. This modal will accept :
1]`save` click handler as a prop
2]`isCancellable` boolean prop to decide whether to enable the cancellable feature or not.
3]The actually view to render as [render prop](https://www.patterns.dev/posts/render-props-pattern/)

**Comment by Sukhacoder02** [comment]
Hey @dartpain, I have worked upon the above and would like you to please review the [PR](https://github.com/arc53/DocsGPT/pull/275).

**Comment by mj06092000** [comment]
@Sukhacoder02 @ajaythapliyal @larinam @jbampton 
I've reviewed the progress on this issue, and it looks like a valuable addition to our project. Extracting common modal functionalities into a generic modal component can help improve code maintainability and reduce duplication.

Is there anything specific you'd like assistance with, or any blockers you're facing in implementing this feature? Please let me know if there are any discussions or decisions to be made regarding the design or implementation details. I'm here to help and collaborate on this!

Looking forward to seeing this enhancement in action. Keep up the great work!

**Comment by Sukhacoder02** [comment]
Hey @mj06092000, the PR got merged the same day and is in action now. 😉

**Comment by rakshit087** [comment]
Since the PR is merged can we close this issue?

**Comment by Sukhacoder02** [comment]
Yep, please do.
