### ISSUE TITLE
🐛 Bug Report: Upload Hanging on demo url

### ISSUE THREAD

**Issue by jlsodai** [arc53/DocsGPT#787]
### 📜 Description

Upload stalls at 100% on Demo URL — [https://docsgpt.arc53.com/](https://docsgpt.arc53.com/)

<img width="529" alt="image" src="https://github.com/arc53/DocsGPT/assets/10335555/c9f750e9-b07b-4ff1-bbc8-223c6ecd3617">

### 👟 Reproduction steps

- Visit page
- Upload PDF

### 👍 Expected behavior

at 100%, the upload popup should close

### 👎 Actual Behavior with Screenshots

<img width="529" alt="image" src="https://github.com/arc53/DocsGPT/assets/10335555/703284e6-eafe-47f9-9e9f-c0407ef55822">

Upload stalls.

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zexiong-Xiang** [comment]
`i have the same question`
