### ISSUE TITLE
Chrome extension name doesn't contain "DocsGPT" and "documentation" is misspelled 

### ISSUE THREAD

**Issue by jaredbradley243** [arc53/docsgpt#8]
![image](https://user-images.githubusercontent.com/107898107/216800451-b7f41747-565d-47dc-8e6c-653be29cc02f.png)

**Comment by jaredbradley243** [comment]
Pull request opened; Changed extension name and fixed spelling

**Comment by dartpain** [comment]
Finxed in #9
