### ISSUE TITLE
🐛 Bug Report: alt text is redundant 

### ISSUE THREAD

**Issue by CBID2** [arc53/DocsGPT#808]
### 📜 Description

I ran an accessibility test on the Documentation site, and found that some of the alt text is redundant(see proof in the Screenshot section). According to [Deque University](https://dequeuniversity.com/rules/axe/4.7/image-redundant-alt), repetitive alt text can confuse screen readers, thus, making it difficult for users with disabilities to navigate this project's website.  

### 👟 Reproduction steps

N/A

### 👍 Expected behavior

N/A

### 👎 Actual Behavior with Screenshots

Here's a screenshot of the issue
![redundant alt text](https://github.com/arc53/DocsGPT/assets/105683440/6db1361e-1d36-45b5-928b-6968a83f226c)

According to Wave, it recommends the following:
"Ensure that the alternative text for each image or image button is appropriate while removing unnecessary redundancy. If the content of the image is already conveyed elsewhere (through text or the alternative text of a nearby image) or if the image does not convey content, the image may generally be given empty/null alternative text (alt=""). Image buttons always convey a specific function, and thus cannot be given null alternative text."

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EmmanuelAjibokun** [comment]
@CBID2 Hello, I would like to know if you are still working on this issue?

**Comment by CBID2** [comment]
> @CBID2 Hello, I would like to know if you are still working on this issue?

Hi @EmmanuelAjibokun. Yes I will.
