### ISSUE TITLE
Vulnerability report contact person or email

### ISSUE THREAD

**Issue by sylwia-budzynska** [arc53/DocsGPT#815]
### 📜 Description

Hello,

A bit over a month ago I created a vulnerability report via the private vulnerability reporting feature, but I haven't heard back. The report is available [here](https://github.com/arc53/DocsGPT/security/advisories/GHSA-p5qc-vj2x-9rjp). Please let me know if you'd like me to send the report to an email address or in another way. Thank you!

### 👟 Reproduction steps

-

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 💻 Operating system

Linux

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lymah123** [comment]
Hi @sylwia-budzynska , may I know how to get started with this issue?

**Comment by mafaisalhussain** [comment]
Hi @sylwia-budzynska , may I know how to get started with this issue?

**Comment by sylwia-budzynska** [comment]
Hello, only authorized owners of this repository can access the report. If you are an authorized maintainer, please see the details in the report. If you have any questions about the issues, please comment under the report page.

**Comment by dartpain** [comment]
Hi, Thank you for report
