### ISSUE TITLE
Bug: getting 500 server error when no api key is passed

### ISSUE THREAD

**Issue by TAKANOME-DEV** [arc53/DocsGPT#84]
When visiting https://docsgpt.arc53.com/, it will prompt you to add an api key. If you skip that step and send a message, a server error is returned and no visual feedback.

![Screenshot from 2023-02-14 07-48-40](https://user-images.githubusercontent.com/79809121/218672851-66dd0a4a-e622-4ff3-a3ee-20cc11c4351f.png)

## Suggestion
- if api key is required, user shouldn't be able to send a message
- display an error message

**Comment by yash1744** [comment]
Hello, I think this was already resolved in the code, may be we might see an update in the website soon

**Comment by TAKANOME-DEV** [comment]
> Hello, I think this was already resolved in the code, may be we might see an update in the website soon
>
Glad to hear that, thanks 🙂

**Comment by dartpain** [comment]
Will be solved in a new UI
