### ISSUE TITLE
🐛 Bug Report: Large zip breaking stream endpoint

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#859]
### 📜 Description

Stream endpoint doesn't provide answer when embedded file in zip archive is long. 

### 👟 Reproduction steps

1. Upload a zip file 
2. Try chatting 
[docs_tester.zip](https://github.com/arc53/DocsGPT/files/14360514/docs_tester.zip)

### 👍 Expected behavior

DocsGPT should provide an answer. 

### 👎 Actual Behavior with Screenshots

No answer, stream endpoint breaks.
![image](https://github.com/arc53/DocsGPT/assets/32868631/38335663-2500-4f89-9d1d-b322f063b1be)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Looks like it happens because the file is not being chunked properly or at all when answering, thus resulting current context token overload

**Comment by nayelimdejesus** [comment]
Hi, I would like to work on this issue.

**Comment by nayelimdejesus** [comment]
When you upload a big zip file what answer should it provide?

**Comment by dartpain** [comment]
Just shouldn't break. Basically make sure that it doesn't error out.
Try running it with the file attached.

**Comment by jayantp2003** [comment]
I am interested to work on this issue.

**Comment by jayantp2003** [comment]
I was playing around with the zip file and couple of different files, I found that its not an issue related to chunking of code, there is some issue with RstParser class, I did update the file extensions to text file, for that case, it was working fine. 

<img width="544" alt="image" src="https://github.com/user-attachments/assets/e4c4917d-3b2b-485b-9916-7a17c887f45a">

<img width="830" alt="image" src="https://github.com/user-attachments/assets/becb8270-16b4-4045-a94d-9cc0b3a11a7d">


Currently checking the Rstparser class to figure out the changes required.

**Comment by jayantp2003** [comment]
The issue is with the implementation of rst parser, in each file, it looks for a header and a text below it, but for the zip file we are testing on, it is just a single file with no header available, hence it is not being chunked. This header and text breakdown thing also seems to be an issue for markdown parser. The file should be chunked based on tokens or bytes and this tuple implementation also need to be updated.

**Comment by dartpain** [comment]
Yeah seems like thats the issue, lets add another token size handler to it maybe?

**Comment by jayantp2003** [comment]
Can I direclty use nltk tokenizer or should write manual token counting and all? I will update the dependency list

**Comment by jayantp2003** [comment]
Hey, I have updated the code and created a PR, can you review it and approve, I am new to open source contributions and do not know how it works, after making a PR. Open to feedbacks.

**Comment by jayantp2003** [comment]
@dartpain Can you review my changes and provide feedback, and approve if implementation seems correct.
