### ISSUE TITLE
🐛 Bug Report: [CRITICAL] WORKER TIMEOUT (pid:8)

### ISSUE THREAD

**Issue by prakash3113** [arc53/DocsGPT#864]
### 📜 Description

I cloned repo and running app locally but its not working every time i am getting something went wrong

Downloading shards:   0%|          | 0/7 [00:00<?, ?it/s][2024-02-29 11:59:13 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
Downloading shards:   0%|          | 0/7 [01:56<?, ?it/s]
2024-02-29 17:29:13 [2024-02-29 11:59:13 +0000] [8] [INFO] Worker exiting (pid: 8)
2024-02-29 17:29:14 [2024-02-29 11:59:14 +0000] [1] [ERROR] Worker (pid:8) was sent SIGKILL! Perhaps out of memory?
2024-02-29 17:29:14 [2024-02-29 11:59:14 +0000] [112] [INFO] Booting worker with pid: 112

### 👟 Reproduction steps

clone repo create .env and runthe application

### 👍 Expected behavior

It should run properly

### 👎 Actual Behavior with Screenshots

Its giving error

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

API_KEY=
LLM_NAME=DocsGPT
VITE_API_STREAMING=false

### 📃 Provide any additional context for the Bug.

na

### 📖 Relevant log output

```shell
na
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lipeng1109** [comment]
me too

**Comment by dartpain** [comment]
How much memory do you have assigned to docker in your system?
Try 8 gb - should be fine
