### ISSUE TITLE
🐛 Bug Report: The first time you open the system, without adding any files, this interface will pop up. How can you close this page?

### ISSUE THREAD

**Issue by huicewang** [arc53/DocsGPT#865]
### 📜 Description

The first time you open the system, without adding any files, this interface will pop up. How can you close this page?

![image](https://github.com/arc53/DocsGPT/assets/19237481/63324efb-ef57-4831-9dc1-62e75f8c21d7)

### 👟 Reproduction steps

After the project is launched, the first time the page is opened, it is not possible to enter the system.

### 👍 Expected behavior

You can enter the system to perform subsequent operations.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/arc53/DocsGPT/assets/19237481/63324efb-ef57-4831-9dc1-62e75f8c21d7)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huicewang** [comment]
It has been resolved, you can close it now, thank you.

**Comment by dartpain** [comment]
What was the issue, just so that other people might benefit?
