### ISSUE TITLE
🐛 Bug Report: System not working

### ISSUE THREAD

**Issue by bigbenz8** [arc53/DocsGPT#879]
### 📜 Description

I installed ubuntu22.04 on win11 with wsl2, and used . /setup.sh to complete the installation with one click, then I changed the VITE_API_HOST in the docker-compose.yml file to the IP of the ubuntu VM, and started the service using docker-compose up. However, it's almost unusable (except for opening the home page), there are a lot of CORS cross-domain issues on the front-end page, I checked the cors writing in application/app.py and it seems to be fine (no modifications), and there seems to be a timeout in the logs of the backend container (I chose to use docsgpt). Anyway, it's not working at all at the moment. Has anyone encountered the same problem as mine ?  Did the problem get solved in the end? Please help. 

### 👟 Reproduction steps

same as description

### 👍 Expected behavior

same as description

### 👎 Actual Behavior with Screenshots

same as description

### 💻 Operating system

Windows

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
CORS issues show up due to networks inability to connect sometimes. Ensure that the backends address is accessible from frontend. Try adding a domain name on top of backend too - as it can help.
