### ISSUE TITLE
🚀 Feature: Default document change to empty document

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#887]
### 🔖 Feature description

Change default document to empty (no document provided to the model). If the empty document is selected Chunks processed per query should be 0. Add current default as DocsGPT.

 

### 🎤 Why is this feature needed ?

Currently default document has DocsGPT documentation which in my opinion is confusing.

### ✌️ How do you aim to achieve this?

In the Source Doc dropdown change default to empty. While selected no document is used while chatting. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by dartpain** [comment]
Done, assigned.
