### ISSUE TITLE
[FEATURE] Settings to set tokens for message history used

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#909]
This PR consists of 2 parts:

1. Frontend: Create UI in settings general menu to allow users to explicitly set amount of last characters used in current conversation to set how many will be used to process a new answer. Basically a little input field. Add it to the API keys dropdown too.
2. Backend: add parameters to /api/answer and /stream to include those limits for history of messages. Also add it to the /create api key endpoint.

## Acceptance Criteria

 - [ ] **Scenario: User can set token length for message history in settings**
    - Given the user is in the settings general menu
    - When the user inputs a value for the token length
    - Then the token length is saved and used for processing new answers
  
- [ ] **Scenario: Backend API endpoints accept token length parameters**
  - Given the user is using the API endpoints for answering and streaming messages
  - When the user includes the token length parameter in the request
  - Then the backend processes the request with the specified token length
  
- [ ] **Scenario: Token length is applied to API key creation**
  - Given the user is creating a new API key
  - When the user inputs the desired token length
  - Then the API key is generated with the specified token length for message history processing

**Comment by adi790uu** [comment]
@dartpain can you assign me this issue
