### ISSUE TITLE
[Feature] Better error handling on /stream

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#910]
This is a backend and frontend feature again.

Frontend Part:
Accept error type message in a /stream and print it out in the "something went wrong" message. Most of the stuff that needs to be done is in the `/frontend/scr/conversation` directory

Backend Part:
Wrap our /stream function to handle error and stream type: "error reason" if something fails there such that frontend can accept it.

## Acceptance Criteria

 - [ ] **Scenario: Error handling on /stream**
    - Given a user is using the /stream feature
    - When an error occurs during the stream
    - Then the user should see an error message like "error reason"
- [ ] **Scenario: Backend wraps stream function**
  - Given a user is using the /stream feature
  - When an error occurs during the stream
  - Then the backend should wrap the stream function to handle the error and stream type: "error reason"

**Comment by lucastaylor02** [comment]
@dartpain I would like to contribute, but It seems like the issue has already been solved.
if any changes are needed I would be happy to contribute.

**Comment by sarfarazsiddiquii** [comment]
@dartpain, I believe all issues are resolved. Could you please approve the changes and close this issue? 
Thank you!
