### ISSUE TITLE
[Feature] Make the spinner look nice

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#918]
This is how it looks on a dark theme
![CleanShot 2024-04-09 at 21 37 41@2x](https://github.com/arc53/DocsGPT/assets/15183589/ae0a895b-3cb6-4e32-b797-7e96634219dd)

This is before it becomes a spinner
![CleanShot 2024-04-09 at 21 37 54@2x](https://github.com/arc53/DocsGPT/assets/15183589/6aa15202-35d7-4321-a5e9-ae0bbe70bfe7)

Thats how it should looks like when generating answer:
![CleanShot 2024-04-09 at 21 37 14@2x](https://github.com/arc53/DocsGPT/assets/15183589/c0d56100-53c8-4143-94ca-fcf704fa7888)

Should be opposite color for dark theme
![CleanShot 2024-04-09 at 21 36 30@2x](https://github.com/arc53/DocsGPT/assets/15183589/75720ab9-26b8-4b63-bdfe-b943c4bc7ab1)

## Acceptance Criteria

 - [ ] **Scenario: Spinner looks nice on dark theme**
    - Given the spinner is displayed on a dark theme
    - When the spinner is rendered
    - Then the spinner should have a nice appearance and be easily visible on the dark background

**Comment by sundarakanthan** [comment]
can i contribute to this

**Comment by dartpain** [comment]
Assigned you @sundarakanthan 
Thank you!

**Comment by srushtiss** [comment]
Can  I too work on this?

**Comment by shelar1423** [comment]
ill work on it !

**Comment by lwooly** [comment]
@dartpain I'm keen to take a look at this one?

**Comment by dartpain** [comment]
@lwooly  @shelar1423  started working on this issue yesterday. I really appreciate your energy!
Check out this issue, just created it and thought of you!
https://github.com/arc53/DocsGPT/issues/950
