### ISSUE TITLE
🚀 Feature: Button to clean chat history

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#927]
### 🔖 Feature description

Button in settings general, that will delete full chat history.

### 🎤 Why is this feature needed ?

Sometimes people have too many chats and want to clean up

### ✌️ How do you aim to achieve this?

Frontend button that will execute a call to the backend
New Backend endpoint that will delete all chats from mongodb

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by TomasMatarazzo** [comment]
Can i work this? thx

**Comment by dartpain** [comment]
Assigned, Thank you!

**Comment by nishit2003** [comment]
Can I work on this please? Thanks :)

**Comment by srushtiss** [comment]
Can I too work on this?
Thanks

**Comment by SimKach00** [comment]
Can I work on this? Thank you
