### ISSUE TITLE
🐛 Bug Report: Empty document uses default document

### ISSUE THREAD

**Issue by pabik** [arc53/DocsGPT#948]
### 📜 Description

When Empty document is selected documents from pre-uploaded DocsGPT documentation (Default option) is used. 

### 👟 Reproduction steps

1. Choose Empty from Source Doc selector.
2. Ask any question, you will see that DocsGPT still uses Default source doc. 

### 👍 Expected behavior

Upon selecting Empty, model should not receive any documents. 
The behaviour should be the same as if Chunks processed per query is set to 0. 

### 👎 Actual Behavior with Screenshots

Model receives Default documents. 

### 💻 Operating system

Linux

### 🤖 What development environment are you experiencing this bug on?

Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayelimdejesus** [comment]
I would like to be assigned to this issue.

**Comment by areebniyas** [comment]
Hi, could I work on this issue?

**Comment by pabik** [comment]
Hi @areebniyas 
How is it going with this issue, do you need any help?
