### ISSUE TITLE
[Feature] Copy button on code snippet

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#950]
Add copy button on code snippets
![CleanShot 2024-05-15 at 13 45 25@2x](https://github.com/arc53/DocsGPT/assets/15183589/632dd05b-e5af-4fae-a15b-61d44e804d8f)
Should work and look similar to existing copy button next to the message

Should be visible next to code snippets here (where its underlined with yellow)
![CleanShot 2024-05-15 at 13 46 16@2x](https://github.com/arc53/DocsGPT/assets/15183589/ae067e53-f3d5-4a7b-84a2-3a08e024372a)

Should be visible on hover over the code snippet and act similarly to the copy button next to the message

**Comment by sossost** [comment]
Hello,  @dartpain!  I am sossost, a new contributor. Can I resolve this issue??
