### ISSUE TITLE
[FEAT] After a successful upload, source doc should automatically switch to the new one.

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#959]
Currently after a successful upload of a document we just refresh list of source docs. we need to set the new document as active

**Comment by ahsanfarooq210** [comment]
hi @dartpain. I want to work on this issue. please assign it to me

**Comment by utin-francis-peter** [comment]
Hey, @ahsanfarooq210 

How's it going with the issue?

Any updates?
