### ISSUE TITLE
🐛 Bug Report: Token counter adds long delay to message generation

### ISSUE THREAD

**Issue by starkgate** [arc53/DocsGPT#968]
### 📜 Description

When sending a query, DocsGPT generates an answer as expected but is not available right away for a follow up query. The token counting feature makes DocsGPT unresponsive during the counting, causing a delay whose cause is not immediately visible to the user.

### 👟 Reproduction steps

Using a local LLM, send a query then try to send another query immediately after the previous one finishes. Notice how long it takes before you are able to send the next query.

### 👍 Expected behavior

There should be no delay, or the cause of the delay should be visible to the user.

### 👎 Actual Behavior with Screenshots

There is a delay

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome

### 🤖 What development environment are you experiencing this bug on?

Docker

### 📃 Provide any additional context for the Bug.

Since I do not need any token counting for a local LLM, I simply disabled the feature on my side in `usage.py`. This works but is not an ideal solution for anyone that wants to keep such a feature.

![grafik](https://github.com/arc53/DocsGPT/assets/12874678/00bb13a9-8f1a-45d9-80ed-e70faea0f659)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dartpain** [comment]
Yeah, I noticed this issue, happend due to loading tokenizer inside the function here
https://github.com/arc53/DocsGPT/blob/main/application/utils.py
Now I load it outside. Try git pulling, difference should be extremely marginal, if anything we can try using similar tokenizer as in our ingestion function

**Comment by starkgate** [comment]
> Yeah, I noticed this issue, happend due to loading tokenizer inside the function here https://github.com/arc53/DocsGPT/blob/main/application/utils.py Now I load it outside. Try git pulling, difference should be extremely marginal after the update, if anything we can try using smaller tokenizer as in our ingestion function or including an setting in your settings core file

Thanks, will give it a try soon.
