### ISSUE TITLE
Retry button on failed completion

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#978]
![CleanShot 2024-06-04 at 12 18 03@2x](https://github.com/arc53/DocsGPT/assets/15183589/d77cfdf7-a655-4d89-a550-be94ef90ee04)

If there was an error user should be able to click the button to re-generate answer. It will remove previous error and output and answer in its place.

**Comment by rabelmervin** [comment]
Hi sir @dartpain , I'm interested in work on this issue. Could you please provide me the location of the code ???
