### ISSUE TITLE
Translation - Japanese - i18n

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#985]
This issue is here to create japanese translation of our app. Can be done by adding jp.json and translating all field values from en.json
https://github.com/arc53/DocsGPT/tree/main/frontend/src/locale

**Comment by charlesnilsson** [comment]
Do you accept DeepL/Google translation or do you want someone experienced in japanese.

**Comment by dartpain** [comment]
@charlesnilsson  Not necessarily need someone to know japanese, will accept ai translation. Would appreciate if someone with Japanese knowledge can just proofread

**Comment by dartpain** [comment]
Honestly im not sure, try it out, would suggest you try them here 
![CleanShot 2024-06-07 at 15 06 59@2x](https://github.com/arc53/DocsGPT/assets/15183589/cc1aa281-73e0-421c-bc8d-aecb0de9cfaa)
So that we can also see if anything will break in the middle

**Comment by charlesnilsson** [comment]
@dartpain This is my first time trying to make a pull request. If something went wrong, just tell me! 😅
