### ISSUE TITLE
Translation - Mandarin - i18n

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#986]
This issue is here to create Mandarin translation of our app. Can be done by adding json and translating all field values from en.json
https://github.com/arc53/DocsGPT/tree/main/frontend/src/locale

**Comment by vedantbhatter** [comment]
Hey @dartpain, I would love to help out with this. I personally don't know Mandarin but if an AI translation or anything else is good, I can go ahead and do this. Let me know!

**Comment by mohit975** [comment]
Hello
