### ISSUE TITLE
🐛 Bug Report: ImportError: cannot import name 'Celery' from partially initialized module 'celery'

### ISSUE THREAD

**Issue by xucailiang** [arc53/DocsGPT#992]
### 📜 Description

Mac system local deployment failed to start with error: ImportError: cannot import name 'Celery' from partially initialized module 'celery'

<img width="1398" alt="image" src="https://github.com/arc53/DocsGPT/assets/74602715/908ad4d8-e09a-4566-83df-455c84d264c8">

### 👟 Reproduction steps

After downloading the dependency, execute the following command：
 flask --app application/app.py run --host=0.0.0.0 --port=7091

### 👍 Expected behavior

Successfully started and output url and port

### 👎 Actual Behavior with Screenshots

<img width="1398" alt="image" src="https://github.com/arc53/DocsGPT/assets/74602715/908ad4d8-e09a-4566-83df-455c84d264c8">

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Something else

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fengsim** [comment]
check if docker-compose is installed

**Comment by xucailiang** [comment]
> check if docker-compose is installed

Yes, I think I have installed the necessary dependencies, and it can start normally after I rename it to celery_init.py.
