### ISSUE TITLE
🐛 Bug Report: Language switch to Japanese or Mandarin, blackouts the Settings tab selection

### ISSUE THREAD

**Issue by ManishMadan2882** [arc53/DocsGPT#998]
### 📜 Description

In Settings > General
* On changing the language to Mandarin or Japanese the tab selection is lost
[Watch Demo to the bug](https://www.webmobilefirst.com/en/screencasts/2-DMoU_PTS/)

### 👟 Reproduction steps

1. Go to Settings > general
2. Switch language under the Language Selection dropdown to Japanese or Mandarin
3. Any tab can still be selected in the Settings window but the state of current tab is missed 

### 👍 Expected behavior

The language switch should smoothly translate the activeTab

### 👎 Actual Behavior with Screenshots

[Watch Demo of the issue](https://www.webmobilefirst.com/en/screencasts/2-DMoU_PTS/)

### 💻 Operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 🔒 Did you set the correct environment variables in the right path? List the environment variable names (not values please!)

Yes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utin-francis-peter** [comment]
Hi, @dartpain. 

Kindly assign me the issue.

**Comment by utin-francis-peter** [comment]
Closed the prev PR due to some conflicts in commit.  Below is an updated PR:
